// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: standards/v23/administration.proto

package v23

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EVN struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EventTypeCode        string                 `protobuf:"bytes,1,opt,name=event_type_code,json=eventTypeCode,proto3" json:"event_type_code,omitempty"`
	RecordedDt           string                 `protobuf:"bytes,2,opt,name=recorded_dt,json=recordedDt,proto3" json:"recorded_dt,omitempty"`
	PlannedEventDateTime string                 `protobuf:"bytes,3,opt,name=planned_event_date_time,json=plannedEventDateTime,proto3" json:"planned_event_date_time,omitempty"`
	EventReasonCode      string                 `protobuf:"bytes,4,opt,name=event_reason_code,json=eventReasonCode,proto3" json:"event_reason_code,omitempty"`
	OperatorId           *XCN                   `protobuf:"bytes,5,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	EventOccurred        string                 `protobuf:"bytes,6,opt,name=event_occurred,json=eventOccurred,proto3" json:"event_occurred,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EVN) Reset() {
	*x = EVN{}
	mi := &file_standards_v23_administration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EVN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EVN) ProtoMessage() {}

func (x *EVN) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_administration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EVN.ProtoReflect.Descriptor instead.
func (*EVN) Descriptor() ([]byte, []int) {
	return file_standards_v23_administration_proto_rawDescGZIP(), []int{0}
}

func (x *EVN) GetEventTypeCode() string {
	if x != nil {
		return x.EventTypeCode
	}
	return ""
}

func (x *EVN) GetRecordedDt() string {
	if x != nil {
		return x.RecordedDt
	}
	return ""
}

func (x *EVN) GetPlannedEventDateTime() string {
	if x != nil {
		return x.PlannedEventDateTime
	}
	return ""
}

func (x *EVN) GetEventReasonCode() string {
	if x != nil {
		return x.EventReasonCode
	}
	return ""
}

func (x *EVN) GetOperatorId() *XCN {
	if x != nil {
		return x.OperatorId
	}
	return nil
}

func (x *EVN) GetEventOccurred() string {
	if x != nil {
		return x.EventOccurred
	}
	return ""
}

type PID struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SetId                  string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	ExternalPatientId      *CX                    `protobuf:"bytes,2,opt,name=external_patient_id,json=externalPatientId,proto3" json:"external_patient_id,omitempty"`
	InternalPatientId      *CX                    `protobuf:"bytes,3,opt,name=internal_patient_id,json=internalPatientId,proto3" json:"internal_patient_id,omitempty"`
	AlternatePatientId     *CX                    `protobuf:"bytes,4,opt,name=alternate_patient_id,json=alternatePatientId,proto3" json:"alternate_patient_id,omitempty"`
	PatientName            *XPN                   `protobuf:"bytes,5,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	MotherMaidenName       *XPN                   `protobuf:"bytes,6,opt,name=mother_maiden_name,json=motherMaidenName,proto3" json:"mother_maiden_name,omitempty"`
	Dob                    string                 `protobuf:"bytes,7,opt,name=dob,proto3" json:"dob,omitempty"`
	Sex                    string                 `protobuf:"bytes,8,opt,name=sex,proto3" json:"sex,omitempty"`
	PatientAlias           *XPN                   `protobuf:"bytes,9,opt,name=patient_alias,json=patientAlias,proto3" json:"patient_alias,omitempty"`
	Race                   string                 `protobuf:"bytes,10,opt,name=race,proto3" json:"race,omitempty"`
	PatientAddress         *XAD                   `protobuf:"bytes,11,opt,name=patient_address,json=patientAddress,proto3" json:"patient_address,omitempty"`
	CountyCode             string                 `protobuf:"bytes,12,opt,name=county_code,json=countyCode,proto3" json:"county_code,omitempty"`
	HomePhoneNumber        *XTN                   `protobuf:"bytes,13,opt,name=home_phone_number,json=homePhoneNumber,proto3" json:"home_phone_number,omitempty"`
	WorkPhoneNumber        *XTN                   `protobuf:"bytes,14,opt,name=work_phone_number,json=workPhoneNumber,proto3" json:"work_phone_number,omitempty"`
	PrimaryLanguage        *CE                    `protobuf:"bytes,15,opt,name=primary_language,json=primaryLanguage,proto3" json:"primary_language,omitempty"`
	MaritalStatus          string                 `protobuf:"bytes,16,opt,name=marital_status,json=maritalStatus,proto3" json:"marital_status,omitempty"`
	Religion               string                 `protobuf:"bytes,17,opt,name=religion,proto3" json:"religion,omitempty"`
	PatientAccountNumber   *CX                    `protobuf:"bytes,18,opt,name=patient_account_number,json=patientAccountNumber,proto3" json:"patient_account_number,omitempty"`
	Ssn                    string                 `protobuf:"bytes,19,opt,name=ssn,proto3" json:"ssn,omitempty"`
	DriversLicenseNumber   *DLN                   `protobuf:"bytes,20,opt,name=drivers_license_number,json=driversLicenseNumber,proto3" json:"drivers_license_number,omitempty"`
	MotherIdentifier       *CX                    `protobuf:"bytes,21,opt,name=mother_identifier,json=motherIdentifier,proto3" json:"mother_identifier,omitempty"`
	EthnicGroup            string                 `protobuf:"bytes,22,opt,name=ethnic_group,json=ethnicGroup,proto3" json:"ethnic_group,omitempty"`
	BirthPlace             string                 `protobuf:"bytes,23,opt,name=birth_place,json=birthPlace,proto3" json:"birth_place,omitempty"`
	MultipleBirthIndicator string                 `protobuf:"bytes,24,opt,name=multiple_birth_indicator,json=multipleBirthIndicator,proto3" json:"multiple_birth_indicator,omitempty"`
	BirthOrder             string                 `protobuf:"bytes,25,opt,name=birth_order,json=birthOrder,proto3" json:"birth_order,omitempty"`
	Citizenship            string                 `protobuf:"bytes,26,opt,name=citizenship,proto3" json:"citizenship,omitempty"`
	VeteranStatus          *CE                    `protobuf:"bytes,27,opt,name=veteran_status,json=veteranStatus,proto3" json:"veteran_status,omitempty"`
	Nationality            *CE                    `protobuf:"bytes,28,opt,name=nationality,proto3" json:"nationality,omitempty"`
	PatientDeathDateTime   string                 `protobuf:"bytes,29,opt,name=patient_death_date_time,json=patientDeathDateTime,proto3" json:"patient_death_date_time,omitempty"`
	PatientDeathIndicator  string                 `protobuf:"bytes,30,opt,name=patient_death_indicator,json=patientDeathIndicator,proto3" json:"patient_death_indicator,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PID) Reset() {
	*x = PID{}
	mi := &file_standards_v23_administration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID) ProtoMessage() {}

func (x *PID) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_administration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID.ProtoReflect.Descriptor instead.
func (*PID) Descriptor() ([]byte, []int) {
	return file_standards_v23_administration_proto_rawDescGZIP(), []int{1}
}

func (x *PID) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *PID) GetExternalPatientId() *CX {
	if x != nil {
		return x.ExternalPatientId
	}
	return nil
}

func (x *PID) GetInternalPatientId() *CX {
	if x != nil {
		return x.InternalPatientId
	}
	return nil
}

func (x *PID) GetAlternatePatientId() *CX {
	if x != nil {
		return x.AlternatePatientId
	}
	return nil
}

func (x *PID) GetPatientName() *XPN {
	if x != nil {
		return x.PatientName
	}
	return nil
}

func (x *PID) GetMotherMaidenName() *XPN {
	if x != nil {
		return x.MotherMaidenName
	}
	return nil
}

func (x *PID) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *PID) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *PID) GetPatientAlias() *XPN {
	if x != nil {
		return x.PatientAlias
	}
	return nil
}

func (x *PID) GetRace() string {
	if x != nil {
		return x.Race
	}
	return ""
}

func (x *PID) GetPatientAddress() *XAD {
	if x != nil {
		return x.PatientAddress
	}
	return nil
}

func (x *PID) GetCountyCode() string {
	if x != nil {
		return x.CountyCode
	}
	return ""
}

func (x *PID) GetHomePhoneNumber() *XTN {
	if x != nil {
		return x.HomePhoneNumber
	}
	return nil
}

func (x *PID) GetWorkPhoneNumber() *XTN {
	if x != nil {
		return x.WorkPhoneNumber
	}
	return nil
}

func (x *PID) GetPrimaryLanguage() *CE {
	if x != nil {
		return x.PrimaryLanguage
	}
	return nil
}

func (x *PID) GetMaritalStatus() string {
	if x != nil {
		return x.MaritalStatus
	}
	return ""
}

func (x *PID) GetReligion() string {
	if x != nil {
		return x.Religion
	}
	return ""
}

func (x *PID) GetPatientAccountNumber() *CX {
	if x != nil {
		return x.PatientAccountNumber
	}
	return nil
}

func (x *PID) GetSsn() string {
	if x != nil {
		return x.Ssn
	}
	return ""
}

func (x *PID) GetDriversLicenseNumber() *DLN {
	if x != nil {
		return x.DriversLicenseNumber
	}
	return nil
}

func (x *PID) GetMotherIdentifier() *CX {
	if x != nil {
		return x.MotherIdentifier
	}
	return nil
}

func (x *PID) GetEthnicGroup() string {
	if x != nil {
		return x.EthnicGroup
	}
	return ""
}

func (x *PID) GetBirthPlace() string {
	if x != nil {
		return x.BirthPlace
	}
	return ""
}

func (x *PID) GetMultipleBirthIndicator() string {
	if x != nil {
		return x.MultipleBirthIndicator
	}
	return ""
}

func (x *PID) GetBirthOrder() string {
	if x != nil {
		return x.BirthOrder
	}
	return ""
}

func (x *PID) GetCitizenship() string {
	if x != nil {
		return x.Citizenship
	}
	return ""
}

func (x *PID) GetVeteranStatus() *CE {
	if x != nil {
		return x.VeteranStatus
	}
	return nil
}

func (x *PID) GetNationality() *CE {
	if x != nil {
		return x.Nationality
	}
	return nil
}

func (x *PID) GetPatientDeathDateTime() string {
	if x != nil {
		return x.PatientDeathDateTime
	}
	return ""
}

func (x *PID) GetPatientDeathIndicator() string {
	if x != nil {
		return x.PatientDeathIndicator
	}
	return ""
}

type PD1 struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LivingDependency       string                 `protobuf:"bytes,1,opt,name=living_dependency,json=livingDependency,proto3" json:"living_dependency,omitempty"`
	LivingArrangement      string                 `protobuf:"bytes,2,opt,name=living_arrangement,json=livingArrangement,proto3" json:"living_arrangement,omitempty"`
	PatientPrimaryFacility *XON                   `protobuf:"bytes,3,opt,name=patient_primary_facility,json=patientPrimaryFacility,proto3" json:"patient_primary_facility,omitempty"`
	PatientPcpName         *XCN                   `protobuf:"bytes,4,opt,name=patient_pcp_name,json=patientPcpName,proto3" json:"patient_pcp_name,omitempty"`
	StudentIndicator       string                 `protobuf:"bytes,5,opt,name=student_indicator,json=studentIndicator,proto3" json:"student_indicator,omitempty"`
	Handicap               string                 `protobuf:"bytes,6,opt,name=handicap,proto3" json:"handicap,omitempty"`
	LivingWill             string                 `protobuf:"bytes,7,opt,name=living_will,json=livingWill,proto3" json:"living_will,omitempty"`
	OrganDonor             string                 `protobuf:"bytes,8,opt,name=organ_donor,json=organDonor,proto3" json:"organ_donor,omitempty"`
	SeparateBill           string                 `protobuf:"bytes,9,opt,name=separate_bill,json=separateBill,proto3" json:"separate_bill,omitempty"`
	DuplicatePatient       *CX                    `protobuf:"bytes,10,opt,name=duplicate_patient,json=duplicatePatient,proto3" json:"duplicate_patient,omitempty"`
	PublicityIndicator     *CE                    `protobuf:"bytes,11,opt,name=publicity_indicator,json=publicityIndicator,proto3" json:"publicity_indicator,omitempty"`
	ProtectionIndicator    string                 `protobuf:"bytes,12,opt,name=protection_indicator,json=protectionIndicator,proto3" json:"protection_indicator,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PD1) Reset() {
	*x = PD1{}
	mi := &file_standards_v23_administration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PD1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PD1) ProtoMessage() {}

func (x *PD1) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_administration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PD1.ProtoReflect.Descriptor instead.
func (*PD1) Descriptor() ([]byte, []int) {
	return file_standards_v23_administration_proto_rawDescGZIP(), []int{2}
}

func (x *PD1) GetLivingDependency() string {
	if x != nil {
		return x.LivingDependency
	}
	return ""
}

func (x *PD1) GetLivingArrangement() string {
	if x != nil {
		return x.LivingArrangement
	}
	return ""
}

func (x *PD1) GetPatientPrimaryFacility() *XON {
	if x != nil {
		return x.PatientPrimaryFacility
	}
	return nil
}

func (x *PD1) GetPatientPcpName() *XCN {
	if x != nil {
		return x.PatientPcpName
	}
	return nil
}

func (x *PD1) GetStudentIndicator() string {
	if x != nil {
		return x.StudentIndicator
	}
	return ""
}

func (x *PD1) GetHandicap() string {
	if x != nil {
		return x.Handicap
	}
	return ""
}

func (x *PD1) GetLivingWill() string {
	if x != nil {
		return x.LivingWill
	}
	return ""
}

func (x *PD1) GetOrganDonor() string {
	if x != nil {
		return x.OrganDonor
	}
	return ""
}

func (x *PD1) GetSeparateBill() string {
	if x != nil {
		return x.SeparateBill
	}
	return ""
}

func (x *PD1) GetDuplicatePatient() *CX {
	if x != nil {
		return x.DuplicatePatient
	}
	return nil
}

func (x *PD1) GetPublicityIndicator() *CE {
	if x != nil {
		return x.PublicityIndicator
	}
	return nil
}

func (x *PD1) GetProtectionIndicator() string {
	if x != nil {
		return x.ProtectionIndicator
	}
	return ""
}

type AL1 struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SetId              string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	AllergyType        string                 `protobuf:"bytes,2,opt,name=allergy_type,json=allergyType,proto3" json:"allergy_type,omitempty"`
	AllergyCode        *CE                    `protobuf:"bytes,3,opt,name=allergy_code,json=allergyCode,proto3" json:"allergy_code,omitempty"`
	AllergySeverity    string                 `protobuf:"bytes,4,opt,name=allergy_severity,json=allergySeverity,proto3" json:"allergy_severity,omitempty"`
	AllergyReaction    string                 `protobuf:"bytes,5,opt,name=allergy_reaction,json=allergyReaction,proto3" json:"allergy_reaction,omitempty"`
	IdentificationDate string                 `protobuf:"bytes,6,opt,name=identification_date,json=identificationDate,proto3" json:"identification_date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AL1) Reset() {
	*x = AL1{}
	mi := &file_standards_v23_administration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AL1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AL1) ProtoMessage() {}

func (x *AL1) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_administration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AL1.ProtoReflect.Descriptor instead.
func (*AL1) Descriptor() ([]byte, []int) {
	return file_standards_v23_administration_proto_rawDescGZIP(), []int{3}
}

func (x *AL1) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *AL1) GetAllergyType() string {
	if x != nil {
		return x.AllergyType
	}
	return ""
}

func (x *AL1) GetAllergyCode() *CE {
	if x != nil {
		return x.AllergyCode
	}
	return nil
}

func (x *AL1) GetAllergySeverity() string {
	if x != nil {
		return x.AllergySeverity
	}
	return ""
}

func (x *AL1) GetAllergyReaction() string {
	if x != nil {
		return x.AllergyReaction
	}
	return ""
}

func (x *AL1) GetIdentificationDate() string {
	if x != nil {
		return x.IdentificationDate
	}
	return ""
}

type PV1 struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SetId                   string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	PatientClass            string                 `protobuf:"bytes,2,opt,name=patient_class,json=patientClass,proto3" json:"patient_class,omitempty"`
	AssignedPatientLocation *PL                    `protobuf:"bytes,3,opt,name=assigned_patient_location,json=assignedPatientLocation,proto3" json:"assigned_patient_location,omitempty"`
	AdmissionType           string                 `protobuf:"bytes,4,opt,name=admission_type,json=admissionType,proto3" json:"admission_type,omitempty"`
	PreadmitNumber          *CX                    `protobuf:"bytes,5,opt,name=preadmit_number,json=preadmitNumber,proto3" json:"preadmit_number,omitempty"`
	PriorPatientLocation    *PL                    `protobuf:"bytes,6,opt,name=prior_patient_location,json=priorPatientLocation,proto3" json:"prior_patient_location,omitempty"`
	AttendingDoctor         *XCN                   `protobuf:"bytes,7,opt,name=attending_doctor,json=attendingDoctor,proto3" json:"attending_doctor,omitempty"`
	ReferringDoctor         *XCN                   `protobuf:"bytes,8,opt,name=referring_doctor,json=referringDoctor,proto3" json:"referring_doctor,omitempty"`
	ConsultingDoctor        *XCN                   `protobuf:"bytes,9,opt,name=consulting_doctor,json=consultingDoctor,proto3" json:"consulting_doctor,omitempty"`
	HospitalService         string                 `protobuf:"bytes,10,opt,name=hospital_service,json=hospitalService,proto3" json:"hospital_service,omitempty"`
	TemporaryLocation       *PL                    `protobuf:"bytes,11,opt,name=temporary_location,json=temporaryLocation,proto3" json:"temporary_location,omitempty"`
	PreadmitTestIndicator   string                 `protobuf:"bytes,12,opt,name=preadmit_test_indicator,json=preadmitTestIndicator,proto3" json:"preadmit_test_indicator,omitempty"`
	ReadmissionIndicator    string                 `protobuf:"bytes,13,opt,name=readmission_indicator,json=readmissionIndicator,proto3" json:"readmission_indicator,omitempty"`
	AdmitSource             string                 `protobuf:"bytes,14,opt,name=admit_source,json=admitSource,proto3" json:"admit_source,omitempty"`
	AmbulatoryStatus        string                 `protobuf:"bytes,15,opt,name=ambulatory_status,json=ambulatoryStatus,proto3" json:"ambulatory_status,omitempty"`
	VipIndicator            string                 `protobuf:"bytes,16,opt,name=vip_indicator,json=vipIndicator,proto3" json:"vip_indicator,omitempty"`
	AdmittingDoctor         *XCN                   `protobuf:"bytes,17,opt,name=admitting_doctor,json=admittingDoctor,proto3" json:"admitting_doctor,omitempty"`
	PatientType             string                 `protobuf:"bytes,18,opt,name=patient_type,json=patientType,proto3" json:"patient_type,omitempty"`
	VisitNumber             *CX                    `protobuf:"bytes,19,opt,name=visit_number,json=visitNumber,proto3" json:"visit_number,omitempty"`
	FinancialClass          *FC                    `protobuf:"bytes,20,opt,name=financial_class,json=financialClass,proto3" json:"financial_class,omitempty"`
	ChargePriceIndicator    string                 `protobuf:"bytes,21,opt,name=charge_price_indicator,json=chargePriceIndicator,proto3" json:"charge_price_indicator,omitempty"`
	CourtesyCode            string                 `protobuf:"bytes,22,opt,name=courtesy_code,json=courtesyCode,proto3" json:"courtesy_code,omitempty"`
	CreditRating            string                 `protobuf:"bytes,23,opt,name=credit_rating,json=creditRating,proto3" json:"credit_rating,omitempty"`
	ContractCode            string                 `protobuf:"bytes,24,opt,name=contract_code,json=contractCode,proto3" json:"contract_code,omitempty"`
	ContractEffectiveDate   string                 `protobuf:"bytes,25,opt,name=contract_effective_date,json=contractEffectiveDate,proto3" json:"contract_effective_date,omitempty"`
	ContractAmount          string                 `protobuf:"bytes,26,opt,name=contract_amount,json=contractAmount,proto3" json:"contract_amount,omitempty"`
	ContractPeriod          string                 `protobuf:"bytes,27,opt,name=contract_period,json=contractPeriod,proto3" json:"contract_period,omitempty"`
	InterestCode            string                 `protobuf:"bytes,28,opt,name=interest_code,json=interestCode,proto3" json:"interest_code,omitempty"`
	TransferBadDebtCode     string                 `protobuf:"bytes,29,opt,name=transfer_bad_debt_code,json=transferBadDebtCode,proto3" json:"transfer_bad_debt_code,omitempty"`
	TransferBadDebtDate     string                 `protobuf:"bytes,30,opt,name=transfer_bad_debt_date,json=transferBadDebtDate,proto3" json:"transfer_bad_debt_date,omitempty"`
	BadDebtAgencyCode       string                 `protobuf:"bytes,31,opt,name=bad_debt_agency_code,json=badDebtAgencyCode,proto3" json:"bad_debt_agency_code,omitempty"`
	BadDebtTransferAmount   string                 `protobuf:"bytes,32,opt,name=bad_debt_transfer_amount,json=badDebtTransferAmount,proto3" json:"bad_debt_transfer_amount,omitempty"`
	BadDebtRecoveryAmount   string                 `protobuf:"bytes,33,opt,name=bad_debt_recovery_amount,json=badDebtRecoveryAmount,proto3" json:"bad_debt_recovery_amount,omitempty"`
	DeleteAccountIndicator  string                 `protobuf:"bytes,34,opt,name=delete_account_indicator,json=deleteAccountIndicator,proto3" json:"delete_account_indicator,omitempty"`
	DeleteAccountDate       string                 `protobuf:"bytes,35,opt,name=delete_account_date,json=deleteAccountDate,proto3" json:"delete_account_date,omitempty"`
	DischargeDisposition    string                 `protobuf:"bytes,36,opt,name=discharge_disposition,json=dischargeDisposition,proto3" json:"discharge_disposition,omitempty"`
	DischargedToLocation    *CMDSL                 `protobuf:"bytes,37,opt,name=discharged_to_location,json=dischargedToLocation,proto3" json:"discharged_to_location,omitempty"`
	DietType                string                 `protobuf:"bytes,38,opt,name=diet_type,json=dietType,proto3" json:"diet_type,omitempty"`
	ServicingFacility       string                 `protobuf:"bytes,39,opt,name=servicing_facility,json=servicingFacility,proto3" json:"servicing_facility,omitempty"`
	BedStatus               string                 `protobuf:"bytes,40,opt,name=bed_status,json=bedStatus,proto3" json:"bed_status,omitempty"`
	AccountStatus           string                 `protobuf:"bytes,41,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"`
	PendingLocation         *PL                    `protobuf:"bytes,42,opt,name=pending_location,json=pendingLocation,proto3" json:"pending_location,omitempty"`
	PriorTemporaryLocation  *PL                    `protobuf:"bytes,43,opt,name=prior_temporary_location,json=priorTemporaryLocation,proto3" json:"prior_temporary_location,omitempty"`
	AdmitDateTime           string                 `protobuf:"bytes,44,opt,name=admit_date_time,json=admitDateTime,proto3" json:"admit_date_time,omitempty"`
	DischargeDateTime       string                 `protobuf:"bytes,45,opt,name=discharge_date_time,json=dischargeDateTime,proto3" json:"discharge_date_time,omitempty"`
	CurrentPatientBalance   string                 `protobuf:"bytes,46,opt,name=current_patient_balance,json=currentPatientBalance,proto3" json:"current_patient_balance,omitempty"`
	TotalCharges            string                 `protobuf:"bytes,47,opt,name=total_charges,json=totalCharges,proto3" json:"total_charges,omitempty"`
	TotalAdjustments        string                 `protobuf:"bytes,48,opt,name=total_adjustments,json=totalAdjustments,proto3" json:"total_adjustments,omitempty"`
	TotalPayments           string                 `protobuf:"bytes,49,opt,name=total_payments,json=totalPayments,proto3" json:"total_payments,omitempty"`
	AlternateVisitId        *CX                    `protobuf:"bytes,50,opt,name=alternate_visit_id,json=alternateVisitId,proto3" json:"alternate_visit_id,omitempty"`
	VisitIndicator          string                 `protobuf:"bytes,51,opt,name=visit_indicator,json=visitIndicator,proto3" json:"visit_indicator,omitempty"`
	OtherHealthcareProvider *XCN                   `protobuf:"bytes,52,opt,name=other_healthcare_provider,json=otherHealthcareProvider,proto3" json:"other_healthcare_provider,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PV1) Reset() {
	*x = PV1{}
	mi := &file_standards_v23_administration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PV1) ProtoMessage() {}

func (x *PV1) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_administration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PV1.ProtoReflect.Descriptor instead.
func (*PV1) Descriptor() ([]byte, []int) {
	return file_standards_v23_administration_proto_rawDescGZIP(), []int{4}
}

func (x *PV1) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *PV1) GetPatientClass() string {
	if x != nil {
		return x.PatientClass
	}
	return ""
}

func (x *PV1) GetAssignedPatientLocation() *PL {
	if x != nil {
		return x.AssignedPatientLocation
	}
	return nil
}

func (x *PV1) GetAdmissionType() string {
	if x != nil {
		return x.AdmissionType
	}
	return ""
}

func (x *PV1) GetPreadmitNumber() *CX {
	if x != nil {
		return x.PreadmitNumber
	}
	return nil
}

func (x *PV1) GetPriorPatientLocation() *PL {
	if x != nil {
		return x.PriorPatientLocation
	}
	return nil
}

func (x *PV1) GetAttendingDoctor() *XCN {
	if x != nil {
		return x.AttendingDoctor
	}
	return nil
}

func (x *PV1) GetReferringDoctor() *XCN {
	if x != nil {
		return x.ReferringDoctor
	}
	return nil
}

func (x *PV1) GetConsultingDoctor() *XCN {
	if x != nil {
		return x.ConsultingDoctor
	}
	return nil
}

func (x *PV1) GetHospitalService() string {
	if x != nil {
		return x.HospitalService
	}
	return ""
}

func (x *PV1) GetTemporaryLocation() *PL {
	if x != nil {
		return x.TemporaryLocation
	}
	return nil
}

func (x *PV1) GetPreadmitTestIndicator() string {
	if x != nil {
		return x.PreadmitTestIndicator
	}
	return ""
}

func (x *PV1) GetReadmissionIndicator() string {
	if x != nil {
		return x.ReadmissionIndicator
	}
	return ""
}

func (x *PV1) GetAdmitSource() string {
	if x != nil {
		return x.AdmitSource
	}
	return ""
}

func (x *PV1) GetAmbulatoryStatus() string {
	if x != nil {
		return x.AmbulatoryStatus
	}
	return ""
}

func (x *PV1) GetVipIndicator() string {
	if x != nil {
		return x.VipIndicator
	}
	return ""
}

func (x *PV1) GetAdmittingDoctor() *XCN {
	if x != nil {
		return x.AdmittingDoctor
	}
	return nil
}

func (x *PV1) GetPatientType() string {
	if x != nil {
		return x.PatientType
	}
	return ""
}

func (x *PV1) GetVisitNumber() *CX {
	if x != nil {
		return x.VisitNumber
	}
	return nil
}

func (x *PV1) GetFinancialClass() *FC {
	if x != nil {
		return x.FinancialClass
	}
	return nil
}

func (x *PV1) GetChargePriceIndicator() string {
	if x != nil {
		return x.ChargePriceIndicator
	}
	return ""
}

func (x *PV1) GetCourtesyCode() string {
	if x != nil {
		return x.CourtesyCode
	}
	return ""
}

func (x *PV1) GetCreditRating() string {
	if x != nil {
		return x.CreditRating
	}
	return ""
}

func (x *PV1) GetContractCode() string {
	if x != nil {
		return x.ContractCode
	}
	return ""
}

func (x *PV1) GetContractEffectiveDate() string {
	if x != nil {
		return x.ContractEffectiveDate
	}
	return ""
}

func (x *PV1) GetContractAmount() string {
	if x != nil {
		return x.ContractAmount
	}
	return ""
}

func (x *PV1) GetContractPeriod() string {
	if x != nil {
		return x.ContractPeriod
	}
	return ""
}

func (x *PV1) GetInterestCode() string {
	if x != nil {
		return x.InterestCode
	}
	return ""
}

func (x *PV1) GetTransferBadDebtCode() string {
	if x != nil {
		return x.TransferBadDebtCode
	}
	return ""
}

func (x *PV1) GetTransferBadDebtDate() string {
	if x != nil {
		return x.TransferBadDebtDate
	}
	return ""
}

func (x *PV1) GetBadDebtAgencyCode() string {
	if x != nil {
		return x.BadDebtAgencyCode
	}
	return ""
}

func (x *PV1) GetBadDebtTransferAmount() string {
	if x != nil {
		return x.BadDebtTransferAmount
	}
	return ""
}

func (x *PV1) GetBadDebtRecoveryAmount() string {
	if x != nil {
		return x.BadDebtRecoveryAmount
	}
	return ""
}

func (x *PV1) GetDeleteAccountIndicator() string {
	if x != nil {
		return x.DeleteAccountIndicator
	}
	return ""
}

func (x *PV1) GetDeleteAccountDate() string {
	if x != nil {
		return x.DeleteAccountDate
	}
	return ""
}

func (x *PV1) GetDischargeDisposition() string {
	if x != nil {
		return x.DischargeDisposition
	}
	return ""
}

func (x *PV1) GetDischargedToLocation() *CMDSL {
	if x != nil {
		return x.DischargedToLocation
	}
	return nil
}

func (x *PV1) GetDietType() string {
	if x != nil {
		return x.DietType
	}
	return ""
}

func (x *PV1) GetServicingFacility() string {
	if x != nil {
		return x.ServicingFacility
	}
	return ""
}

func (x *PV1) GetBedStatus() string {
	if x != nil {
		return x.BedStatus
	}
	return ""
}

func (x *PV1) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *PV1) GetPendingLocation() *PL {
	if x != nil {
		return x.PendingLocation
	}
	return nil
}

func (x *PV1) GetPriorTemporaryLocation() *PL {
	if x != nil {
		return x.PriorTemporaryLocation
	}
	return nil
}

func (x *PV1) GetAdmitDateTime() string {
	if x != nil {
		return x.AdmitDateTime
	}
	return ""
}

func (x *PV1) GetDischargeDateTime() string {
	if x != nil {
		return x.DischargeDateTime
	}
	return ""
}

func (x *PV1) GetCurrentPatientBalance() string {
	if x != nil {
		return x.CurrentPatientBalance
	}
	return ""
}

func (x *PV1) GetTotalCharges() string {
	if x != nil {
		return x.TotalCharges
	}
	return ""
}

func (x *PV1) GetTotalAdjustments() string {
	if x != nil {
		return x.TotalAdjustments
	}
	return ""
}

func (x *PV1) GetTotalPayments() string {
	if x != nil {
		return x.TotalPayments
	}
	return ""
}

func (x *PV1) GetAlternateVisitId() *CX {
	if x != nil {
		return x.AlternateVisitId
	}
	return nil
}

func (x *PV1) GetVisitIndicator() string {
	if x != nil {
		return x.VisitIndicator
	}
	return ""
}

func (x *PV1) GetOtherHealthcareProvider() *XCN {
	if x != nil {
		return x.OtherHealthcareProvider
	}
	return nil
}

type PV2 struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	PriorPendingLocation              *PL                    `protobuf:"bytes,1,opt,name=prior_pending_location,json=priorPendingLocation,proto3" json:"prior_pending_location,omitempty"`
	AccomodationCode                  *CE                    `protobuf:"bytes,2,opt,name=accomodation_code,json=accomodationCode,proto3" json:"accomodation_code,omitempty"`
	AdmitReason                       *CE                    `protobuf:"bytes,3,opt,name=admit_reason,json=admitReason,proto3" json:"admit_reason,omitempty"`
	TransferReason                    *CE                    `protobuf:"bytes,4,opt,name=transfer_reason,json=transferReason,proto3" json:"transfer_reason,omitempty"`
	PatientValuables                  string                 `protobuf:"bytes,5,opt,name=patient_valuables,json=patientValuables,proto3" json:"patient_valuables,omitempty"`
	PatientValuablesLocation          string                 `protobuf:"bytes,6,opt,name=patient_valuables_location,json=patientValuablesLocation,proto3" json:"patient_valuables_location,omitempty"`
	VisitUserCode                     string                 `protobuf:"bytes,7,opt,name=visit_user_code,json=visitUserCode,proto3" json:"visit_user_code,omitempty"`
	ExpectedAdmitDateTime             string                 `protobuf:"bytes,8,opt,name=expected_admit_date_time,json=expectedAdmitDateTime,proto3" json:"expected_admit_date_time,omitempty"`
	ExpectedDischargeDateTime         string                 `protobuf:"bytes,9,opt,name=expected_discharge_date_time,json=expectedDischargeDateTime,proto3" json:"expected_discharge_date_time,omitempty"`
	EstimatedLengthInpatientStay      string                 `protobuf:"bytes,10,opt,name=estimated_length_inpatient_stay,json=estimatedLengthInpatientStay,proto3" json:"estimated_length_inpatient_stay,omitempty"`
	ActualLengthInpatientStay         string                 `protobuf:"bytes,11,opt,name=actual_length_inpatient_stay,json=actualLengthInpatientStay,proto3" json:"actual_length_inpatient_stay,omitempty"`
	VisitDescription                  string                 `protobuf:"bytes,12,opt,name=visit_description,json=visitDescription,proto3" json:"visit_description,omitempty"`
	ReferralSourceCode                *XCN                   `protobuf:"bytes,13,opt,name=referral_source_code,json=referralSourceCode,proto3" json:"referral_source_code,omitempty"`
	PreviousServiceDate               string                 `protobuf:"bytes,14,opt,name=previous_service_date,json=previousServiceDate,proto3" json:"previous_service_date,omitempty"`
	EmploymentIllnessRelatedIndicator string                 `protobuf:"bytes,15,opt,name=employment_illness_related_indicator,json=employmentIllnessRelatedIndicator,proto3" json:"employment_illness_related_indicator,omitempty"`
	PurgeStatusCode                   string                 `protobuf:"bytes,16,opt,name=purge_status_code,json=purgeStatusCode,proto3" json:"purge_status_code,omitempty"`
	PurgeStatusDate                   string                 `protobuf:"bytes,17,opt,name=purge_status_date,json=purgeStatusDate,proto3" json:"purge_status_date,omitempty"`
	SpecialProgramCode                string                 `protobuf:"bytes,18,opt,name=special_program_code,json=specialProgramCode,proto3" json:"special_program_code,omitempty"`
	RetentionIndicator                string                 `protobuf:"bytes,19,opt,name=retention_indicator,json=retentionIndicator,proto3" json:"retention_indicator,omitempty"`
	ExpectedCountInsurancePlans       string                 `protobuf:"bytes,20,opt,name=expected_count_insurance_plans,json=expectedCountInsurancePlans,proto3" json:"expected_count_insurance_plans,omitempty"`
	VisitPublicityCode                string                 `protobuf:"bytes,21,opt,name=visit_publicity_code,json=visitPublicityCode,proto3" json:"visit_publicity_code,omitempty"`
	VisitProtectionIndicator          string                 `protobuf:"bytes,22,opt,name=visit_protection_indicator,json=visitProtectionIndicator,proto3" json:"visit_protection_indicator,omitempty"`
	ClinicOrganizationName            *XON                   `protobuf:"bytes,23,opt,name=clinic_organization_name,json=clinicOrganizationName,proto3" json:"clinic_organization_name,omitempty"`
	PatientStatusCode                 string                 `protobuf:"bytes,24,opt,name=patient_status_code,json=patientStatusCode,proto3" json:"patient_status_code,omitempty"`
	VisitPriorityCode                 string                 `protobuf:"bytes,25,opt,name=visit_priority_code,json=visitPriorityCode,proto3" json:"visit_priority_code,omitempty"`
	PreviousTreatmentDate             string                 `protobuf:"bytes,26,opt,name=previous_treatment_date,json=previousTreatmentDate,proto3" json:"previous_treatment_date,omitempty"`
	ExpectedDischargeDisposition      string                 `protobuf:"bytes,27,opt,name=expected_discharge_disposition,json=expectedDischargeDisposition,proto3" json:"expected_discharge_disposition,omitempty"`
	FileSignatureDate                 string                 `protobuf:"bytes,28,opt,name=file_signature_date,json=fileSignatureDate,proto3" json:"file_signature_date,omitempty"`
	FirstSimilarIllnessDate           string                 `protobuf:"bytes,29,opt,name=first_similar_illness_date,json=firstSimilarIllnessDate,proto3" json:"first_similar_illness_date,omitempty"`
	PatientChargeAdjustmentCode       string                 `protobuf:"bytes,30,opt,name=patient_charge_adjustment_code,json=patientChargeAdjustmentCode,proto3" json:"patient_charge_adjustment_code,omitempty"`
	RecurringServiceCode              string                 `protobuf:"bytes,31,opt,name=recurring_service_code,json=recurringServiceCode,proto3" json:"recurring_service_code,omitempty"`
	BillingMediaCode                  string                 `protobuf:"bytes,32,opt,name=billing_media_code,json=billingMediaCode,proto3" json:"billing_media_code,omitempty"`
	ExpectedSurgeryDateTime           string                 `protobuf:"bytes,33,opt,name=expected_surgery_date_time,json=expectedSurgeryDateTime,proto3" json:"expected_surgery_date_time,omitempty"`
	MilitaryPartnershipCode           string                 `protobuf:"bytes,34,opt,name=military_partnership_code,json=militaryPartnershipCode,proto3" json:"military_partnership_code,omitempty"`
	MilitaryNonAvailabilityCode       string                 `protobuf:"bytes,35,opt,name=military_non_availability_code,json=militaryNonAvailabilityCode,proto3" json:"military_non_availability_code,omitempty"`
	NewbornBabyIndicator              string                 `protobuf:"bytes,36,opt,name=newborn_baby_indicator,json=newbornBabyIndicator,proto3" json:"newborn_baby_indicator,omitempty"`
	BabyDetainedIndicator             string                 `protobuf:"bytes,37,opt,name=baby_detained_indicator,json=babyDetainedIndicator,proto3" json:"baby_detained_indicator,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *PV2) Reset() {
	*x = PV2{}
	mi := &file_standards_v23_administration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PV2) ProtoMessage() {}

func (x *PV2) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_administration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PV2.ProtoReflect.Descriptor instead.
func (*PV2) Descriptor() ([]byte, []int) {
	return file_standards_v23_administration_proto_rawDescGZIP(), []int{5}
}

func (x *PV2) GetPriorPendingLocation() *PL {
	if x != nil {
		return x.PriorPendingLocation
	}
	return nil
}

func (x *PV2) GetAccomodationCode() *CE {
	if x != nil {
		return x.AccomodationCode
	}
	return nil
}

func (x *PV2) GetAdmitReason() *CE {
	if x != nil {
		return x.AdmitReason
	}
	return nil
}

func (x *PV2) GetTransferReason() *CE {
	if x != nil {
		return x.TransferReason
	}
	return nil
}

func (x *PV2) GetPatientValuables() string {
	if x != nil {
		return x.PatientValuables
	}
	return ""
}

func (x *PV2) GetPatientValuablesLocation() string {
	if x != nil {
		return x.PatientValuablesLocation
	}
	return ""
}

func (x *PV2) GetVisitUserCode() string {
	if x != nil {
		return x.VisitUserCode
	}
	return ""
}

func (x *PV2) GetExpectedAdmitDateTime() string {
	if x != nil {
		return x.ExpectedAdmitDateTime
	}
	return ""
}

func (x *PV2) GetExpectedDischargeDateTime() string {
	if x != nil {
		return x.ExpectedDischargeDateTime
	}
	return ""
}

func (x *PV2) GetEstimatedLengthInpatientStay() string {
	if x != nil {
		return x.EstimatedLengthInpatientStay
	}
	return ""
}

func (x *PV2) GetActualLengthInpatientStay() string {
	if x != nil {
		return x.ActualLengthInpatientStay
	}
	return ""
}

func (x *PV2) GetVisitDescription() string {
	if x != nil {
		return x.VisitDescription
	}
	return ""
}

func (x *PV2) GetReferralSourceCode() *XCN {
	if x != nil {
		return x.ReferralSourceCode
	}
	return nil
}

func (x *PV2) GetPreviousServiceDate() string {
	if x != nil {
		return x.PreviousServiceDate
	}
	return ""
}

func (x *PV2) GetEmploymentIllnessRelatedIndicator() string {
	if x != nil {
		return x.EmploymentIllnessRelatedIndicator
	}
	return ""
}

func (x *PV2) GetPurgeStatusCode() string {
	if x != nil {
		return x.PurgeStatusCode
	}
	return ""
}

func (x *PV2) GetPurgeStatusDate() string {
	if x != nil {
		return x.PurgeStatusDate
	}
	return ""
}

func (x *PV2) GetSpecialProgramCode() string {
	if x != nil {
		return x.SpecialProgramCode
	}
	return ""
}

func (x *PV2) GetRetentionIndicator() string {
	if x != nil {
		return x.RetentionIndicator
	}
	return ""
}

func (x *PV2) GetExpectedCountInsurancePlans() string {
	if x != nil {
		return x.ExpectedCountInsurancePlans
	}
	return ""
}

func (x *PV2) GetVisitPublicityCode() string {
	if x != nil {
		return x.VisitPublicityCode
	}
	return ""
}

func (x *PV2) GetVisitProtectionIndicator() string {
	if x != nil {
		return x.VisitProtectionIndicator
	}
	return ""
}

func (x *PV2) GetClinicOrganizationName() *XON {
	if x != nil {
		return x.ClinicOrganizationName
	}
	return nil
}

func (x *PV2) GetPatientStatusCode() string {
	if x != nil {
		return x.PatientStatusCode
	}
	return ""
}

func (x *PV2) GetVisitPriorityCode() string {
	if x != nil {
		return x.VisitPriorityCode
	}
	return ""
}

func (x *PV2) GetPreviousTreatmentDate() string {
	if x != nil {
		return x.PreviousTreatmentDate
	}
	return ""
}

func (x *PV2) GetExpectedDischargeDisposition() string {
	if x != nil {
		return x.ExpectedDischargeDisposition
	}
	return ""
}

func (x *PV2) GetFileSignatureDate() string {
	if x != nil {
		return x.FileSignatureDate
	}
	return ""
}

func (x *PV2) GetFirstSimilarIllnessDate() string {
	if x != nil {
		return x.FirstSimilarIllnessDate
	}
	return ""
}

func (x *PV2) GetPatientChargeAdjustmentCode() string {
	if x != nil {
		return x.PatientChargeAdjustmentCode
	}
	return ""
}

func (x *PV2) GetRecurringServiceCode() string {
	if x != nil {
		return x.RecurringServiceCode
	}
	return ""
}

func (x *PV2) GetBillingMediaCode() string {
	if x != nil {
		return x.BillingMediaCode
	}
	return ""
}

func (x *PV2) GetExpectedSurgeryDateTime() string {
	if x != nil {
		return x.ExpectedSurgeryDateTime
	}
	return ""
}

func (x *PV2) GetMilitaryPartnershipCode() string {
	if x != nil {
		return x.MilitaryPartnershipCode
	}
	return ""
}

func (x *PV2) GetMilitaryNonAvailabilityCode() string {
	if x != nil {
		return x.MilitaryNonAvailabilityCode
	}
	return ""
}

func (x *PV2) GetNewbornBabyIndicator() string {
	if x != nil {
		return x.NewbornBabyIndicator
	}
	return ""
}

func (x *PV2) GetBabyDetainedIndicator() string {
	if x != nil {
		return x.BabyDetainedIndicator
	}
	return ""
}

var File_standards_v23_administration_proto protoreflect.FileDescriptor

const file_standards_v23_administration_proto_rawDesc = "" +
	"\n" +
	"\"standards/v23/administration.proto\x12\rstandards.v23\x1a\x19standards/v23/types.proto\"\x8d\x02\n" +
	"\x03EVN\x12&\n" +
	"\x0fevent_type_code\x18\x01 \x01(\tR\reventTypeCode\x12\x1f\n" +
	"\vrecorded_dt\x18\x02 \x01(\tR\n" +
	"recordedDt\x125\n" +
	"\x17planned_event_date_time\x18\x03 \x01(\tR\x14plannedEventDateTime\x12*\n" +
	"\x11event_reason_code\x18\x04 \x01(\tR\x0feventReasonCode\x123\n" +
	"\voperator_id\x18\x05 \x01(\v2\x12.standards.v23.XCNR\n" +
	"operatorId\x12%\n" +
	"\x0eevent_occurred\x18\x06 \x01(\tR\reventOccurred\"\xb4\v\n" +
	"\x03PID\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12A\n" +
	"\x13external_patient_id\x18\x02 \x01(\v2\x11.standards.v23.CXR\x11externalPatientId\x12A\n" +
	"\x13internal_patient_id\x18\x03 \x01(\v2\x11.standards.v23.CXR\x11internalPatientId\x12C\n" +
	"\x14alternate_patient_id\x18\x04 \x01(\v2\x11.standards.v23.CXR\x12alternatePatientId\x125\n" +
	"\fpatient_name\x18\x05 \x01(\v2\x12.standards.v23.XPNR\vpatientName\x12@\n" +
	"\x12mother_maiden_name\x18\x06 \x01(\v2\x12.standards.v23.XPNR\x10motherMaidenName\x12\x10\n" +
	"\x03dob\x18\a \x01(\tR\x03dob\x12\x10\n" +
	"\x03sex\x18\b \x01(\tR\x03sex\x127\n" +
	"\rpatient_alias\x18\t \x01(\v2\x12.standards.v23.XPNR\fpatientAlias\x12\x12\n" +
	"\x04race\x18\n" +
	" \x01(\tR\x04race\x12;\n" +
	"\x0fpatient_address\x18\v \x01(\v2\x12.standards.v23.XADR\x0epatientAddress\x12\x1f\n" +
	"\vcounty_code\x18\f \x01(\tR\n" +
	"countyCode\x12>\n" +
	"\x11home_phone_number\x18\r \x01(\v2\x12.standards.v23.XTNR\x0fhomePhoneNumber\x12>\n" +
	"\x11work_phone_number\x18\x0e \x01(\v2\x12.standards.v23.XTNR\x0fworkPhoneNumber\x12<\n" +
	"\x10primary_language\x18\x0f \x01(\v2\x11.standards.v23.CER\x0fprimaryLanguage\x12%\n" +
	"\x0emarital_status\x18\x10 \x01(\tR\rmaritalStatus\x12\x1a\n" +
	"\breligion\x18\x11 \x01(\tR\breligion\x12G\n" +
	"\x16patient_account_number\x18\x12 \x01(\v2\x11.standards.v23.CXR\x14patientAccountNumber\x12\x10\n" +
	"\x03ssn\x18\x13 \x01(\tR\x03ssn\x12H\n" +
	"\x16drivers_license_number\x18\x14 \x01(\v2\x12.standards.v23.DLNR\x14driversLicenseNumber\x12>\n" +
	"\x11mother_identifier\x18\x15 \x01(\v2\x11.standards.v23.CXR\x10motherIdentifier\x12!\n" +
	"\fethnic_group\x18\x16 \x01(\tR\vethnicGroup\x12\x1f\n" +
	"\vbirth_place\x18\x17 \x01(\tR\n" +
	"birthPlace\x128\n" +
	"\x18multiple_birth_indicator\x18\x18 \x01(\tR\x16multipleBirthIndicator\x12\x1f\n" +
	"\vbirth_order\x18\x19 \x01(\tR\n" +
	"birthOrder\x12 \n" +
	"\vcitizenship\x18\x1a \x01(\tR\vcitizenship\x128\n" +
	"\x0eveteran_status\x18\x1b \x01(\v2\x11.standards.v23.CER\rveteranStatus\x123\n" +
	"\vnationality\x18\x1c \x01(\v2\x11.standards.v23.CER\vnationality\x125\n" +
	"\x17patient_death_date_time\x18\x1d \x01(\tR\x14patientDeathDateTime\x126\n" +
	"\x17patient_death_indicator\x18\x1e \x01(\tR\x15patientDeathIndicator\"\xd4\x04\n" +
	"\x03PD1\x12+\n" +
	"\x11living_dependency\x18\x01 \x01(\tR\x10livingDependency\x12-\n" +
	"\x12living_arrangement\x18\x02 \x01(\tR\x11livingArrangement\x12L\n" +
	"\x18patient_primary_facility\x18\x03 \x01(\v2\x12.standards.v23.XONR\x16patientPrimaryFacility\x12<\n" +
	"\x10patient_pcp_name\x18\x04 \x01(\v2\x12.standards.v23.XCNR\x0epatientPcpName\x12+\n" +
	"\x11student_indicator\x18\x05 \x01(\tR\x10studentIndicator\x12\x1a\n" +
	"\bhandicap\x18\x06 \x01(\tR\bhandicap\x12\x1f\n" +
	"\vliving_will\x18\a \x01(\tR\n" +
	"livingWill\x12\x1f\n" +
	"\vorgan_donor\x18\b \x01(\tR\n" +
	"organDonor\x12#\n" +
	"\rseparate_bill\x18\t \x01(\tR\fseparateBill\x12>\n" +
	"\x11duplicate_patient\x18\n" +
	" \x01(\v2\x11.standards.v23.CXR\x10duplicatePatient\x12B\n" +
	"\x13publicity_indicator\x18\v \x01(\v2\x11.standards.v23.CER\x12publicityIndicator\x121\n" +
	"\x14protection_indicator\x18\f \x01(\tR\x13protectionIndicator\"\xfc\x01\n" +
	"\x03AL1\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12!\n" +
	"\fallergy_type\x18\x02 \x01(\tR\vallergyType\x124\n" +
	"\fallergy_code\x18\x03 \x01(\v2\x11.standards.v23.CER\vallergyCode\x12)\n" +
	"\x10allergy_severity\x18\x04 \x01(\tR\x0fallergySeverity\x12)\n" +
	"\x10allergy_reaction\x18\x05 \x01(\tR\x0fallergyReaction\x12/\n" +
	"\x13identification_date\x18\x06 \x01(\tR\x12identificationDate\"\xca\x14\n" +
	"\x03PV1\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12#\n" +
	"\rpatient_class\x18\x02 \x01(\tR\fpatientClass\x12M\n" +
	"\x19assigned_patient_location\x18\x03 \x01(\v2\x11.standards.v23.PLR\x17assignedPatientLocation\x12%\n" +
	"\x0eadmission_type\x18\x04 \x01(\tR\radmissionType\x12:\n" +
	"\x0fpreadmit_number\x18\x05 \x01(\v2\x11.standards.v23.CXR\x0epreadmitNumber\x12G\n" +
	"\x16prior_patient_location\x18\x06 \x01(\v2\x11.standards.v23.PLR\x14priorPatientLocation\x12=\n" +
	"\x10attending_doctor\x18\a \x01(\v2\x12.standards.v23.XCNR\x0fattendingDoctor\x12=\n" +
	"\x10referring_doctor\x18\b \x01(\v2\x12.standards.v23.XCNR\x0freferringDoctor\x12?\n" +
	"\x11consulting_doctor\x18\t \x01(\v2\x12.standards.v23.XCNR\x10consultingDoctor\x12)\n" +
	"\x10hospital_service\x18\n" +
	" \x01(\tR\x0fhospitalService\x12@\n" +
	"\x12temporary_location\x18\v \x01(\v2\x11.standards.v23.PLR\x11temporaryLocation\x126\n" +
	"\x17preadmit_test_indicator\x18\f \x01(\tR\x15preadmitTestIndicator\x123\n" +
	"\x15readmission_indicator\x18\r \x01(\tR\x14readmissionIndicator\x12!\n" +
	"\fadmit_source\x18\x0e \x01(\tR\vadmitSource\x12+\n" +
	"\x11ambulatory_status\x18\x0f \x01(\tR\x10ambulatoryStatus\x12#\n" +
	"\rvip_indicator\x18\x10 \x01(\tR\fvipIndicator\x12=\n" +
	"\x10admitting_doctor\x18\x11 \x01(\v2\x12.standards.v23.XCNR\x0fadmittingDoctor\x12!\n" +
	"\fpatient_type\x18\x12 \x01(\tR\vpatientType\x124\n" +
	"\fvisit_number\x18\x13 \x01(\v2\x11.standards.v23.CXR\vvisitNumber\x12:\n" +
	"\x0ffinancial_class\x18\x14 \x01(\v2\x11.standards.v23.FCR\x0efinancialClass\x124\n" +
	"\x16charge_price_indicator\x18\x15 \x01(\tR\x14chargePriceIndicator\x12#\n" +
	"\rcourtesy_code\x18\x16 \x01(\tR\fcourtesyCode\x12#\n" +
	"\rcredit_rating\x18\x17 \x01(\tR\fcreditRating\x12#\n" +
	"\rcontract_code\x18\x18 \x01(\tR\fcontractCode\x126\n" +
	"\x17contract_effective_date\x18\x19 \x01(\tR\x15contractEffectiveDate\x12'\n" +
	"\x0fcontract_amount\x18\x1a \x01(\tR\x0econtractAmount\x12'\n" +
	"\x0fcontract_period\x18\x1b \x01(\tR\x0econtractPeriod\x12#\n" +
	"\rinterest_code\x18\x1c \x01(\tR\finterestCode\x123\n" +
	"\x16transfer_bad_debt_code\x18\x1d \x01(\tR\x13transferBadDebtCode\x123\n" +
	"\x16transfer_bad_debt_date\x18\x1e \x01(\tR\x13transferBadDebtDate\x12/\n" +
	"\x14bad_debt_agency_code\x18\x1f \x01(\tR\x11badDebtAgencyCode\x127\n" +
	"\x18bad_debt_transfer_amount\x18  \x01(\tR\x15badDebtTransferAmount\x127\n" +
	"\x18bad_debt_recovery_amount\x18! \x01(\tR\x15badDebtRecoveryAmount\x128\n" +
	"\x18delete_account_indicator\x18\" \x01(\tR\x16deleteAccountIndicator\x12.\n" +
	"\x13delete_account_date\x18# \x01(\tR\x11deleteAccountDate\x123\n" +
	"\x15discharge_disposition\x18$ \x01(\tR\x14dischargeDisposition\x12J\n" +
	"\x16discharged_to_location\x18% \x01(\v2\x14.standards.v23.CMDSLR\x14dischargedToLocation\x12\x1b\n" +
	"\tdiet_type\x18& \x01(\tR\bdietType\x12-\n" +
	"\x12servicing_facility\x18' \x01(\tR\x11servicingFacility\x12\x1d\n" +
	"\n" +
	"bed_status\x18( \x01(\tR\tbedStatus\x12%\n" +
	"\x0eaccount_status\x18) \x01(\tR\raccountStatus\x12<\n" +
	"\x10pending_location\x18* \x01(\v2\x11.standards.v23.PLR\x0fpendingLocation\x12K\n" +
	"\x18prior_temporary_location\x18+ \x01(\v2\x11.standards.v23.PLR\x16priorTemporaryLocation\x12&\n" +
	"\x0fadmit_date_time\x18, \x01(\tR\radmitDateTime\x12.\n" +
	"\x13discharge_date_time\x18- \x01(\tR\x11dischargeDateTime\x126\n" +
	"\x17current_patient_balance\x18. \x01(\tR\x15currentPatientBalance\x12#\n" +
	"\rtotal_charges\x18/ \x01(\tR\ftotalCharges\x12+\n" +
	"\x11total_adjustments\x180 \x01(\tR\x10totalAdjustments\x12%\n" +
	"\x0etotal_payments\x181 \x01(\tR\rtotalPayments\x12?\n" +
	"\x12alternate_visit_id\x182 \x01(\v2\x11.standards.v23.CXR\x10alternateVisitId\x12'\n" +
	"\x0fvisit_indicator\x183 \x01(\tR\x0evisitIndicator\x12N\n" +
	"\x19other_healthcare_provider\x184 \x01(\v2\x12.standards.v23.XCNR\x17otherHealthcareProvider\"\xeb\x10\n" +
	"\x03PV2\x12G\n" +
	"\x16prior_pending_location\x18\x01 \x01(\v2\x11.standards.v23.PLR\x14priorPendingLocation\x12>\n" +
	"\x11accomodation_code\x18\x02 \x01(\v2\x11.standards.v23.CER\x10accomodationCode\x124\n" +
	"\fadmit_reason\x18\x03 \x01(\v2\x11.standards.v23.CER\vadmitReason\x12:\n" +
	"\x0ftransfer_reason\x18\x04 \x01(\v2\x11.standards.v23.CER\x0etransferReason\x12+\n" +
	"\x11patient_valuables\x18\x05 \x01(\tR\x10patientValuables\x12<\n" +
	"\x1apatient_valuables_location\x18\x06 \x01(\tR\x18patientValuablesLocation\x12&\n" +
	"\x0fvisit_user_code\x18\a \x01(\tR\rvisitUserCode\x127\n" +
	"\x18expected_admit_date_time\x18\b \x01(\tR\x15expectedAdmitDateTime\x12?\n" +
	"\x1cexpected_discharge_date_time\x18\t \x01(\tR\x19expectedDischargeDateTime\x12E\n" +
	"\x1festimated_length_inpatient_stay\x18\n" +
	" \x01(\tR\x1cestimatedLengthInpatientStay\x12?\n" +
	"\x1cactual_length_inpatient_stay\x18\v \x01(\tR\x19actualLengthInpatientStay\x12+\n" +
	"\x11visit_description\x18\f \x01(\tR\x10visitDescription\x12D\n" +
	"\x14referral_source_code\x18\r \x01(\v2\x12.standards.v23.XCNR\x12referralSourceCode\x122\n" +
	"\x15previous_service_date\x18\x0e \x01(\tR\x13previousServiceDate\x12O\n" +
	"$employment_illness_related_indicator\x18\x0f \x01(\tR!employmentIllnessRelatedIndicator\x12*\n" +
	"\x11purge_status_code\x18\x10 \x01(\tR\x0fpurgeStatusCode\x12*\n" +
	"\x11purge_status_date\x18\x11 \x01(\tR\x0fpurgeStatusDate\x120\n" +
	"\x14special_program_code\x18\x12 \x01(\tR\x12specialProgramCode\x12/\n" +
	"\x13retention_indicator\x18\x13 \x01(\tR\x12retentionIndicator\x12C\n" +
	"\x1eexpected_count_insurance_plans\x18\x14 \x01(\tR\x1bexpectedCountInsurancePlans\x120\n" +
	"\x14visit_publicity_code\x18\x15 \x01(\tR\x12visitPublicityCode\x12<\n" +
	"\x1avisit_protection_indicator\x18\x16 \x01(\tR\x18visitProtectionIndicator\x12L\n" +
	"\x18clinic_organization_name\x18\x17 \x01(\v2\x12.standards.v23.XONR\x16clinicOrganizationName\x12.\n" +
	"\x13patient_status_code\x18\x18 \x01(\tR\x11patientStatusCode\x12.\n" +
	"\x13visit_priority_code\x18\x19 \x01(\tR\x11visitPriorityCode\x126\n" +
	"\x17previous_treatment_date\x18\x1a \x01(\tR\x15previousTreatmentDate\x12D\n" +
	"\x1eexpected_discharge_disposition\x18\x1b \x01(\tR\x1cexpectedDischargeDisposition\x12.\n" +
	"\x13file_signature_date\x18\x1c \x01(\tR\x11fileSignatureDate\x12;\n" +
	"\x1afirst_similar_illness_date\x18\x1d \x01(\tR\x17firstSimilarIllnessDate\x12C\n" +
	"\x1epatient_charge_adjustment_code\x18\x1e \x01(\tR\x1bpatientChargeAdjustmentCode\x124\n" +
	"\x16recurring_service_code\x18\x1f \x01(\tR\x14recurringServiceCode\x12,\n" +
	"\x12billing_media_code\x18  \x01(\tR\x10billingMediaCode\x12;\n" +
	"\x1aexpected_surgery_date_time\x18! \x01(\tR\x17expectedSurgeryDateTime\x12:\n" +
	"\x19military_partnership_code\x18\" \x01(\tR\x17militaryPartnershipCode\x12C\n" +
	"\x1emilitary_non_availability_code\x18# \x01(\tR\x1bmilitaryNonAvailabilityCode\x124\n" +
	"\x16newborn_baby_indicator\x18$ \x01(\tR\x14newbornBabyIndicator\x126\n" +
	"\x17baby_detained_indicator\x18% \x01(\tR\x15babyDetainedIndicatorB1Z/github.com/s-hammon/hl7/proto/standards/v23;v23b\x06proto3"

var (
	file_standards_v23_administration_proto_rawDescOnce sync.Once
	file_standards_v23_administration_proto_rawDescData []byte
)

func file_standards_v23_administration_proto_rawDescGZIP() []byte {
	file_standards_v23_administration_proto_rawDescOnce.Do(func() {
		file_standards_v23_administration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_v23_administration_proto_rawDesc), len(file_standards_v23_administration_proto_rawDesc)))
	})
	return file_standards_v23_administration_proto_rawDescData
}

var file_standards_v23_administration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_standards_v23_administration_proto_goTypes = []any{
	(*EVN)(nil),   // 0: standards.v23.EVN
	(*PID)(nil),   // 1: standards.v23.PID
	(*PD1)(nil),   // 2: standards.v23.PD1
	(*AL1)(nil),   // 3: standards.v23.AL1
	(*PV1)(nil),   // 4: standards.v23.PV1
	(*PV2)(nil),   // 5: standards.v23.PV2
	(*XCN)(nil),   // 6: standards.v23.XCN
	(*CX)(nil),    // 7: standards.v23.CX
	(*XPN)(nil),   // 8: standards.v23.XPN
	(*XAD)(nil),   // 9: standards.v23.XAD
	(*XTN)(nil),   // 10: standards.v23.XTN
	(*CE)(nil),    // 11: standards.v23.CE
	(*DLN)(nil),   // 12: standards.v23.DLN
	(*XON)(nil),   // 13: standards.v23.XON
	(*PL)(nil),    // 14: standards.v23.PL
	(*FC)(nil),    // 15: standards.v23.FC
	(*CMDSL)(nil), // 16: standards.v23.CMDSL
}
var file_standards_v23_administration_proto_depIdxs = []int32{
	6,  // 0: standards.v23.EVN.operator_id:type_name -> standards.v23.XCN
	7,  // 1: standards.v23.PID.external_patient_id:type_name -> standards.v23.CX
	7,  // 2: standards.v23.PID.internal_patient_id:type_name -> standards.v23.CX
	7,  // 3: standards.v23.PID.alternate_patient_id:type_name -> standards.v23.CX
	8,  // 4: standards.v23.PID.patient_name:type_name -> standards.v23.XPN
	8,  // 5: standards.v23.PID.mother_maiden_name:type_name -> standards.v23.XPN
	8,  // 6: standards.v23.PID.patient_alias:type_name -> standards.v23.XPN
	9,  // 7: standards.v23.PID.patient_address:type_name -> standards.v23.XAD
	10, // 8: standards.v23.PID.home_phone_number:type_name -> standards.v23.XTN
	10, // 9: standards.v23.PID.work_phone_number:type_name -> standards.v23.XTN
	11, // 10: standards.v23.PID.primary_language:type_name -> standards.v23.CE
	7,  // 11: standards.v23.PID.patient_account_number:type_name -> standards.v23.CX
	12, // 12: standards.v23.PID.drivers_license_number:type_name -> standards.v23.DLN
	7,  // 13: standards.v23.PID.mother_identifier:type_name -> standards.v23.CX
	11, // 14: standards.v23.PID.veteran_status:type_name -> standards.v23.CE
	11, // 15: standards.v23.PID.nationality:type_name -> standards.v23.CE
	13, // 16: standards.v23.PD1.patient_primary_facility:type_name -> standards.v23.XON
	6,  // 17: standards.v23.PD1.patient_pcp_name:type_name -> standards.v23.XCN
	7,  // 18: standards.v23.PD1.duplicate_patient:type_name -> standards.v23.CX
	11, // 19: standards.v23.PD1.publicity_indicator:type_name -> standards.v23.CE
	11, // 20: standards.v23.AL1.allergy_code:type_name -> standards.v23.CE
	14, // 21: standards.v23.PV1.assigned_patient_location:type_name -> standards.v23.PL
	7,  // 22: standards.v23.PV1.preadmit_number:type_name -> standards.v23.CX
	14, // 23: standards.v23.PV1.prior_patient_location:type_name -> standards.v23.PL
	6,  // 24: standards.v23.PV1.attending_doctor:type_name -> standards.v23.XCN
	6,  // 25: standards.v23.PV1.referring_doctor:type_name -> standards.v23.XCN
	6,  // 26: standards.v23.PV1.consulting_doctor:type_name -> standards.v23.XCN
	14, // 27: standards.v23.PV1.temporary_location:type_name -> standards.v23.PL
	6,  // 28: standards.v23.PV1.admitting_doctor:type_name -> standards.v23.XCN
	7,  // 29: standards.v23.PV1.visit_number:type_name -> standards.v23.CX
	15, // 30: standards.v23.PV1.financial_class:type_name -> standards.v23.FC
	16, // 31: standards.v23.PV1.discharged_to_location:type_name -> standards.v23.CMDSL
	14, // 32: standards.v23.PV1.pending_location:type_name -> standards.v23.PL
	14, // 33: standards.v23.PV1.prior_temporary_location:type_name -> standards.v23.PL
	7,  // 34: standards.v23.PV1.alternate_visit_id:type_name -> standards.v23.CX
	6,  // 35: standards.v23.PV1.other_healthcare_provider:type_name -> standards.v23.XCN
	14, // 36: standards.v23.PV2.prior_pending_location:type_name -> standards.v23.PL
	11, // 37: standards.v23.PV2.accomodation_code:type_name -> standards.v23.CE
	11, // 38: standards.v23.PV2.admit_reason:type_name -> standards.v23.CE
	11, // 39: standards.v23.PV2.transfer_reason:type_name -> standards.v23.CE
	6,  // 40: standards.v23.PV2.referral_source_code:type_name -> standards.v23.XCN
	13, // 41: standards.v23.PV2.clinic_organization_name:type_name -> standards.v23.XON
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_standards_v23_administration_proto_init() }
func file_standards_v23_administration_proto_init() {
	if File_standards_v23_administration_proto != nil {
		return
	}
	file_standards_v23_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_v23_administration_proto_rawDesc), len(file_standards_v23_administration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_v23_administration_proto_goTypes,
		DependencyIndexes: file_standards_v23_administration_proto_depIdxs,
		MessageInfos:      file_standards_v23_administration_proto_msgTypes,
	}.Build()
	File_standards_v23_administration_proto = out.File
	file_standards_v23_administration_proto_goTypes = nil
	file_standards_v23_administration_proto_depIdxs = nil
}
