// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: standards/v23/control.proto

package v23

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MSH struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	FieldDelimiter            string                 `protobuf:"bytes,1,opt,name=field_delimiter,json=fieldDelimiter,proto3" json:"field_delimiter,omitempty"`
	EncodingCharacters        string                 `protobuf:"bytes,2,opt,name=encoding_characters,json=encodingCharacters,proto3" json:"encoding_characters,omitempty"`
	SendingApplication        string                 `protobuf:"bytes,3,opt,name=sending_application,json=sendingApplication,proto3" json:"sending_application,omitempty"`
	SendingFacility           string                 `protobuf:"bytes,4,opt,name=sending_facility,json=sendingFacility,proto3" json:"sending_facility,omitempty"`
	ReceivingApplication      string                 `protobuf:"bytes,5,opt,name=receiving_application,json=receivingApplication,proto3" json:"receiving_application,omitempty"`
	ReceivingFacility         string                 `protobuf:"bytes,6,opt,name=receiving_facility,json=receivingFacility,proto3" json:"receiving_facility,omitempty"`
	DateTime                  string                 `protobuf:"bytes,7,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Security                  string                 `protobuf:"bytes,8,opt,name=security,proto3" json:"security,omitempty"`
	MessageType               *CMMSG                 `protobuf:"bytes,9,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ControlId                 string                 `protobuf:"bytes,10,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	ProcessingId              string                 `protobuf:"bytes,11,opt,name=processing_id,json=processingId,proto3" json:"processing_id,omitempty"`
	VersionId                 string                 `protobuf:"bytes,12,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	SequenceNumber            string                 `protobuf:"bytes,13,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	ContinuationPointer       string                 `protobuf:"bytes,14,opt,name=continuation_pointer,json=continuationPointer,proto3" json:"continuation_pointer,omitempty"`
	AcceptAcknowledgementType string                 `protobuf:"bytes,15,opt,name=accept_acknowledgement_type,json=acceptAcknowledgementType,proto3" json:"accept_acknowledgement_type,omitempty"`
	CountryCode               string                 `protobuf:"bytes,16,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CharacterSet              string                 `protobuf:"bytes,17,opt,name=character_set,json=characterSet,proto3" json:"character_set,omitempty"`
	PrincipalLanguage         string                 `protobuf:"bytes,18,opt,name=principal_language,json=principalLanguage,proto3" json:"principal_language,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MSH) Reset() {
	*x = MSH{}
	mi := &file_standards_v23_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSH) ProtoMessage() {}

func (x *MSH) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSH.ProtoReflect.Descriptor instead.
func (*MSH) Descriptor() ([]byte, []int) {
	return file_standards_v23_control_proto_rawDescGZIP(), []int{0}
}

func (x *MSH) GetFieldDelimiter() string {
	if x != nil {
		return x.FieldDelimiter
	}
	return ""
}

func (x *MSH) GetEncodingCharacters() string {
	if x != nil {
		return x.EncodingCharacters
	}
	return ""
}

func (x *MSH) GetSendingApplication() string {
	if x != nil {
		return x.SendingApplication
	}
	return ""
}

func (x *MSH) GetSendingFacility() string {
	if x != nil {
		return x.SendingFacility
	}
	return ""
}

func (x *MSH) GetReceivingApplication() string {
	if x != nil {
		return x.ReceivingApplication
	}
	return ""
}

func (x *MSH) GetReceivingFacility() string {
	if x != nil {
		return x.ReceivingFacility
	}
	return ""
}

func (x *MSH) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

func (x *MSH) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *MSH) GetMessageType() *CMMSG {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *MSH) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *MSH) GetProcessingId() string {
	if x != nil {
		return x.ProcessingId
	}
	return ""
}

func (x *MSH) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *MSH) GetSequenceNumber() string {
	if x != nil {
		return x.SequenceNumber
	}
	return ""
}

func (x *MSH) GetContinuationPointer() string {
	if x != nil {
		return x.ContinuationPointer
	}
	return ""
}

func (x *MSH) GetAcceptAcknowledgementType() string {
	if x != nil {
		return x.AcceptAcknowledgementType
	}
	return ""
}

func (x *MSH) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *MSH) GetCharacterSet() string {
	if x != nil {
		return x.CharacterSet
	}
	return ""
}

func (x *MSH) GetPrincipalLanguage() string {
	if x != nil {
		return x.PrincipalLanguage
	}
	return ""
}

type NTE struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SetId           string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	SourceOfComment string                 `protobuf:"bytes,2,opt,name=source_of_comment,json=sourceOfComment,proto3" json:"source_of_comment,omitempty"`
	Comment         string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NTE) Reset() {
	*x = NTE{}
	mi := &file_standards_v23_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NTE) ProtoMessage() {}

func (x *NTE) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NTE.ProtoReflect.Descriptor instead.
func (*NTE) Descriptor() ([]byte, []int) {
	return file_standards_v23_control_proto_rawDescGZIP(), []int{1}
}

func (x *NTE) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *NTE) GetSourceOfComment() string {
	if x != nil {
		return x.SourceOfComment
	}
	return ""
}

func (x *NTE) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type DSC struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ContinuationPointer string                 `protobuf:"bytes,1,opt,name=continuation_pointer,json=continuationPointer,proto3" json:"continuation_pointer,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DSC) Reset() {
	*x = DSC{}
	mi := &file_standards_v23_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DSC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSC) ProtoMessage() {}

func (x *DSC) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSC.ProtoReflect.Descriptor instead.
func (*DSC) Descriptor() ([]byte, []int) {
	return file_standards_v23_control_proto_rawDescGZIP(), []int{2}
}

func (x *DSC) GetContinuationPointer() string {
	if x != nil {
		return x.ContinuationPointer
	}
	return ""
}

var File_standards_v23_control_proto protoreflect.FileDescriptor

const file_standards_v23_control_proto_rawDesc = "" +
	"\n" +
	"\x1bstandards/v23/control.proto\x12\rstandards.v23\x1a\x19standards/v23/types.proto\"\x87\x06\n" +
	"\x03MSH\x12'\n" +
	"\x0ffield_delimiter\x18\x01 \x01(\tR\x0efieldDelimiter\x12/\n" +
	"\x13encoding_characters\x18\x02 \x01(\tR\x12encodingCharacters\x12/\n" +
	"\x13sending_application\x18\x03 \x01(\tR\x12sendingApplication\x12)\n" +
	"\x10sending_facility\x18\x04 \x01(\tR\x0fsendingFacility\x123\n" +
	"\x15receiving_application\x18\x05 \x01(\tR\x14receivingApplication\x12-\n" +
	"\x12receiving_facility\x18\x06 \x01(\tR\x11receivingFacility\x12\x1b\n" +
	"\tdate_time\x18\a \x01(\tR\bdateTime\x12\x1a\n" +
	"\bsecurity\x18\b \x01(\tR\bsecurity\x127\n" +
	"\fmessage_type\x18\t \x01(\v2\x14.standards.v23.CMMSGR\vmessageType\x12\x1d\n" +
	"\n" +
	"control_id\x18\n" +
	" \x01(\tR\tcontrolId\x12#\n" +
	"\rprocessing_id\x18\v \x01(\tR\fprocessingId\x12\x1d\n" +
	"\n" +
	"version_id\x18\f \x01(\tR\tversionId\x12'\n" +
	"\x0fsequence_number\x18\r \x01(\tR\x0esequenceNumber\x121\n" +
	"\x14continuation_pointer\x18\x0e \x01(\tR\x13continuationPointer\x12>\n" +
	"\x1baccept_acknowledgement_type\x18\x0f \x01(\tR\x19acceptAcknowledgementType\x12!\n" +
	"\fcountry_code\x18\x10 \x01(\tR\vcountryCode\x12#\n" +
	"\rcharacter_set\x18\x11 \x01(\tR\fcharacterSet\x12-\n" +
	"\x12principal_language\x18\x12 \x01(\tR\x11principalLanguage\"b\n" +
	"\x03NTE\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12*\n" +
	"\x11source_of_comment\x18\x02 \x01(\tR\x0fsourceOfComment\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"8\n" +
	"\x03DSC\x121\n" +
	"\x14continuation_pointer\x18\x01 \x01(\tR\x13continuationPointerB1Z/github.com/s-hammon/hl7/proto/standards/v23;v23b\x06proto3"

var (
	file_standards_v23_control_proto_rawDescOnce sync.Once
	file_standards_v23_control_proto_rawDescData []byte
)

func file_standards_v23_control_proto_rawDescGZIP() []byte {
	file_standards_v23_control_proto_rawDescOnce.Do(func() {
		file_standards_v23_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_v23_control_proto_rawDesc), len(file_standards_v23_control_proto_rawDesc)))
	})
	return file_standards_v23_control_proto_rawDescData
}

var file_standards_v23_control_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_standards_v23_control_proto_goTypes = []any{
	(*MSH)(nil),   // 0: standards.v23.MSH
	(*NTE)(nil),   // 1: standards.v23.NTE
	(*DSC)(nil),   // 2: standards.v23.DSC
	(*CMMSG)(nil), // 3: standards.v23.CMMSG
}
var file_standards_v23_control_proto_depIdxs = []int32{
	3, // 0: standards.v23.MSH.message_type:type_name -> standards.v23.CMMSG
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_standards_v23_control_proto_init() }
func file_standards_v23_control_proto_init() {
	if File_standards_v23_control_proto != nil {
		return
	}
	file_standards_v23_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_v23_control_proto_rawDesc), len(file_standards_v23_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_v23_control_proto_goTypes,
		DependencyIndexes: file_standards_v23_control_proto_depIdxs,
		MessageInfos:      file_standards_v23_control_proto_msgTypes,
	}.Build()
	File_standards_v23_control_proto = out.File
	file_standards_v23_control_proto_goTypes = nil
	file_standards_v23_control_proto_depIdxs = nil
}
