// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: standards/v23/financial.proto

package v23

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GT1 struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SetId                    string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	GuarantorNumber          *CX                    `protobuf:"bytes,2,opt,name=guarantor_number,json=guarantorNumber,proto3" json:"guarantor_number,omitempty"`
	Name                     *XPN                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SpouseName               *XPN                   `protobuf:"bytes,4,opt,name=spouse_name,json=spouseName,proto3" json:"spouse_name,omitempty"`
	Address                  *XAD                   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	HomePhoneNumber          *XTN                   `protobuf:"bytes,6,opt,name=home_phone_number,json=homePhoneNumber,proto3" json:"home_phone_number,omitempty"`
	WorkPhoneNumber          *XTN                   `protobuf:"bytes,7,opt,name=work_phone_number,json=workPhoneNumber,proto3" json:"work_phone_number,omitempty"`
	Dob                      string                 `protobuf:"bytes,8,opt,name=dob,proto3" json:"dob,omitempty"`
	Sex                      string                 `protobuf:"bytes,9,opt,name=sex,proto3" json:"sex,omitempty"`
	Type                     string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	RelationshipToPatient    string                 `protobuf:"bytes,11,opt,name=relationship_to_patient,json=relationshipToPatient,proto3" json:"relationship_to_patient,omitempty"`
	Ssn                      string                 `protobuf:"bytes,12,opt,name=ssn,proto3" json:"ssn,omitempty"`
	BeginDate                string                 `protobuf:"bytes,13,opt,name=begin_date,json=beginDate,proto3" json:"begin_date,omitempty"`
	EndDate                  string                 `protobuf:"bytes,14,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Priority                 string                 `protobuf:"bytes,15,opt,name=priority,proto3" json:"priority,omitempty"`
	EmployerName             *XPN                   `protobuf:"bytes,16,opt,name=employer_name,json=employerName,proto3" json:"employer_name,omitempty"`
	EmployerAddress          *XAD                   `protobuf:"bytes,17,opt,name=employer_address,json=employerAddress,proto3" json:"employer_address,omitempty"`
	EmployerPhoneNumber      *XTN                   `protobuf:"bytes,18,opt,name=employer_phone_number,json=employerPhoneNumber,proto3" json:"employer_phone_number,omitempty"`
	EmployeeIdNumber         *CX                    `protobuf:"bytes,19,opt,name=employee_id_number,json=employeeIdNumber,proto3" json:"employee_id_number,omitempty"`
	EmploymentStatus         string                 `protobuf:"bytes,20,opt,name=employment_status,json=employmentStatus,proto3" json:"employment_status,omitempty"`
	OrganizationName         *XON                   `protobuf:"bytes,21,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	BillingHoldFlag          string                 `protobuf:"bytes,22,opt,name=billing_hold_flag,json=billingHoldFlag,proto3" json:"billing_hold_flag,omitempty"`
	CreditRatingCode         *CE                    `protobuf:"bytes,23,opt,name=credit_rating_code,json=creditRatingCode,proto3" json:"credit_rating_code,omitempty"`
	DeathDateTime            string                 `protobuf:"bytes,24,opt,name=death_date_time,json=deathDateTime,proto3" json:"death_date_time,omitempty"`
	DeathFlag                string                 `protobuf:"bytes,25,opt,name=death_flag,json=deathFlag,proto3" json:"death_flag,omitempty"`
	ChargeAdjustmentCode     *CE                    `protobuf:"bytes,26,opt,name=charge_adjustment_code,json=chargeAdjustmentCode,proto3" json:"charge_adjustment_code,omitempty"`
	HouseholdAnnualIncome    *CP                    `protobuf:"bytes,27,opt,name=household_annual_income,json=householdAnnualIncome,proto3" json:"household_annual_income,omitempty"`
	HouseholdSize            string                 `protobuf:"bytes,28,opt,name=household_size,json=householdSize,proto3" json:"household_size,omitempty"`
	EmployerIdNumber         *CX                    `protobuf:"bytes,29,opt,name=employer_id_number,json=employerIdNumber,proto3" json:"employer_id_number,omitempty"`
	MaritalStatus            string                 `protobuf:"bytes,30,opt,name=marital_status,json=maritalStatus,proto3" json:"marital_status,omitempty"`
	HireEffectiveDate        string                 `protobuf:"bytes,31,opt,name=hire_effective_date,json=hireEffectiveDate,proto3" json:"hire_effective_date,omitempty"`
	EmploymentStopDate       string                 `protobuf:"bytes,32,opt,name=employment_stop_date,json=employmentStopDate,proto3" json:"employment_stop_date,omitempty"`
	LivingDependency         string                 `protobuf:"bytes,33,opt,name=living_dependency,json=livingDependency,proto3" json:"living_dependency,omitempty"`
	AmbulatoryStatus         string                 `protobuf:"bytes,34,opt,name=ambulatory_status,json=ambulatoryStatus,proto3" json:"ambulatory_status,omitempty"`
	Citizenship              string                 `protobuf:"bytes,35,opt,name=citizenship,proto3" json:"citizenship,omitempty"`
	PrimaryLanguage          *CE                    `protobuf:"bytes,36,opt,name=primary_language,json=primaryLanguage,proto3" json:"primary_language,omitempty"`
	LivingArrangement        string                 `protobuf:"bytes,37,opt,name=living_arrangement,json=livingArrangement,proto3" json:"living_arrangement,omitempty"`
	PublicityIndicator       *CE                    `protobuf:"bytes,38,opt,name=publicity_indicator,json=publicityIndicator,proto3" json:"publicity_indicator,omitempty"`
	ProtectionIndicator      string                 `protobuf:"bytes,39,opt,name=protection_indicator,json=protectionIndicator,proto3" json:"protection_indicator,omitempty"`
	StudentIndicator         string                 `protobuf:"bytes,40,opt,name=student_indicator,json=studentIndicator,proto3" json:"student_indicator,omitempty"`
	Religion                 string                 `protobuf:"bytes,41,opt,name=religion,proto3" json:"religion,omitempty"`
	MotherMaidenName         *XPN                   `protobuf:"bytes,42,opt,name=mother_maiden_name,json=motherMaidenName,proto3" json:"mother_maiden_name,omitempty"`
	Nationality              *CE                    `protobuf:"bytes,43,opt,name=nationality,proto3" json:"nationality,omitempty"`
	EthnicGroup              string                 `protobuf:"bytes,44,opt,name=ethnic_group,json=ethnicGroup,proto3" json:"ethnic_group,omitempty"`
	ContactName              *XPN                   `protobuf:"bytes,45,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhoneNumber       *XTN                   `protobuf:"bytes,46,opt,name=contact_phone_number,json=contactPhoneNumber,proto3" json:"contact_phone_number,omitempty"`
	ContactReason            *CE                    `protobuf:"bytes,47,opt,name=contact_reason,json=contactReason,proto3" json:"contact_reason,omitempty"`
	ContactRelationship      string                 `protobuf:"bytes,48,opt,name=contact_relationship,json=contactRelationship,proto3" json:"contact_relationship,omitempty"`
	JobTitle                 string                 `protobuf:"bytes,49,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	JobCode                  *JCC                   `protobuf:"bytes,50,opt,name=job_code,json=jobCode,proto3" json:"job_code,omitempty"`
	EmployerOrganizationName *XON                   `protobuf:"bytes,51,opt,name=employer_organization_name,json=employerOrganizationName,proto3" json:"employer_organization_name,omitempty"`
	Handicap                 string                 `protobuf:"bytes,52,opt,name=handicap,proto3" json:"handicap,omitempty"`
	JobStatus                string                 `protobuf:"bytes,53,opt,name=job_status,json=jobStatus,proto3" json:"job_status,omitempty"`
	FinancialClass           *FC                    `protobuf:"bytes,54,opt,name=financial_class,json=financialClass,proto3" json:"financial_class,omitempty"`
	Race                     string                 `protobuf:"bytes,55,opt,name=race,proto3" json:"race,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GT1) Reset() {
	*x = GT1{}
	mi := &file_standards_v23_financial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GT1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GT1) ProtoMessage() {}

func (x *GT1) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_financial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GT1.ProtoReflect.Descriptor instead.
func (*GT1) Descriptor() ([]byte, []int) {
	return file_standards_v23_financial_proto_rawDescGZIP(), []int{0}
}

func (x *GT1) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *GT1) GetGuarantorNumber() *CX {
	if x != nil {
		return x.GuarantorNumber
	}
	return nil
}

func (x *GT1) GetName() *XPN {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *GT1) GetSpouseName() *XPN {
	if x != nil {
		return x.SpouseName
	}
	return nil
}

func (x *GT1) GetAddress() *XAD {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GT1) GetHomePhoneNumber() *XTN {
	if x != nil {
		return x.HomePhoneNumber
	}
	return nil
}

func (x *GT1) GetWorkPhoneNumber() *XTN {
	if x != nil {
		return x.WorkPhoneNumber
	}
	return nil
}

func (x *GT1) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *GT1) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *GT1) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GT1) GetRelationshipToPatient() string {
	if x != nil {
		return x.RelationshipToPatient
	}
	return ""
}

func (x *GT1) GetSsn() string {
	if x != nil {
		return x.Ssn
	}
	return ""
}

func (x *GT1) GetBeginDate() string {
	if x != nil {
		return x.BeginDate
	}
	return ""
}

func (x *GT1) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GT1) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *GT1) GetEmployerName() *XPN {
	if x != nil {
		return x.EmployerName
	}
	return nil
}

func (x *GT1) GetEmployerAddress() *XAD {
	if x != nil {
		return x.EmployerAddress
	}
	return nil
}

func (x *GT1) GetEmployerPhoneNumber() *XTN {
	if x != nil {
		return x.EmployerPhoneNumber
	}
	return nil
}

func (x *GT1) GetEmployeeIdNumber() *CX {
	if x != nil {
		return x.EmployeeIdNumber
	}
	return nil
}

func (x *GT1) GetEmploymentStatus() string {
	if x != nil {
		return x.EmploymentStatus
	}
	return ""
}

func (x *GT1) GetOrganizationName() *XON {
	if x != nil {
		return x.OrganizationName
	}
	return nil
}

func (x *GT1) GetBillingHoldFlag() string {
	if x != nil {
		return x.BillingHoldFlag
	}
	return ""
}

func (x *GT1) GetCreditRatingCode() *CE {
	if x != nil {
		return x.CreditRatingCode
	}
	return nil
}

func (x *GT1) GetDeathDateTime() string {
	if x != nil {
		return x.DeathDateTime
	}
	return ""
}

func (x *GT1) GetDeathFlag() string {
	if x != nil {
		return x.DeathFlag
	}
	return ""
}

func (x *GT1) GetChargeAdjustmentCode() *CE {
	if x != nil {
		return x.ChargeAdjustmentCode
	}
	return nil
}

func (x *GT1) GetHouseholdAnnualIncome() *CP {
	if x != nil {
		return x.HouseholdAnnualIncome
	}
	return nil
}

func (x *GT1) GetHouseholdSize() string {
	if x != nil {
		return x.HouseholdSize
	}
	return ""
}

func (x *GT1) GetEmployerIdNumber() *CX {
	if x != nil {
		return x.EmployerIdNumber
	}
	return nil
}

func (x *GT1) GetMaritalStatus() string {
	if x != nil {
		return x.MaritalStatus
	}
	return ""
}

func (x *GT1) GetHireEffectiveDate() string {
	if x != nil {
		return x.HireEffectiveDate
	}
	return ""
}

func (x *GT1) GetEmploymentStopDate() string {
	if x != nil {
		return x.EmploymentStopDate
	}
	return ""
}

func (x *GT1) GetLivingDependency() string {
	if x != nil {
		return x.LivingDependency
	}
	return ""
}

func (x *GT1) GetAmbulatoryStatus() string {
	if x != nil {
		return x.AmbulatoryStatus
	}
	return ""
}

func (x *GT1) GetCitizenship() string {
	if x != nil {
		return x.Citizenship
	}
	return ""
}

func (x *GT1) GetPrimaryLanguage() *CE {
	if x != nil {
		return x.PrimaryLanguage
	}
	return nil
}

func (x *GT1) GetLivingArrangement() string {
	if x != nil {
		return x.LivingArrangement
	}
	return ""
}

func (x *GT1) GetPublicityIndicator() *CE {
	if x != nil {
		return x.PublicityIndicator
	}
	return nil
}

func (x *GT1) GetProtectionIndicator() string {
	if x != nil {
		return x.ProtectionIndicator
	}
	return ""
}

func (x *GT1) GetStudentIndicator() string {
	if x != nil {
		return x.StudentIndicator
	}
	return ""
}

func (x *GT1) GetReligion() string {
	if x != nil {
		return x.Religion
	}
	return ""
}

func (x *GT1) GetMotherMaidenName() *XPN {
	if x != nil {
		return x.MotherMaidenName
	}
	return nil
}

func (x *GT1) GetNationality() *CE {
	if x != nil {
		return x.Nationality
	}
	return nil
}

func (x *GT1) GetEthnicGroup() string {
	if x != nil {
		return x.EthnicGroup
	}
	return ""
}

func (x *GT1) GetContactName() *XPN {
	if x != nil {
		return x.ContactName
	}
	return nil
}

func (x *GT1) GetContactPhoneNumber() *XTN {
	if x != nil {
		return x.ContactPhoneNumber
	}
	return nil
}

func (x *GT1) GetContactReason() *CE {
	if x != nil {
		return x.ContactReason
	}
	return nil
}

func (x *GT1) GetContactRelationship() string {
	if x != nil {
		return x.ContactRelationship
	}
	return ""
}

func (x *GT1) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *GT1) GetJobCode() *JCC {
	if x != nil {
		return x.JobCode
	}
	return nil
}

func (x *GT1) GetEmployerOrganizationName() *XON {
	if x != nil {
		return x.EmployerOrganizationName
	}
	return nil
}

func (x *GT1) GetHandicap() string {
	if x != nil {
		return x.Handicap
	}
	return ""
}

func (x *GT1) GetJobStatus() string {
	if x != nil {
		return x.JobStatus
	}
	return ""
}

func (x *GT1) GetFinancialClass() *FC {
	if x != nil {
		return x.FinancialClass
	}
	return nil
}

func (x *GT1) GetRace() string {
	if x != nil {
		return x.Race
	}
	return ""
}

type IN1 struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SetId                    string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	PlanId                   *CE                    `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	CompanyId                *CX                    `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	CompanyName              *XON                   `protobuf:"bytes,4,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CompanyAddress           *XAD                   `protobuf:"bytes,5,opt,name=company_address,json=companyAddress,proto3" json:"company_address,omitempty"`
	CompanyContact           *XPN                   `protobuf:"bytes,6,opt,name=company_contact,json=companyContact,proto3" json:"company_contact,omitempty"`
	CompanyPhoneNumber       *XTN                   `protobuf:"bytes,7,opt,name=company_phone_number,json=companyPhoneNumber,proto3" json:"company_phone_number,omitempty"`
	GroupNumber              string                 `protobuf:"bytes,8,opt,name=group_number,json=groupNumber,proto3" json:"group_number,omitempty"`
	GroupName                *XON                   `protobuf:"bytes,9,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupEmployerId          *CX                    `protobuf:"bytes,10,opt,name=group_employer_id,json=groupEmployerId,proto3" json:"group_employer_id,omitempty"`
	GroupEmployerName        *XON                   `protobuf:"bytes,11,opt,name=group_employer_name,json=groupEmployerName,proto3" json:"group_employer_name,omitempty"`
	PlanEffectiveDate        string                 `protobuf:"bytes,12,opt,name=plan_effective_date,json=planEffectiveDate,proto3" json:"plan_effective_date,omitempty"`
	PlanExpirationDate       string                 `protobuf:"bytes,13,opt,name=plan_expiration_date,json=planExpirationDate,proto3" json:"plan_expiration_date,omitempty"`
	AuthorizationInformation *CMAUI                 `protobuf:"bytes,14,opt,name=authorization_information,json=authorizationInformation,proto3" json:"authorization_information,omitempty"`
	PlanType                 string                 `protobuf:"bytes,15,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	InsuredName              *XPN                   `protobuf:"bytes,16,opt,name=insured_name,json=insuredName,proto3" json:"insured_name,omitempty"`
	RelationshipToPatient    string                 `protobuf:"bytes,17,opt,name=relationship_to_patient,json=relationshipToPatient,proto3" json:"relationship_to_patient,omitempty"`
	InsuredDob               string                 `protobuf:"bytes,18,opt,name=insured_dob,json=insuredDob,proto3" json:"insured_dob,omitempty"`
	InsuredAddress           *XAD                   `protobuf:"bytes,19,opt,name=insured_address,json=insuredAddress,proto3" json:"insured_address,omitempty"`
	Aob                      string                 `protobuf:"bytes,20,opt,name=aob,proto3" json:"aob,omitempty"`
	Cob                      string                 `protobuf:"bytes,21,opt,name=cob,proto3" json:"cob,omitempty"`
	CobPriority              string                 `protobuf:"bytes,22,opt,name=cob_priority,json=cobPriority,proto3" json:"cob_priority,omitempty"`
	AdmissionFlag            string                 `protobuf:"bytes,23,opt,name=admission_flag,json=admissionFlag,proto3" json:"admission_flag,omitempty"`
	AdmissionDate            string                 `protobuf:"bytes,24,opt,name=admission_date,json=admissionDate,proto3" json:"admission_date,omitempty"`
	EligibilityFlag          string                 `protobuf:"bytes,25,opt,name=eligibility_flag,json=eligibilityFlag,proto3" json:"eligibility_flag,omitempty"`
	EligibilityDate          string                 `protobuf:"bytes,26,opt,name=eligibility_date,json=eligibilityDate,proto3" json:"eligibility_date,omitempty"`
	ReleaseInformationCode   string                 `protobuf:"bytes,27,opt,name=release_information_code,json=releaseInformationCode,proto3" json:"release_information_code,omitempty"`
	Pac                      string                 `protobuf:"bytes,28,opt,name=pac,proto3" json:"pac,omitempty"`
	VerificationDateTime     string                 `protobuf:"bytes,29,opt,name=verification_date_time,json=verificationDateTime,proto3" json:"verification_date_time,omitempty"`
	VerificationBy           *XCN                   `protobuf:"bytes,30,opt,name=verification_by,json=verificationBy,proto3" json:"verification_by,omitempty"`
	AgreementCode            string                 `protobuf:"bytes,31,opt,name=agreement_code,json=agreementCode,proto3" json:"agreement_code,omitempty"`
	BillingStatus            string                 `protobuf:"bytes,32,opt,name=billing_status,json=billingStatus,proto3" json:"billing_status,omitempty"`
	LifetimeReserveDays      string                 `protobuf:"bytes,33,opt,name=lifetime_reserve_days,json=lifetimeReserveDays,proto3" json:"lifetime_reserve_days,omitempty"`
	DelayBeforeLrDay         string                 `protobuf:"bytes,34,opt,name=delay_before_lr_day,json=delayBeforeLrDay,proto3" json:"delay_before_lr_day,omitempty"`
	CompanyPlanCode          string                 `protobuf:"bytes,35,opt,name=company_plan_code,json=companyPlanCode,proto3" json:"company_plan_code,omitempty"`
	PolicyNumber             string                 `protobuf:"bytes,36,opt,name=policy_number,json=policyNumber,proto3" json:"policy_number,omitempty"`
	PolicyDeductible         *CP                    `protobuf:"bytes,37,opt,name=policy_deductible,json=policyDeductible,proto3" json:"policy_deductible,omitempty"`
	PolicyLimitAmount        *CP                    `protobuf:"bytes,38,opt,name=policy_limit_amount,json=policyLimitAmount,proto3" json:"policy_limit_amount,omitempty"`
	PolicyLimitDays          string                 `protobuf:"bytes,39,opt,name=policy_limit_days,json=policyLimitDays,proto3" json:"policy_limit_days,omitempty"`
	RoomRateSemiPrivate      *CP                    `protobuf:"bytes,40,opt,name=room_rate_semi_private,json=roomRateSemiPrivate,proto3" json:"room_rate_semi_private,omitempty"`
	RoomRatePrivate          *CP                    `protobuf:"bytes,41,opt,name=room_rate_private,json=roomRatePrivate,proto3" json:"room_rate_private,omitempty"`
	InsuredEmploymentStatus  *CE                    `protobuf:"bytes,42,opt,name=insured_employment_status,json=insuredEmploymentStatus,proto3" json:"insured_employment_status,omitempty"`
	InsuredSex               string                 `protobuf:"bytes,43,opt,name=insured_sex,json=insuredSex,proto3" json:"insured_sex,omitempty"`
	InsuredEmployerAddress   *XAD                   `protobuf:"bytes,44,opt,name=insured_employer_address,json=insuredEmployerAddress,proto3" json:"insured_employer_address,omitempty"`
	VerificationStatus       string                 `protobuf:"bytes,45,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"`
	PriorInsturancePlanId    string                 `protobuf:"bytes,46,opt,name=prior_insturance_plan_id,json=priorInsturancePlanId,proto3" json:"prior_insturance_plan_id,omitempty"`
	CoverageType             string                 `protobuf:"bytes,47,opt,name=coverage_type,json=coverageType,proto3" json:"coverage_type,omitempty"`
	Handicap                 string                 `protobuf:"bytes,48,opt,name=handicap,proto3" json:"handicap,omitempty"`
	InsuredIdNumber          *CX                    `protobuf:"bytes,49,opt,name=insured_id_number,json=insuredIdNumber,proto3" json:"insured_id_number,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *IN1) Reset() {
	*x = IN1{}
	mi := &file_standards_v23_financial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IN1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IN1) ProtoMessage() {}

func (x *IN1) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_financial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IN1.ProtoReflect.Descriptor instead.
func (*IN1) Descriptor() ([]byte, []int) {
	return file_standards_v23_financial_proto_rawDescGZIP(), []int{1}
}

func (x *IN1) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *IN1) GetPlanId() *CE {
	if x != nil {
		return x.PlanId
	}
	return nil
}

func (x *IN1) GetCompanyId() *CX {
	if x != nil {
		return x.CompanyId
	}
	return nil
}

func (x *IN1) GetCompanyName() *XON {
	if x != nil {
		return x.CompanyName
	}
	return nil
}

func (x *IN1) GetCompanyAddress() *XAD {
	if x != nil {
		return x.CompanyAddress
	}
	return nil
}

func (x *IN1) GetCompanyContact() *XPN {
	if x != nil {
		return x.CompanyContact
	}
	return nil
}

func (x *IN1) GetCompanyPhoneNumber() *XTN {
	if x != nil {
		return x.CompanyPhoneNumber
	}
	return nil
}

func (x *IN1) GetGroupNumber() string {
	if x != nil {
		return x.GroupNumber
	}
	return ""
}

func (x *IN1) GetGroupName() *XON {
	if x != nil {
		return x.GroupName
	}
	return nil
}

func (x *IN1) GetGroupEmployerId() *CX {
	if x != nil {
		return x.GroupEmployerId
	}
	return nil
}

func (x *IN1) GetGroupEmployerName() *XON {
	if x != nil {
		return x.GroupEmployerName
	}
	return nil
}

func (x *IN1) GetPlanEffectiveDate() string {
	if x != nil {
		return x.PlanEffectiveDate
	}
	return ""
}

func (x *IN1) GetPlanExpirationDate() string {
	if x != nil {
		return x.PlanExpirationDate
	}
	return ""
}

func (x *IN1) GetAuthorizationInformation() *CMAUI {
	if x != nil {
		return x.AuthorizationInformation
	}
	return nil
}

func (x *IN1) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

func (x *IN1) GetInsuredName() *XPN {
	if x != nil {
		return x.InsuredName
	}
	return nil
}

func (x *IN1) GetRelationshipToPatient() string {
	if x != nil {
		return x.RelationshipToPatient
	}
	return ""
}

func (x *IN1) GetInsuredDob() string {
	if x != nil {
		return x.InsuredDob
	}
	return ""
}

func (x *IN1) GetInsuredAddress() *XAD {
	if x != nil {
		return x.InsuredAddress
	}
	return nil
}

func (x *IN1) GetAob() string {
	if x != nil {
		return x.Aob
	}
	return ""
}

func (x *IN1) GetCob() string {
	if x != nil {
		return x.Cob
	}
	return ""
}

func (x *IN1) GetCobPriority() string {
	if x != nil {
		return x.CobPriority
	}
	return ""
}

func (x *IN1) GetAdmissionFlag() string {
	if x != nil {
		return x.AdmissionFlag
	}
	return ""
}

func (x *IN1) GetAdmissionDate() string {
	if x != nil {
		return x.AdmissionDate
	}
	return ""
}

func (x *IN1) GetEligibilityFlag() string {
	if x != nil {
		return x.EligibilityFlag
	}
	return ""
}

func (x *IN1) GetEligibilityDate() string {
	if x != nil {
		return x.EligibilityDate
	}
	return ""
}

func (x *IN1) GetReleaseInformationCode() string {
	if x != nil {
		return x.ReleaseInformationCode
	}
	return ""
}

func (x *IN1) GetPac() string {
	if x != nil {
		return x.Pac
	}
	return ""
}

func (x *IN1) GetVerificationDateTime() string {
	if x != nil {
		return x.VerificationDateTime
	}
	return ""
}

func (x *IN1) GetVerificationBy() *XCN {
	if x != nil {
		return x.VerificationBy
	}
	return nil
}

func (x *IN1) GetAgreementCode() string {
	if x != nil {
		return x.AgreementCode
	}
	return ""
}

func (x *IN1) GetBillingStatus() string {
	if x != nil {
		return x.BillingStatus
	}
	return ""
}

func (x *IN1) GetLifetimeReserveDays() string {
	if x != nil {
		return x.LifetimeReserveDays
	}
	return ""
}

func (x *IN1) GetDelayBeforeLrDay() string {
	if x != nil {
		return x.DelayBeforeLrDay
	}
	return ""
}

func (x *IN1) GetCompanyPlanCode() string {
	if x != nil {
		return x.CompanyPlanCode
	}
	return ""
}

func (x *IN1) GetPolicyNumber() string {
	if x != nil {
		return x.PolicyNumber
	}
	return ""
}

func (x *IN1) GetPolicyDeductible() *CP {
	if x != nil {
		return x.PolicyDeductible
	}
	return nil
}

func (x *IN1) GetPolicyLimitAmount() *CP {
	if x != nil {
		return x.PolicyLimitAmount
	}
	return nil
}

func (x *IN1) GetPolicyLimitDays() string {
	if x != nil {
		return x.PolicyLimitDays
	}
	return ""
}

func (x *IN1) GetRoomRateSemiPrivate() *CP {
	if x != nil {
		return x.RoomRateSemiPrivate
	}
	return nil
}

func (x *IN1) GetRoomRatePrivate() *CP {
	if x != nil {
		return x.RoomRatePrivate
	}
	return nil
}

func (x *IN1) GetInsuredEmploymentStatus() *CE {
	if x != nil {
		return x.InsuredEmploymentStatus
	}
	return nil
}

func (x *IN1) GetInsuredSex() string {
	if x != nil {
		return x.InsuredSex
	}
	return ""
}

func (x *IN1) GetInsuredEmployerAddress() *XAD {
	if x != nil {
		return x.InsuredEmployerAddress
	}
	return nil
}

func (x *IN1) GetVerificationStatus() string {
	if x != nil {
		return x.VerificationStatus
	}
	return ""
}

func (x *IN1) GetPriorInsturancePlanId() string {
	if x != nil {
		return x.PriorInsturancePlanId
	}
	return ""
}

func (x *IN1) GetCoverageType() string {
	if x != nil {
		return x.CoverageType
	}
	return ""
}

func (x *IN1) GetHandicap() string {
	if x != nil {
		return x.Handicap
	}
	return ""
}

func (x *IN1) GetInsuredIdNumber() *CX {
	if x != nil {
		return x.InsuredIdNumber
	}
	return nil
}

type IN2 struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	InsuredEmployeeId                  *CX                    `protobuf:"bytes,1,opt,name=insured_employee_id,json=insuredEmployeeId,proto3" json:"insured_employee_id,omitempty"`
	InsuredSsn                         string                 `protobuf:"bytes,2,opt,name=insured_ssn,json=insuredSsn,proto3" json:"insured_ssn,omitempty"`
	InsuredEmployerName                *XCN                   `protobuf:"bytes,3,opt,name=insured_employer_name,json=insuredEmployerName,proto3" json:"insured_employer_name,omitempty"`
	EmployerInformationData            string                 `protobuf:"bytes,4,opt,name=employer_information_data,json=employerInformationData,proto3" json:"employer_information_data,omitempty"`
	MailClaimParty                     string                 `protobuf:"bytes,5,opt,name=mail_claim_party,json=mailClaimParty,proto3" json:"mail_claim_party,omitempty"`
	MedicareCardNumber                 string                 `protobuf:"bytes,6,opt,name=medicare_card_number,json=medicareCardNumber,proto3" json:"medicare_card_number,omitempty"`
	MedicaidCaseName                   *XPN                   `protobuf:"bytes,7,opt,name=medicaid_case_name,json=medicaidCaseName,proto3" json:"medicaid_case_name,omitempty"`
	MedicaidCaseNumber                 string                 `protobuf:"bytes,8,opt,name=medicaid_case_number,json=medicaidCaseNumber,proto3" json:"medicaid_case_number,omitempty"`
	ChampuSponsorName                  *XPN                   `protobuf:"bytes,9,opt,name=champu_sponsor_name,json=champuSponsorName,proto3" json:"champu_sponsor_name,omitempty"`
	ChampusIdNumber                    string                 `protobuf:"bytes,10,opt,name=champus_id_number,json=champusIdNumber,proto3" json:"champus_id_number,omitempty"`
	ChampusDependentRecipient          *CE                    `protobuf:"bytes,11,opt,name=champus_dependent_recipient,json=champusDependentRecipient,proto3" json:"champus_dependent_recipient,omitempty"`
	ChampusOrganization                string                 `protobuf:"bytes,12,opt,name=champus_organization,json=champusOrganization,proto3" json:"champus_organization,omitempty"`
	ChampusStation                     string                 `protobuf:"bytes,13,opt,name=champus_station,json=champusStation,proto3" json:"champus_station,omitempty"`
	ChampusService                     string                 `protobuf:"bytes,14,opt,name=champus_service,json=champusService,proto3" json:"champus_service,omitempty"`
	ChampusRank                        string                 `protobuf:"bytes,15,opt,name=champus_rank,json=champusRank,proto3" json:"champus_rank,omitempty"`
	ChampusStatus                      string                 `protobuf:"bytes,16,opt,name=champus_status,json=champusStatus,proto3" json:"champus_status,omitempty"`
	ChampusRetireDate                  string                 `protobuf:"bytes,17,opt,name=champus_retire_date,json=champusRetireDate,proto3" json:"champus_retire_date,omitempty"`
	ChampusNonAvailCertOnFile          string                 `protobuf:"bytes,18,opt,name=champus_non_avail_cert_on_file,json=champusNonAvailCertOnFile,proto3" json:"champus_non_avail_cert_on_file,omitempty"`
	BabyCoverage                       string                 `protobuf:"bytes,19,opt,name=baby_coverage,json=babyCoverage,proto3" json:"baby_coverage,omitempty"`
	CombineBabyBill                    string                 `protobuf:"bytes,20,opt,name=combine_baby_bill,json=combineBabyBill,proto3" json:"combine_baby_bill,omitempty"`
	BloodDeductible                    string                 `protobuf:"bytes,21,opt,name=blood_deductible,json=bloodDeductible,proto3" json:"blood_deductible,omitempty"`
	SpecialCoverageApprovalName        *XPN                   `protobuf:"bytes,22,opt,name=special_coverage_approval_name,json=specialCoverageApprovalName,proto3" json:"special_coverage_approval_name,omitempty"`
	SpecialCoverageApprovalTitle       string                 `protobuf:"bytes,23,opt,name=special_coverage_approval_title,json=specialCoverageApprovalTitle,proto3" json:"special_coverage_approval_title,omitempty"`
	NoncoveredInsuranceCode            string                 `protobuf:"bytes,24,opt,name=noncovered_insurance_code,json=noncoveredInsuranceCode,proto3" json:"noncovered_insurance_code,omitempty"`
	PayorId                            *CX                    `protobuf:"bytes,25,opt,name=payor_id,json=payorId,proto3" json:"payor_id,omitempty"`
	PayorSubscriberId                  *CX                    `protobuf:"bytes,26,opt,name=payor_subscriber_id,json=payorSubscriberId,proto3" json:"payor_subscriber_id,omitempty"`
	EligibilitySource                  string                 `protobuf:"bytes,27,opt,name=eligibility_source,json=eligibilitySource,proto3" json:"eligibility_source,omitempty"`
	RoomCoverageType                   *CMPLT                 `protobuf:"bytes,28,opt,name=room_coverage_type,json=roomCoverageType,proto3" json:"room_coverage_type,omitempty"`
	PolicyType                         *CMPLT                 `protobuf:"bytes,29,opt,name=policy_type,json=policyType,proto3" json:"policy_type,omitempty"`
	DailyDeductible                    *CMDDE                 `protobuf:"bytes,30,opt,name=daily_deductible,json=dailyDeductible,proto3" json:"daily_deductible,omitempty"`
	LivingDependency                   string                 `protobuf:"bytes,31,opt,name=living_dependency,json=livingDependency,proto3" json:"living_dependency,omitempty"`
	AmbulatoryStatus                   string                 `protobuf:"bytes,32,opt,name=ambulatory_status,json=ambulatoryStatus,proto3" json:"ambulatory_status,omitempty"`
	Citizenship                        string                 `protobuf:"bytes,33,opt,name=citizenship,proto3" json:"citizenship,omitempty"`
	PrimaryLanguage                    *CE                    `protobuf:"bytes,34,opt,name=primary_language,json=primaryLanguage,proto3" json:"primary_language,omitempty"`
	LivingArrangement                  string                 `protobuf:"bytes,35,opt,name=living_arrangement,json=livingArrangement,proto3" json:"living_arrangement,omitempty"`
	PublicityIndicator                 *CE                    `protobuf:"bytes,36,opt,name=publicity_indicator,json=publicityIndicator,proto3" json:"publicity_indicator,omitempty"`
	ProtectionIndicator                string                 `protobuf:"bytes,37,opt,name=protection_indicator,json=protectionIndicator,proto3" json:"protection_indicator,omitempty"`
	StudentIndicator                   string                 `protobuf:"bytes,38,opt,name=student_indicator,json=studentIndicator,proto3" json:"student_indicator,omitempty"`
	Religion                           string                 `protobuf:"bytes,39,opt,name=religion,proto3" json:"religion,omitempty"`
	MotherMaidenName                   *XPN                   `protobuf:"bytes,40,opt,name=mother_maiden_name,json=motherMaidenName,proto3" json:"mother_maiden_name,omitempty"`
	Nationality                        *CE                    `protobuf:"bytes,41,opt,name=nationality,proto3" json:"nationality,omitempty"`
	EthnicGroup                        string                 `protobuf:"bytes,42,opt,name=ethnic_group,json=ethnicGroup,proto3" json:"ethnic_group,omitempty"`
	MaritalStatus                      string                 `protobuf:"bytes,43,opt,name=marital_status,json=maritalStatus,proto3" json:"marital_status,omitempty"`
	InsuredEmploymentStartDate         string                 `protobuf:"bytes,44,opt,name=insured_employment_start_date,json=insuredEmploymentStartDate,proto3" json:"insured_employment_start_date,omitempty"`
	InsuredEmploymentStopDate          string                 `protobuf:"bytes,45,opt,name=insured_employment_stop_date,json=insuredEmploymentStopDate,proto3" json:"insured_employment_stop_date,omitempty"`
	JobTitle                           string                 `protobuf:"bytes,46,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	JobCode                            *JCC                   `protobuf:"bytes,47,opt,name=job_code,json=jobCode,proto3" json:"job_code,omitempty"`
	JobStatus                          string                 `protobuf:"bytes,48,opt,name=job_status,json=jobStatus,proto3" json:"job_status,omitempty"`
	EmployerContactName                *XPN                   `protobuf:"bytes,49,opt,name=employer_contact_name,json=employerContactName,proto3" json:"employer_contact_name,omitempty"`
	EmployerContactPhoneNumber         *XTN                   `protobuf:"bytes,50,opt,name=employer_contact_phone_number,json=employerContactPhoneNumber,proto3" json:"employer_contact_phone_number,omitempty"`
	EmployerContactReason              string                 `protobuf:"bytes,51,opt,name=employer_contact_reason,json=employerContactReason,proto3" json:"employer_contact_reason,omitempty"`
	InsuredContactName                 *XPN                   `protobuf:"bytes,52,opt,name=insured_contact_name,json=insuredContactName,proto3" json:"insured_contact_name,omitempty"`
	InsuredContactPhoneNumbet          *XTN                   `protobuf:"bytes,53,opt,name=insured_contact_phone_numbet,json=insuredContactPhoneNumbet,proto3" json:"insured_contact_phone_numbet,omitempty"`
	InsuredContactReason               string                 `protobuf:"bytes,54,opt,name=insured_contact_reason,json=insuredContactReason,proto3" json:"insured_contact_reason,omitempty"`
	RelationshipToPatientStartDate     string                 `protobuf:"bytes,55,opt,name=relationship_to_patient_start_date,json=relationshipToPatientStartDate,proto3" json:"relationship_to_patient_start_date,omitempty"`
	RelationshipToPatientStopDate      string                 `protobuf:"bytes,56,opt,name=relationship_to_patient_stop_date,json=relationshipToPatientStopDate,proto3" json:"relationship_to_patient_stop_date,omitempty"`
	InsuranceCompanyContactReason      string                 `protobuf:"bytes,57,opt,name=insurance_company_contact_reason,json=insuranceCompanyContactReason,proto3" json:"insurance_company_contact_reason,omitempty"`
	InsuranceCompanyContactPhoneNumber *XTN                   `protobuf:"bytes,58,opt,name=insurance_company_contact_phone_number,json=insuranceCompanyContactPhoneNumber,proto3" json:"insurance_company_contact_phone_number,omitempty"`
	PolicyScope                        string                 `protobuf:"bytes,59,opt,name=policy_scope,json=policyScope,proto3" json:"policy_scope,omitempty"`
	PolicySource                       string                 `protobuf:"bytes,60,opt,name=policy_source,json=policySource,proto3" json:"policy_source,omitempty"`
	PatientMemberNumber                *CX                    `protobuf:"bytes,61,opt,name=patient_member_number,json=patientMemberNumber,proto3" json:"patient_member_number,omitempty"`
	GuarantorRelationship              string                 `protobuf:"bytes,62,opt,name=guarantor_relationship,json=guarantorRelationship,proto3" json:"guarantor_relationship,omitempty"`
	InsuredHomePhoneNumber             *XTN                   `protobuf:"bytes,63,opt,name=insured_home_phone_number,json=insuredHomePhoneNumber,proto3" json:"insured_home_phone_number,omitempty"`
	InsuredHomeWorkNumber              *XTN                   `protobuf:"bytes,64,opt,name=insured_home_work_number,json=insuredHomeWorkNumber,proto3" json:"insured_home_work_number,omitempty"`
	MilitaryHandicappedProgram         *CE                    `protobuf:"bytes,65,opt,name=military_handicapped_program,json=militaryHandicappedProgram,proto3" json:"military_handicapped_program,omitempty"`
	SuspendFlag                        string                 `protobuf:"bytes,66,opt,name=suspend_flag,json=suspendFlag,proto3" json:"suspend_flag,omitempty"`
	CopayLimitFlag                     string                 `protobuf:"bytes,67,opt,name=copay_limit_flag,json=copayLimitFlag,proto3" json:"copay_limit_flag,omitempty"`
	StoplossLimitFlag                  string                 `protobuf:"bytes,68,opt,name=stoploss_limit_flag,json=stoplossLimitFlag,proto3" json:"stoploss_limit_flag,omitempty"`
	InsuredOrganizationName            *XON                   `protobuf:"bytes,69,opt,name=insured_organization_name,json=insuredOrganizationName,proto3" json:"insured_organization_name,omitempty"`
	InsuredEmployerOrganizationName    *XON                   `protobuf:"bytes,70,opt,name=insured_employer_organization_name,json=insuredEmployerOrganizationName,proto3" json:"insured_employer_organization_name,omitempty"`
	Race                               string                 `protobuf:"bytes,71,opt,name=race,proto3" json:"race,omitempty"`
	HcfaPatientRelationshipToInsured   *CE                    `protobuf:"bytes,72,opt,name=hcfa_patient_relationship_to_insured,json=hcfaPatientRelationshipToInsured,proto3" json:"hcfa_patient_relationship_to_insured,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *IN2) Reset() {
	*x = IN2{}
	mi := &file_standards_v23_financial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IN2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IN2) ProtoMessage() {}

func (x *IN2) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_financial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IN2.ProtoReflect.Descriptor instead.
func (*IN2) Descriptor() ([]byte, []int) {
	return file_standards_v23_financial_proto_rawDescGZIP(), []int{2}
}

func (x *IN2) GetInsuredEmployeeId() *CX {
	if x != nil {
		return x.InsuredEmployeeId
	}
	return nil
}

func (x *IN2) GetInsuredSsn() string {
	if x != nil {
		return x.InsuredSsn
	}
	return ""
}

func (x *IN2) GetInsuredEmployerName() *XCN {
	if x != nil {
		return x.InsuredEmployerName
	}
	return nil
}

func (x *IN2) GetEmployerInformationData() string {
	if x != nil {
		return x.EmployerInformationData
	}
	return ""
}

func (x *IN2) GetMailClaimParty() string {
	if x != nil {
		return x.MailClaimParty
	}
	return ""
}

func (x *IN2) GetMedicareCardNumber() string {
	if x != nil {
		return x.MedicareCardNumber
	}
	return ""
}

func (x *IN2) GetMedicaidCaseName() *XPN {
	if x != nil {
		return x.MedicaidCaseName
	}
	return nil
}

func (x *IN2) GetMedicaidCaseNumber() string {
	if x != nil {
		return x.MedicaidCaseNumber
	}
	return ""
}

func (x *IN2) GetChampuSponsorName() *XPN {
	if x != nil {
		return x.ChampuSponsorName
	}
	return nil
}

func (x *IN2) GetChampusIdNumber() string {
	if x != nil {
		return x.ChampusIdNumber
	}
	return ""
}

func (x *IN2) GetChampusDependentRecipient() *CE {
	if x != nil {
		return x.ChampusDependentRecipient
	}
	return nil
}

func (x *IN2) GetChampusOrganization() string {
	if x != nil {
		return x.ChampusOrganization
	}
	return ""
}

func (x *IN2) GetChampusStation() string {
	if x != nil {
		return x.ChampusStation
	}
	return ""
}

func (x *IN2) GetChampusService() string {
	if x != nil {
		return x.ChampusService
	}
	return ""
}

func (x *IN2) GetChampusRank() string {
	if x != nil {
		return x.ChampusRank
	}
	return ""
}

func (x *IN2) GetChampusStatus() string {
	if x != nil {
		return x.ChampusStatus
	}
	return ""
}

func (x *IN2) GetChampusRetireDate() string {
	if x != nil {
		return x.ChampusRetireDate
	}
	return ""
}

func (x *IN2) GetChampusNonAvailCertOnFile() string {
	if x != nil {
		return x.ChampusNonAvailCertOnFile
	}
	return ""
}

func (x *IN2) GetBabyCoverage() string {
	if x != nil {
		return x.BabyCoverage
	}
	return ""
}

func (x *IN2) GetCombineBabyBill() string {
	if x != nil {
		return x.CombineBabyBill
	}
	return ""
}

func (x *IN2) GetBloodDeductible() string {
	if x != nil {
		return x.BloodDeductible
	}
	return ""
}

func (x *IN2) GetSpecialCoverageApprovalName() *XPN {
	if x != nil {
		return x.SpecialCoverageApprovalName
	}
	return nil
}

func (x *IN2) GetSpecialCoverageApprovalTitle() string {
	if x != nil {
		return x.SpecialCoverageApprovalTitle
	}
	return ""
}

func (x *IN2) GetNoncoveredInsuranceCode() string {
	if x != nil {
		return x.NoncoveredInsuranceCode
	}
	return ""
}

func (x *IN2) GetPayorId() *CX {
	if x != nil {
		return x.PayorId
	}
	return nil
}

func (x *IN2) GetPayorSubscriberId() *CX {
	if x != nil {
		return x.PayorSubscriberId
	}
	return nil
}

func (x *IN2) GetEligibilitySource() string {
	if x != nil {
		return x.EligibilitySource
	}
	return ""
}

func (x *IN2) GetRoomCoverageType() *CMPLT {
	if x != nil {
		return x.RoomCoverageType
	}
	return nil
}

func (x *IN2) GetPolicyType() *CMPLT {
	if x != nil {
		return x.PolicyType
	}
	return nil
}

func (x *IN2) GetDailyDeductible() *CMDDE {
	if x != nil {
		return x.DailyDeductible
	}
	return nil
}

func (x *IN2) GetLivingDependency() string {
	if x != nil {
		return x.LivingDependency
	}
	return ""
}

func (x *IN2) GetAmbulatoryStatus() string {
	if x != nil {
		return x.AmbulatoryStatus
	}
	return ""
}

func (x *IN2) GetCitizenship() string {
	if x != nil {
		return x.Citizenship
	}
	return ""
}

func (x *IN2) GetPrimaryLanguage() *CE {
	if x != nil {
		return x.PrimaryLanguage
	}
	return nil
}

func (x *IN2) GetLivingArrangement() string {
	if x != nil {
		return x.LivingArrangement
	}
	return ""
}

func (x *IN2) GetPublicityIndicator() *CE {
	if x != nil {
		return x.PublicityIndicator
	}
	return nil
}

func (x *IN2) GetProtectionIndicator() string {
	if x != nil {
		return x.ProtectionIndicator
	}
	return ""
}

func (x *IN2) GetStudentIndicator() string {
	if x != nil {
		return x.StudentIndicator
	}
	return ""
}

func (x *IN2) GetReligion() string {
	if x != nil {
		return x.Religion
	}
	return ""
}

func (x *IN2) GetMotherMaidenName() *XPN {
	if x != nil {
		return x.MotherMaidenName
	}
	return nil
}

func (x *IN2) GetNationality() *CE {
	if x != nil {
		return x.Nationality
	}
	return nil
}

func (x *IN2) GetEthnicGroup() string {
	if x != nil {
		return x.EthnicGroup
	}
	return ""
}

func (x *IN2) GetMaritalStatus() string {
	if x != nil {
		return x.MaritalStatus
	}
	return ""
}

func (x *IN2) GetInsuredEmploymentStartDate() string {
	if x != nil {
		return x.InsuredEmploymentStartDate
	}
	return ""
}

func (x *IN2) GetInsuredEmploymentStopDate() string {
	if x != nil {
		return x.InsuredEmploymentStopDate
	}
	return ""
}

func (x *IN2) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *IN2) GetJobCode() *JCC {
	if x != nil {
		return x.JobCode
	}
	return nil
}

func (x *IN2) GetJobStatus() string {
	if x != nil {
		return x.JobStatus
	}
	return ""
}

func (x *IN2) GetEmployerContactName() *XPN {
	if x != nil {
		return x.EmployerContactName
	}
	return nil
}

func (x *IN2) GetEmployerContactPhoneNumber() *XTN {
	if x != nil {
		return x.EmployerContactPhoneNumber
	}
	return nil
}

func (x *IN2) GetEmployerContactReason() string {
	if x != nil {
		return x.EmployerContactReason
	}
	return ""
}

func (x *IN2) GetInsuredContactName() *XPN {
	if x != nil {
		return x.InsuredContactName
	}
	return nil
}

func (x *IN2) GetInsuredContactPhoneNumbet() *XTN {
	if x != nil {
		return x.InsuredContactPhoneNumbet
	}
	return nil
}

func (x *IN2) GetInsuredContactReason() string {
	if x != nil {
		return x.InsuredContactReason
	}
	return ""
}

func (x *IN2) GetRelationshipToPatientStartDate() string {
	if x != nil {
		return x.RelationshipToPatientStartDate
	}
	return ""
}

func (x *IN2) GetRelationshipToPatientStopDate() string {
	if x != nil {
		return x.RelationshipToPatientStopDate
	}
	return ""
}

func (x *IN2) GetInsuranceCompanyContactReason() string {
	if x != nil {
		return x.InsuranceCompanyContactReason
	}
	return ""
}

func (x *IN2) GetInsuranceCompanyContactPhoneNumber() *XTN {
	if x != nil {
		return x.InsuranceCompanyContactPhoneNumber
	}
	return nil
}

func (x *IN2) GetPolicyScope() string {
	if x != nil {
		return x.PolicyScope
	}
	return ""
}

func (x *IN2) GetPolicySource() string {
	if x != nil {
		return x.PolicySource
	}
	return ""
}

func (x *IN2) GetPatientMemberNumber() *CX {
	if x != nil {
		return x.PatientMemberNumber
	}
	return nil
}

func (x *IN2) GetGuarantorRelationship() string {
	if x != nil {
		return x.GuarantorRelationship
	}
	return ""
}

func (x *IN2) GetInsuredHomePhoneNumber() *XTN {
	if x != nil {
		return x.InsuredHomePhoneNumber
	}
	return nil
}

func (x *IN2) GetInsuredHomeWorkNumber() *XTN {
	if x != nil {
		return x.InsuredHomeWorkNumber
	}
	return nil
}

func (x *IN2) GetMilitaryHandicappedProgram() *CE {
	if x != nil {
		return x.MilitaryHandicappedProgram
	}
	return nil
}

func (x *IN2) GetSuspendFlag() string {
	if x != nil {
		return x.SuspendFlag
	}
	return ""
}

func (x *IN2) GetCopayLimitFlag() string {
	if x != nil {
		return x.CopayLimitFlag
	}
	return ""
}

func (x *IN2) GetStoplossLimitFlag() string {
	if x != nil {
		return x.StoplossLimitFlag
	}
	return ""
}

func (x *IN2) GetInsuredOrganizationName() *XON {
	if x != nil {
		return x.InsuredOrganizationName
	}
	return nil
}

func (x *IN2) GetInsuredEmployerOrganizationName() *XON {
	if x != nil {
		return x.InsuredEmployerOrganizationName
	}
	return nil
}

func (x *IN2) GetRace() string {
	if x != nil {
		return x.Race
	}
	return ""
}

func (x *IN2) GetHcfaPatientRelationshipToInsured() *CE {
	if x != nil {
		return x.HcfaPatientRelationshipToInsured
	}
	return nil
}

type IN3 struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	SetId                              string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	CertificationNumber                *CX                    `protobuf:"bytes,2,opt,name=certification_number,json=certificationNumber,proto3" json:"certification_number,omitempty"`
	CertifiedBy                        *XCN                   `protobuf:"bytes,3,opt,name=certified_by,json=certifiedBy,proto3" json:"certified_by,omitempty"`
	CertificationRequired              string                 `protobuf:"bytes,4,opt,name=certification_required,json=certificationRequired,proto3" json:"certification_required,omitempty"`
	Penalty                            *CMVAL                 `protobuf:"bytes,5,opt,name=penalty,proto3" json:"penalty,omitempty"`
	CertificationDateTime              string                 `protobuf:"bytes,6,opt,name=certification_date_time,json=certificationDateTime,proto3" json:"certification_date_time,omitempty"`
	CertificationModalityDateTime      string                 `protobuf:"bytes,7,opt,name=certification_modality_date_time,json=certificationModalityDateTime,proto3" json:"certification_modality_date_time,omitempty"`
	Operator                           *XCN                   `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	CertificationBeginDate             string                 `protobuf:"bytes,9,opt,name=certification_begin_date,json=certificationBeginDate,proto3" json:"certification_begin_date,omitempty"`
	CertificationEndDate               string                 `protobuf:"bytes,10,opt,name=certification_end_date,json=certificationEndDate,proto3" json:"certification_end_date,omitempty"`
	Days                               *CMVAL                 `protobuf:"bytes,11,opt,name=days,proto3" json:"days,omitempty"`
	NonConcurCodeDescription           *CE                    `protobuf:"bytes,12,opt,name=non_concur_code_description,json=nonConcurCodeDescription,proto3" json:"non_concur_code_description,omitempty"`
	NonConcurEffectiveDateTime         string                 `protobuf:"bytes,13,opt,name=non_concur_effective_date_time,json=nonConcurEffectiveDateTime,proto3" json:"non_concur_effective_date_time,omitempty"`
	PhysicianReviewer                  *XCN                   `protobuf:"bytes,14,opt,name=physician_reviewer,json=physicianReviewer,proto3" json:"physician_reviewer,omitempty"`
	CertificationContact               string                 `protobuf:"bytes,15,opt,name=certification_contact,json=certificationContact,proto3" json:"certification_contact,omitempty"`
	CertificationContactPhoneNumber    *XTN                   `protobuf:"bytes,16,opt,name=certification_contact_phone_number,json=certificationContactPhoneNumber,proto3" json:"certification_contact_phone_number,omitempty"`
	AppealReason                       *CE                    `protobuf:"bytes,17,opt,name=appeal_reason,json=appealReason,proto3" json:"appeal_reason,omitempty"`
	CertificationAgency                *CE                    `protobuf:"bytes,18,opt,name=certification_agency,json=certificationAgency,proto3" json:"certification_agency,omitempty"`
	CertificationAgencyPhoneNumber     *XTN                   `protobuf:"bytes,19,opt,name=certification_agency_phone_number,json=certificationAgencyPhoneNumber,proto3" json:"certification_agency_phone_number,omitempty"`
	PreCertRequirementWindow           *CMPCR                 `protobuf:"bytes,20,opt,name=pre_cert_requirement_window,json=preCertRequirementWindow,proto3" json:"pre_cert_requirement_window,omitempty"`
	CaseManager                        string                 `protobuf:"bytes,21,opt,name=case_manager,json=caseManager,proto3" json:"case_manager,omitempty"`
	SecondOpinionDate                  string                 `protobuf:"bytes,22,opt,name=second_opinion_date,json=secondOpinionDate,proto3" json:"second_opinion_date,omitempty"`
	SecondOpinionStatus                string                 `protobuf:"bytes,23,opt,name=second_opinion_status,json=secondOpinionStatus,proto3" json:"second_opinion_status,omitempty"`
	SecondOpinionDocumentationReceived string                 `protobuf:"bytes,24,opt,name=second_opinion_documentation_received,json=secondOpinionDocumentationReceived,proto3" json:"second_opinion_documentation_received,omitempty"`
	SecondOpinionPhysician             *XCN                   `protobuf:"bytes,25,opt,name=second_opinion_physician,json=secondOpinionPhysician,proto3" json:"second_opinion_physician,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *IN3) Reset() {
	*x = IN3{}
	mi := &file_standards_v23_financial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IN3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IN3) ProtoMessage() {}

func (x *IN3) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_financial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IN3.ProtoReflect.Descriptor instead.
func (*IN3) Descriptor() ([]byte, []int) {
	return file_standards_v23_financial_proto_rawDescGZIP(), []int{3}
}

func (x *IN3) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *IN3) GetCertificationNumber() *CX {
	if x != nil {
		return x.CertificationNumber
	}
	return nil
}

func (x *IN3) GetCertifiedBy() *XCN {
	if x != nil {
		return x.CertifiedBy
	}
	return nil
}

func (x *IN3) GetCertificationRequired() string {
	if x != nil {
		return x.CertificationRequired
	}
	return ""
}

func (x *IN3) GetPenalty() *CMVAL {
	if x != nil {
		return x.Penalty
	}
	return nil
}

func (x *IN3) GetCertificationDateTime() string {
	if x != nil {
		return x.CertificationDateTime
	}
	return ""
}

func (x *IN3) GetCertificationModalityDateTime() string {
	if x != nil {
		return x.CertificationModalityDateTime
	}
	return ""
}

func (x *IN3) GetOperator() *XCN {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *IN3) GetCertificationBeginDate() string {
	if x != nil {
		return x.CertificationBeginDate
	}
	return ""
}

func (x *IN3) GetCertificationEndDate() string {
	if x != nil {
		return x.CertificationEndDate
	}
	return ""
}

func (x *IN3) GetDays() *CMVAL {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *IN3) GetNonConcurCodeDescription() *CE {
	if x != nil {
		return x.NonConcurCodeDescription
	}
	return nil
}

func (x *IN3) GetNonConcurEffectiveDateTime() string {
	if x != nil {
		return x.NonConcurEffectiveDateTime
	}
	return ""
}

func (x *IN3) GetPhysicianReviewer() *XCN {
	if x != nil {
		return x.PhysicianReviewer
	}
	return nil
}

func (x *IN3) GetCertificationContact() string {
	if x != nil {
		return x.CertificationContact
	}
	return ""
}

func (x *IN3) GetCertificationContactPhoneNumber() *XTN {
	if x != nil {
		return x.CertificationContactPhoneNumber
	}
	return nil
}

func (x *IN3) GetAppealReason() *CE {
	if x != nil {
		return x.AppealReason
	}
	return nil
}

func (x *IN3) GetCertificationAgency() *CE {
	if x != nil {
		return x.CertificationAgency
	}
	return nil
}

func (x *IN3) GetCertificationAgencyPhoneNumber() *XTN {
	if x != nil {
		return x.CertificationAgencyPhoneNumber
	}
	return nil
}

func (x *IN3) GetPreCertRequirementWindow() *CMPCR {
	if x != nil {
		return x.PreCertRequirementWindow
	}
	return nil
}

func (x *IN3) GetCaseManager() string {
	if x != nil {
		return x.CaseManager
	}
	return ""
}

func (x *IN3) GetSecondOpinionDate() string {
	if x != nil {
		return x.SecondOpinionDate
	}
	return ""
}

func (x *IN3) GetSecondOpinionStatus() string {
	if x != nil {
		return x.SecondOpinionStatus
	}
	return ""
}

func (x *IN3) GetSecondOpinionDocumentationReceived() string {
	if x != nil {
		return x.SecondOpinionDocumentationReceived
	}
	return ""
}

func (x *IN3) GetSecondOpinionPhysician() *XCN {
	if x != nil {
		return x.SecondOpinionPhysician
	}
	return nil
}

type DG1 struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SetId                   string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	CodingMethod            string                 `protobuf:"bytes,2,opt,name=coding_method,json=codingMethod,proto3" json:"coding_method,omitempty"`
	Code                    *CE                    `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description             string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DateTime                string                 `protobuf:"bytes,5,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Type                    string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	MajorDiagnosticCategory *CE                    `protobuf:"bytes,7,opt,name=major_diagnostic_category,json=majorDiagnosticCategory,proto3" json:"major_diagnostic_category,omitempty"`
	DiagnosticRelatedGroup  *CE                    `protobuf:"bytes,8,opt,name=diagnostic_related_group,json=diagnosticRelatedGroup,proto3" json:"diagnostic_related_group,omitempty"`
	DrgApprovalIndicator    string                 `protobuf:"bytes,9,opt,name=drg_approval_indicator,json=drgApprovalIndicator,proto3" json:"drg_approval_indicator,omitempty"`
	DrgGrouperReviewCode    string                 `protobuf:"bytes,10,opt,name=drg_grouper_review_code,json=drgGrouperReviewCode,proto3" json:"drg_grouper_review_code,omitempty"`
	OutlierType             *CE                    `protobuf:"bytes,11,opt,name=outlier_type,json=outlierType,proto3" json:"outlier_type,omitempty"`
	OutlierDays             string                 `protobuf:"bytes,12,opt,name=outlier_days,json=outlierDays,proto3" json:"outlier_days,omitempty"`
	OutlierCost             *CP                    `protobuf:"bytes,13,opt,name=outlier_cost,json=outlierCost,proto3" json:"outlier_cost,omitempty"`
	GoruperVersion          string                 `protobuf:"bytes,14,opt,name=goruper_version,json=goruperVersion,proto3" json:"goruper_version,omitempty"`
	Priority                string                 `protobuf:"bytes,15,opt,name=priority,proto3" json:"priority,omitempty"`
	DiagnosingClinician     *XCN                   `protobuf:"bytes,16,opt,name=diagnosing_clinician,json=diagnosingClinician,proto3" json:"diagnosing_clinician,omitempty"`
	Classification          string                 `protobuf:"bytes,17,opt,name=classification,proto3" json:"classification,omitempty"`
	ConfidentialIndicator   string                 `protobuf:"bytes,18,opt,name=confidential_indicator,json=confidentialIndicator,proto3" json:"confidential_indicator,omitempty"`
	AttestationDateTime     string                 `protobuf:"bytes,19,opt,name=attestation_date_time,json=attestationDateTime,proto3" json:"attestation_date_time,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DG1) Reset() {
	*x = DG1{}
	mi := &file_standards_v23_financial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DG1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DG1) ProtoMessage() {}

func (x *DG1) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_financial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DG1.ProtoReflect.Descriptor instead.
func (*DG1) Descriptor() ([]byte, []int) {
	return file_standards_v23_financial_proto_rawDescGZIP(), []int{4}
}

func (x *DG1) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *DG1) GetCodingMethod() string {
	if x != nil {
		return x.CodingMethod
	}
	return ""
}

func (x *DG1) GetCode() *CE {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *DG1) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DG1) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

func (x *DG1) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DG1) GetMajorDiagnosticCategory() *CE {
	if x != nil {
		return x.MajorDiagnosticCategory
	}
	return nil
}

func (x *DG1) GetDiagnosticRelatedGroup() *CE {
	if x != nil {
		return x.DiagnosticRelatedGroup
	}
	return nil
}

func (x *DG1) GetDrgApprovalIndicator() string {
	if x != nil {
		return x.DrgApprovalIndicator
	}
	return ""
}

func (x *DG1) GetDrgGrouperReviewCode() string {
	if x != nil {
		return x.DrgGrouperReviewCode
	}
	return ""
}

func (x *DG1) GetOutlierType() *CE {
	if x != nil {
		return x.OutlierType
	}
	return nil
}

func (x *DG1) GetOutlierDays() string {
	if x != nil {
		return x.OutlierDays
	}
	return ""
}

func (x *DG1) GetOutlierCost() *CP {
	if x != nil {
		return x.OutlierCost
	}
	return nil
}

func (x *DG1) GetGoruperVersion() string {
	if x != nil {
		return x.GoruperVersion
	}
	return ""
}

func (x *DG1) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *DG1) GetDiagnosingClinician() *XCN {
	if x != nil {
		return x.DiagnosingClinician
	}
	return nil
}

func (x *DG1) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *DG1) GetConfidentialIndicator() string {
	if x != nil {
		return x.ConfidentialIndicator
	}
	return ""
}

func (x *DG1) GetAttestationDateTime() string {
	if x != nil {
		return x.AttestationDateTime
	}
	return ""
}

var File_standards_v23_financial_proto protoreflect.FileDescriptor

const file_standards_v23_financial_proto_rawDesc = "" +
	"\n" +
	"\x1dstandards/v23/financial.proto\x12\rstandards.v23\x1a\x19standards/v23/types.proto\"\xbb\x14\n" +
	"\x03GT1\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12<\n" +
	"\x10guarantor_number\x18\x02 \x01(\v2\x11.standards.v23.CXR\x0fguarantorNumber\x12&\n" +
	"\x04name\x18\x03 \x01(\v2\x12.standards.v23.XPNR\x04name\x123\n" +
	"\vspouse_name\x18\x04 \x01(\v2\x12.standards.v23.XPNR\n" +
	"spouseName\x12,\n" +
	"\aaddress\x18\x05 \x01(\v2\x12.standards.v23.XADR\aaddress\x12>\n" +
	"\x11home_phone_number\x18\x06 \x01(\v2\x12.standards.v23.XTNR\x0fhomePhoneNumber\x12>\n" +
	"\x11work_phone_number\x18\a \x01(\v2\x12.standards.v23.XTNR\x0fworkPhoneNumber\x12\x10\n" +
	"\x03dob\x18\b \x01(\tR\x03dob\x12\x10\n" +
	"\x03sex\x18\t \x01(\tR\x03sex\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x126\n" +
	"\x17relationship_to_patient\x18\v \x01(\tR\x15relationshipToPatient\x12\x10\n" +
	"\x03ssn\x18\f \x01(\tR\x03ssn\x12\x1d\n" +
	"\n" +
	"begin_date\x18\r \x01(\tR\tbeginDate\x12\x19\n" +
	"\bend_date\x18\x0e \x01(\tR\aendDate\x12\x1a\n" +
	"\bpriority\x18\x0f \x01(\tR\bpriority\x127\n" +
	"\remployer_name\x18\x10 \x01(\v2\x12.standards.v23.XPNR\femployerName\x12=\n" +
	"\x10employer_address\x18\x11 \x01(\v2\x12.standards.v23.XADR\x0femployerAddress\x12F\n" +
	"\x15employer_phone_number\x18\x12 \x01(\v2\x12.standards.v23.XTNR\x13employerPhoneNumber\x12?\n" +
	"\x12employee_id_number\x18\x13 \x01(\v2\x11.standards.v23.CXR\x10employeeIdNumber\x12+\n" +
	"\x11employment_status\x18\x14 \x01(\tR\x10employmentStatus\x12?\n" +
	"\x11organization_name\x18\x15 \x01(\v2\x12.standards.v23.XONR\x10organizationName\x12*\n" +
	"\x11billing_hold_flag\x18\x16 \x01(\tR\x0fbillingHoldFlag\x12?\n" +
	"\x12credit_rating_code\x18\x17 \x01(\v2\x11.standards.v23.CER\x10creditRatingCode\x12&\n" +
	"\x0fdeath_date_time\x18\x18 \x01(\tR\rdeathDateTime\x12\x1d\n" +
	"\n" +
	"death_flag\x18\x19 \x01(\tR\tdeathFlag\x12G\n" +
	"\x16charge_adjustment_code\x18\x1a \x01(\v2\x11.standards.v23.CER\x14chargeAdjustmentCode\x12I\n" +
	"\x17household_annual_income\x18\x1b \x01(\v2\x11.standards.v23.CPR\x15householdAnnualIncome\x12%\n" +
	"\x0ehousehold_size\x18\x1c \x01(\tR\rhouseholdSize\x12?\n" +
	"\x12employer_id_number\x18\x1d \x01(\v2\x11.standards.v23.CXR\x10employerIdNumber\x12%\n" +
	"\x0emarital_status\x18\x1e \x01(\tR\rmaritalStatus\x12.\n" +
	"\x13hire_effective_date\x18\x1f \x01(\tR\x11hireEffectiveDate\x120\n" +
	"\x14employment_stop_date\x18  \x01(\tR\x12employmentStopDate\x12+\n" +
	"\x11living_dependency\x18! \x01(\tR\x10livingDependency\x12+\n" +
	"\x11ambulatory_status\x18\" \x01(\tR\x10ambulatoryStatus\x12 \n" +
	"\vcitizenship\x18# \x01(\tR\vcitizenship\x12<\n" +
	"\x10primary_language\x18$ \x01(\v2\x11.standards.v23.CER\x0fprimaryLanguage\x12-\n" +
	"\x12living_arrangement\x18% \x01(\tR\x11livingArrangement\x12B\n" +
	"\x13publicity_indicator\x18& \x01(\v2\x11.standards.v23.CER\x12publicityIndicator\x121\n" +
	"\x14protection_indicator\x18' \x01(\tR\x13protectionIndicator\x12+\n" +
	"\x11student_indicator\x18( \x01(\tR\x10studentIndicator\x12\x1a\n" +
	"\breligion\x18) \x01(\tR\breligion\x12@\n" +
	"\x12mother_maiden_name\x18* \x01(\v2\x12.standards.v23.XPNR\x10motherMaidenName\x123\n" +
	"\vnationality\x18+ \x01(\v2\x11.standards.v23.CER\vnationality\x12!\n" +
	"\fethnic_group\x18, \x01(\tR\vethnicGroup\x125\n" +
	"\fcontact_name\x18- \x01(\v2\x12.standards.v23.XPNR\vcontactName\x12D\n" +
	"\x14contact_phone_number\x18. \x01(\v2\x12.standards.v23.XTNR\x12contactPhoneNumber\x128\n" +
	"\x0econtact_reason\x18/ \x01(\v2\x11.standards.v23.CER\rcontactReason\x121\n" +
	"\x14contact_relationship\x180 \x01(\tR\x13contactRelationship\x12\x1b\n" +
	"\tjob_title\x181 \x01(\tR\bjobTitle\x12-\n" +
	"\bjob_code\x182 \x01(\v2\x12.standards.v23.JCCR\ajobCode\x12P\n" +
	"\x1aemployer_organization_name\x183 \x01(\v2\x12.standards.v23.XONR\x18employerOrganizationName\x12\x1a\n" +
	"\bhandicap\x184 \x01(\tR\bhandicap\x12\x1d\n" +
	"\n" +
	"job_status\x185 \x01(\tR\tjobStatus\x12:\n" +
	"\x0ffinancial_class\x186 \x01(\v2\x11.standards.v23.FCR\x0efinancialClass\x12\x12\n" +
	"\x04race\x187 \x01(\tR\x04race\"\xf3\x12\n" +
	"\x03IN1\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12*\n" +
	"\aplan_id\x18\x02 \x01(\v2\x11.standards.v23.CER\x06planId\x120\n" +
	"\n" +
	"company_id\x18\x03 \x01(\v2\x11.standards.v23.CXR\tcompanyId\x125\n" +
	"\fcompany_name\x18\x04 \x01(\v2\x12.standards.v23.XONR\vcompanyName\x12;\n" +
	"\x0fcompany_address\x18\x05 \x01(\v2\x12.standards.v23.XADR\x0ecompanyAddress\x12;\n" +
	"\x0fcompany_contact\x18\x06 \x01(\v2\x12.standards.v23.XPNR\x0ecompanyContact\x12D\n" +
	"\x14company_phone_number\x18\a \x01(\v2\x12.standards.v23.XTNR\x12companyPhoneNumber\x12!\n" +
	"\fgroup_number\x18\b \x01(\tR\vgroupNumber\x121\n" +
	"\n" +
	"group_name\x18\t \x01(\v2\x12.standards.v23.XONR\tgroupName\x12=\n" +
	"\x11group_employer_id\x18\n" +
	" \x01(\v2\x11.standards.v23.CXR\x0fgroupEmployerId\x12B\n" +
	"\x13group_employer_name\x18\v \x01(\v2\x12.standards.v23.XONR\x11groupEmployerName\x12.\n" +
	"\x13plan_effective_date\x18\f \x01(\tR\x11planEffectiveDate\x120\n" +
	"\x14plan_expiration_date\x18\r \x01(\tR\x12planExpirationDate\x12Q\n" +
	"\x19authorization_information\x18\x0e \x01(\v2\x14.standards.v23.CMAUIR\x18authorizationInformation\x12\x1b\n" +
	"\tplan_type\x18\x0f \x01(\tR\bplanType\x125\n" +
	"\finsured_name\x18\x10 \x01(\v2\x12.standards.v23.XPNR\vinsuredName\x126\n" +
	"\x17relationship_to_patient\x18\x11 \x01(\tR\x15relationshipToPatient\x12\x1f\n" +
	"\vinsured_dob\x18\x12 \x01(\tR\n" +
	"insuredDob\x12;\n" +
	"\x0finsured_address\x18\x13 \x01(\v2\x12.standards.v23.XADR\x0einsuredAddress\x12\x10\n" +
	"\x03aob\x18\x14 \x01(\tR\x03aob\x12\x10\n" +
	"\x03cob\x18\x15 \x01(\tR\x03cob\x12!\n" +
	"\fcob_priority\x18\x16 \x01(\tR\vcobPriority\x12%\n" +
	"\x0eadmission_flag\x18\x17 \x01(\tR\radmissionFlag\x12%\n" +
	"\x0eadmission_date\x18\x18 \x01(\tR\radmissionDate\x12)\n" +
	"\x10eligibility_flag\x18\x19 \x01(\tR\x0feligibilityFlag\x12)\n" +
	"\x10eligibility_date\x18\x1a \x01(\tR\x0feligibilityDate\x128\n" +
	"\x18release_information_code\x18\x1b \x01(\tR\x16releaseInformationCode\x12\x10\n" +
	"\x03pac\x18\x1c \x01(\tR\x03pac\x124\n" +
	"\x16verification_date_time\x18\x1d \x01(\tR\x14verificationDateTime\x12;\n" +
	"\x0fverification_by\x18\x1e \x01(\v2\x12.standards.v23.XCNR\x0everificationBy\x12%\n" +
	"\x0eagreement_code\x18\x1f \x01(\tR\ragreementCode\x12%\n" +
	"\x0ebilling_status\x18  \x01(\tR\rbillingStatus\x122\n" +
	"\x15lifetime_reserve_days\x18! \x01(\tR\x13lifetimeReserveDays\x12-\n" +
	"\x13delay_before_lr_day\x18\" \x01(\tR\x10delayBeforeLrDay\x12*\n" +
	"\x11company_plan_code\x18# \x01(\tR\x0fcompanyPlanCode\x12#\n" +
	"\rpolicy_number\x18$ \x01(\tR\fpolicyNumber\x12>\n" +
	"\x11policy_deductible\x18% \x01(\v2\x11.standards.v23.CPR\x10policyDeductible\x12A\n" +
	"\x13policy_limit_amount\x18& \x01(\v2\x11.standards.v23.CPR\x11policyLimitAmount\x12*\n" +
	"\x11policy_limit_days\x18' \x01(\tR\x0fpolicyLimitDays\x12F\n" +
	"\x16room_rate_semi_private\x18( \x01(\v2\x11.standards.v23.CPR\x13roomRateSemiPrivate\x12=\n" +
	"\x11room_rate_private\x18) \x01(\v2\x11.standards.v23.CPR\x0froomRatePrivate\x12M\n" +
	"\x19insured_employment_status\x18* \x01(\v2\x11.standards.v23.CER\x17insuredEmploymentStatus\x12\x1f\n" +
	"\vinsured_sex\x18+ \x01(\tR\n" +
	"insuredSex\x12L\n" +
	"\x18insured_employer_address\x18, \x01(\v2\x12.standards.v23.XADR\x16insuredEmployerAddress\x12/\n" +
	"\x13verification_status\x18- \x01(\tR\x12verificationStatus\x127\n" +
	"\x18prior_insturance_plan_id\x18. \x01(\tR\x15priorInsturancePlanId\x12#\n" +
	"\rcoverage_type\x18/ \x01(\tR\fcoverageType\x12\x1a\n" +
	"\bhandicap\x180 \x01(\tR\bhandicap\x12=\n" +
	"\x11insured_id_number\x181 \x01(\v2\x11.standards.v23.CXR\x0finsuredIdNumber\"\x9a \n" +
	"\x03IN2\x12A\n" +
	"\x13insured_employee_id\x18\x01 \x01(\v2\x11.standards.v23.CXR\x11insuredEmployeeId\x12\x1f\n" +
	"\vinsured_ssn\x18\x02 \x01(\tR\n" +
	"insuredSsn\x12F\n" +
	"\x15insured_employer_name\x18\x03 \x01(\v2\x12.standards.v23.XCNR\x13insuredEmployerName\x12:\n" +
	"\x19employer_information_data\x18\x04 \x01(\tR\x17employerInformationData\x12(\n" +
	"\x10mail_claim_party\x18\x05 \x01(\tR\x0emailClaimParty\x120\n" +
	"\x14medicare_card_number\x18\x06 \x01(\tR\x12medicareCardNumber\x12@\n" +
	"\x12medicaid_case_name\x18\a \x01(\v2\x12.standards.v23.XPNR\x10medicaidCaseName\x120\n" +
	"\x14medicaid_case_number\x18\b \x01(\tR\x12medicaidCaseNumber\x12B\n" +
	"\x13champu_sponsor_name\x18\t \x01(\v2\x12.standards.v23.XPNR\x11champuSponsorName\x12*\n" +
	"\x11champus_id_number\x18\n" +
	" \x01(\tR\x0fchampusIdNumber\x12Q\n" +
	"\x1bchampus_dependent_recipient\x18\v \x01(\v2\x11.standards.v23.CER\x19champusDependentRecipient\x121\n" +
	"\x14champus_organization\x18\f \x01(\tR\x13champusOrganization\x12'\n" +
	"\x0fchampus_station\x18\r \x01(\tR\x0echampusStation\x12'\n" +
	"\x0fchampus_service\x18\x0e \x01(\tR\x0echampusService\x12!\n" +
	"\fchampus_rank\x18\x0f \x01(\tR\vchampusRank\x12%\n" +
	"\x0echampus_status\x18\x10 \x01(\tR\rchampusStatus\x12.\n" +
	"\x13champus_retire_date\x18\x11 \x01(\tR\x11champusRetireDate\x12A\n" +
	"\x1echampus_non_avail_cert_on_file\x18\x12 \x01(\tR\x19champusNonAvailCertOnFile\x12#\n" +
	"\rbaby_coverage\x18\x13 \x01(\tR\fbabyCoverage\x12*\n" +
	"\x11combine_baby_bill\x18\x14 \x01(\tR\x0fcombineBabyBill\x12)\n" +
	"\x10blood_deductible\x18\x15 \x01(\tR\x0fbloodDeductible\x12W\n" +
	"\x1especial_coverage_approval_name\x18\x16 \x01(\v2\x12.standards.v23.XPNR\x1bspecialCoverageApprovalName\x12E\n" +
	"\x1fspecial_coverage_approval_title\x18\x17 \x01(\tR\x1cspecialCoverageApprovalTitle\x12:\n" +
	"\x19noncovered_insurance_code\x18\x18 \x01(\tR\x17noncoveredInsuranceCode\x12,\n" +
	"\bpayor_id\x18\x19 \x01(\v2\x11.standards.v23.CXR\apayorId\x12A\n" +
	"\x13payor_subscriber_id\x18\x1a \x01(\v2\x11.standards.v23.CXR\x11payorSubscriberId\x12-\n" +
	"\x12eligibility_source\x18\x1b \x01(\tR\x11eligibilitySource\x12B\n" +
	"\x12room_coverage_type\x18\x1c \x01(\v2\x14.standards.v23.CMPLTR\x10roomCoverageType\x125\n" +
	"\vpolicy_type\x18\x1d \x01(\v2\x14.standards.v23.CMPLTR\n" +
	"policyType\x12?\n" +
	"\x10daily_deductible\x18\x1e \x01(\v2\x14.standards.v23.CMDDER\x0fdailyDeductible\x12+\n" +
	"\x11living_dependency\x18\x1f \x01(\tR\x10livingDependency\x12+\n" +
	"\x11ambulatory_status\x18  \x01(\tR\x10ambulatoryStatus\x12 \n" +
	"\vcitizenship\x18! \x01(\tR\vcitizenship\x12<\n" +
	"\x10primary_language\x18\" \x01(\v2\x11.standards.v23.CER\x0fprimaryLanguage\x12-\n" +
	"\x12living_arrangement\x18# \x01(\tR\x11livingArrangement\x12B\n" +
	"\x13publicity_indicator\x18$ \x01(\v2\x11.standards.v23.CER\x12publicityIndicator\x121\n" +
	"\x14protection_indicator\x18% \x01(\tR\x13protectionIndicator\x12+\n" +
	"\x11student_indicator\x18& \x01(\tR\x10studentIndicator\x12\x1a\n" +
	"\breligion\x18' \x01(\tR\breligion\x12@\n" +
	"\x12mother_maiden_name\x18( \x01(\v2\x12.standards.v23.XPNR\x10motherMaidenName\x123\n" +
	"\vnationality\x18) \x01(\v2\x11.standards.v23.CER\vnationality\x12!\n" +
	"\fethnic_group\x18* \x01(\tR\vethnicGroup\x12%\n" +
	"\x0emarital_status\x18+ \x01(\tR\rmaritalStatus\x12A\n" +
	"\x1dinsured_employment_start_date\x18, \x01(\tR\x1ainsuredEmploymentStartDate\x12?\n" +
	"\x1cinsured_employment_stop_date\x18- \x01(\tR\x19insuredEmploymentStopDate\x12\x1b\n" +
	"\tjob_title\x18. \x01(\tR\bjobTitle\x12-\n" +
	"\bjob_code\x18/ \x01(\v2\x12.standards.v23.JCCR\ajobCode\x12\x1d\n" +
	"\n" +
	"job_status\x180 \x01(\tR\tjobStatus\x12F\n" +
	"\x15employer_contact_name\x181 \x01(\v2\x12.standards.v23.XPNR\x13employerContactName\x12U\n" +
	"\x1demployer_contact_phone_number\x182 \x01(\v2\x12.standards.v23.XTNR\x1aemployerContactPhoneNumber\x126\n" +
	"\x17employer_contact_reason\x183 \x01(\tR\x15employerContactReason\x12D\n" +
	"\x14insured_contact_name\x184 \x01(\v2\x12.standards.v23.XPNR\x12insuredContactName\x12S\n" +
	"\x1cinsured_contact_phone_numbet\x185 \x01(\v2\x12.standards.v23.XTNR\x19insuredContactPhoneNumbet\x124\n" +
	"\x16insured_contact_reason\x186 \x01(\tR\x14insuredContactReason\x12J\n" +
	"\"relationship_to_patient_start_date\x187 \x01(\tR\x1erelationshipToPatientStartDate\x12H\n" +
	"!relationship_to_patient_stop_date\x188 \x01(\tR\x1drelationshipToPatientStopDate\x12G\n" +
	" insurance_company_contact_reason\x189 \x01(\tR\x1dinsuranceCompanyContactReason\x12f\n" +
	"&insurance_company_contact_phone_number\x18: \x01(\v2\x12.standards.v23.XTNR\"insuranceCompanyContactPhoneNumber\x12!\n" +
	"\fpolicy_scope\x18; \x01(\tR\vpolicyScope\x12#\n" +
	"\rpolicy_source\x18< \x01(\tR\fpolicySource\x12E\n" +
	"\x15patient_member_number\x18= \x01(\v2\x11.standards.v23.CXR\x13patientMemberNumber\x125\n" +
	"\x16guarantor_relationship\x18> \x01(\tR\x15guarantorRelationship\x12M\n" +
	"\x19insured_home_phone_number\x18? \x01(\v2\x12.standards.v23.XTNR\x16insuredHomePhoneNumber\x12K\n" +
	"\x18insured_home_work_number\x18@ \x01(\v2\x12.standards.v23.XTNR\x15insuredHomeWorkNumber\x12S\n" +
	"\x1cmilitary_handicapped_program\x18A \x01(\v2\x11.standards.v23.CER\x1amilitaryHandicappedProgram\x12!\n" +
	"\fsuspend_flag\x18B \x01(\tR\vsuspendFlag\x12(\n" +
	"\x10copay_limit_flag\x18C \x01(\tR\x0ecopayLimitFlag\x12.\n" +
	"\x13stoploss_limit_flag\x18D \x01(\tR\x11stoplossLimitFlag\x12N\n" +
	"\x19insured_organization_name\x18E \x01(\v2\x12.standards.v23.XONR\x17insuredOrganizationName\x12_\n" +
	"\"insured_employer_organization_name\x18F \x01(\v2\x12.standards.v23.XONR\x1finsuredEmployerOrganizationName\x12\x12\n" +
	"\x04race\x18G \x01(\tR\x04race\x12a\n" +
	"$hcfa_patient_relationship_to_insured\x18H \x01(\v2\x11.standards.v23.CER hcfaPatientRelationshipToInsured\"\x94\f\n" +
	"\x03IN3\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12D\n" +
	"\x14certification_number\x18\x02 \x01(\v2\x11.standards.v23.CXR\x13certificationNumber\x125\n" +
	"\fcertified_by\x18\x03 \x01(\v2\x12.standards.v23.XCNR\vcertifiedBy\x125\n" +
	"\x16certification_required\x18\x04 \x01(\tR\x15certificationRequired\x12.\n" +
	"\apenalty\x18\x05 \x01(\v2\x14.standards.v23.CMVALR\apenalty\x126\n" +
	"\x17certification_date_time\x18\x06 \x01(\tR\x15certificationDateTime\x12G\n" +
	" certification_modality_date_time\x18\a \x01(\tR\x1dcertificationModalityDateTime\x12.\n" +
	"\boperator\x18\b \x01(\v2\x12.standards.v23.XCNR\boperator\x128\n" +
	"\x18certification_begin_date\x18\t \x01(\tR\x16certificationBeginDate\x124\n" +
	"\x16certification_end_date\x18\n" +
	" \x01(\tR\x14certificationEndDate\x12(\n" +
	"\x04days\x18\v \x01(\v2\x14.standards.v23.CMVALR\x04days\x12P\n" +
	"\x1bnon_concur_code_description\x18\f \x01(\v2\x11.standards.v23.CER\x18nonConcurCodeDescription\x12B\n" +
	"\x1enon_concur_effective_date_time\x18\r \x01(\tR\x1anonConcurEffectiveDateTime\x12A\n" +
	"\x12physician_reviewer\x18\x0e \x01(\v2\x12.standards.v23.XCNR\x11physicianReviewer\x123\n" +
	"\x15certification_contact\x18\x0f \x01(\tR\x14certificationContact\x12_\n" +
	"\"certification_contact_phone_number\x18\x10 \x01(\v2\x12.standards.v23.XTNR\x1fcertificationContactPhoneNumber\x126\n" +
	"\rappeal_reason\x18\x11 \x01(\v2\x11.standards.v23.CER\fappealReason\x12D\n" +
	"\x14certification_agency\x18\x12 \x01(\v2\x11.standards.v23.CER\x13certificationAgency\x12]\n" +
	"!certification_agency_phone_number\x18\x13 \x01(\v2\x12.standards.v23.XTNR\x1ecertificationAgencyPhoneNumber\x12S\n" +
	"\x1bpre_cert_requirement_window\x18\x14 \x01(\v2\x14.standards.v23.CMPCRR\x18preCertRequirementWindow\x12!\n" +
	"\fcase_manager\x18\x15 \x01(\tR\vcaseManager\x12.\n" +
	"\x13second_opinion_date\x18\x16 \x01(\tR\x11secondOpinionDate\x122\n" +
	"\x15second_opinion_status\x18\x17 \x01(\tR\x13secondOpinionStatus\x12Q\n" +
	"%second_opinion_documentation_received\x18\x18 \x01(\tR\"secondOpinionDocumentationReceived\x12L\n" +
	"\x18second_opinion_physician\x18\x19 \x01(\v2\x12.standards.v23.XCNR\x16secondOpinionPhysician\"\xf2\x06\n" +
	"\x03DG1\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12#\n" +
	"\rcoding_method\x18\x02 \x01(\tR\fcodingMethod\x12%\n" +
	"\x04code\x18\x03 \x01(\v2\x11.standards.v23.CER\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdate_time\x18\x05 \x01(\tR\bdateTime\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12M\n" +
	"\x19major_diagnostic_category\x18\a \x01(\v2\x11.standards.v23.CER\x17majorDiagnosticCategory\x12K\n" +
	"\x18diagnostic_related_group\x18\b \x01(\v2\x11.standards.v23.CER\x16diagnosticRelatedGroup\x124\n" +
	"\x16drg_approval_indicator\x18\t \x01(\tR\x14drgApprovalIndicator\x125\n" +
	"\x17drg_grouper_review_code\x18\n" +
	" \x01(\tR\x14drgGrouperReviewCode\x124\n" +
	"\foutlier_type\x18\v \x01(\v2\x11.standards.v23.CER\voutlierType\x12!\n" +
	"\foutlier_days\x18\f \x01(\tR\voutlierDays\x124\n" +
	"\foutlier_cost\x18\r \x01(\v2\x11.standards.v23.CPR\voutlierCost\x12'\n" +
	"\x0fgoruper_version\x18\x0e \x01(\tR\x0egoruperVersion\x12\x1a\n" +
	"\bpriority\x18\x0f \x01(\tR\bpriority\x12E\n" +
	"\x14diagnosing_clinician\x18\x10 \x01(\v2\x12.standards.v23.XCNR\x13diagnosingClinician\x12&\n" +
	"\x0eclassification\x18\x11 \x01(\tR\x0eclassification\x125\n" +
	"\x16confidential_indicator\x18\x12 \x01(\tR\x15confidentialIndicator\x122\n" +
	"\x15attestation_date_time\x18\x13 \x01(\tR\x13attestationDateTimeB1Z/github.com/s-hammon/hl7/proto/standards/v23;v23b\x06proto3"

var (
	file_standards_v23_financial_proto_rawDescOnce sync.Once
	file_standards_v23_financial_proto_rawDescData []byte
)

func file_standards_v23_financial_proto_rawDescGZIP() []byte {
	file_standards_v23_financial_proto_rawDescOnce.Do(func() {
		file_standards_v23_financial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_v23_financial_proto_rawDesc), len(file_standards_v23_financial_proto_rawDesc)))
	})
	return file_standards_v23_financial_proto_rawDescData
}

var file_standards_v23_financial_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_standards_v23_financial_proto_goTypes = []any{
	(*GT1)(nil),   // 0: standards.v23.GT1
	(*IN1)(nil),   // 1: standards.v23.IN1
	(*IN2)(nil),   // 2: standards.v23.IN2
	(*IN3)(nil),   // 3: standards.v23.IN3
	(*DG1)(nil),   // 4: standards.v23.DG1
	(*CX)(nil),    // 5: standards.v23.CX
	(*XPN)(nil),   // 6: standards.v23.XPN
	(*XAD)(nil),   // 7: standards.v23.XAD
	(*XTN)(nil),   // 8: standards.v23.XTN
	(*XON)(nil),   // 9: standards.v23.XON
	(*CE)(nil),    // 10: standards.v23.CE
	(*CP)(nil),    // 11: standards.v23.CP
	(*JCC)(nil),   // 12: standards.v23.JCC
	(*FC)(nil),    // 13: standards.v23.FC
	(*CMAUI)(nil), // 14: standards.v23.CMAUI
	(*XCN)(nil),   // 15: standards.v23.XCN
	(*CMPLT)(nil), // 16: standards.v23.CMPLT
	(*CMDDE)(nil), // 17: standards.v23.CMDDE
	(*CMVAL)(nil), // 18: standards.v23.CMVAL
	(*CMPCR)(nil), // 19: standards.v23.CMPCR
}
var file_standards_v23_financial_proto_depIdxs = []int32{
	5,  // 0: standards.v23.GT1.guarantor_number:type_name -> standards.v23.CX
	6,  // 1: standards.v23.GT1.name:type_name -> standards.v23.XPN
	6,  // 2: standards.v23.GT1.spouse_name:type_name -> standards.v23.XPN
	7,  // 3: standards.v23.GT1.address:type_name -> standards.v23.XAD
	8,  // 4: standards.v23.GT1.home_phone_number:type_name -> standards.v23.XTN
	8,  // 5: standards.v23.GT1.work_phone_number:type_name -> standards.v23.XTN
	6,  // 6: standards.v23.GT1.employer_name:type_name -> standards.v23.XPN
	7,  // 7: standards.v23.GT1.employer_address:type_name -> standards.v23.XAD
	8,  // 8: standards.v23.GT1.employer_phone_number:type_name -> standards.v23.XTN
	5,  // 9: standards.v23.GT1.employee_id_number:type_name -> standards.v23.CX
	9,  // 10: standards.v23.GT1.organization_name:type_name -> standards.v23.XON
	10, // 11: standards.v23.GT1.credit_rating_code:type_name -> standards.v23.CE
	10, // 12: standards.v23.GT1.charge_adjustment_code:type_name -> standards.v23.CE
	11, // 13: standards.v23.GT1.household_annual_income:type_name -> standards.v23.CP
	5,  // 14: standards.v23.GT1.employer_id_number:type_name -> standards.v23.CX
	10, // 15: standards.v23.GT1.primary_language:type_name -> standards.v23.CE
	10, // 16: standards.v23.GT1.publicity_indicator:type_name -> standards.v23.CE
	6,  // 17: standards.v23.GT1.mother_maiden_name:type_name -> standards.v23.XPN
	10, // 18: standards.v23.GT1.nationality:type_name -> standards.v23.CE
	6,  // 19: standards.v23.GT1.contact_name:type_name -> standards.v23.XPN
	8,  // 20: standards.v23.GT1.contact_phone_number:type_name -> standards.v23.XTN
	10, // 21: standards.v23.GT1.contact_reason:type_name -> standards.v23.CE
	12, // 22: standards.v23.GT1.job_code:type_name -> standards.v23.JCC
	9,  // 23: standards.v23.GT1.employer_organization_name:type_name -> standards.v23.XON
	13, // 24: standards.v23.GT1.financial_class:type_name -> standards.v23.FC
	10, // 25: standards.v23.IN1.plan_id:type_name -> standards.v23.CE
	5,  // 26: standards.v23.IN1.company_id:type_name -> standards.v23.CX
	9,  // 27: standards.v23.IN1.company_name:type_name -> standards.v23.XON
	7,  // 28: standards.v23.IN1.company_address:type_name -> standards.v23.XAD
	6,  // 29: standards.v23.IN1.company_contact:type_name -> standards.v23.XPN
	8,  // 30: standards.v23.IN1.company_phone_number:type_name -> standards.v23.XTN
	9,  // 31: standards.v23.IN1.group_name:type_name -> standards.v23.XON
	5,  // 32: standards.v23.IN1.group_employer_id:type_name -> standards.v23.CX
	9,  // 33: standards.v23.IN1.group_employer_name:type_name -> standards.v23.XON
	14, // 34: standards.v23.IN1.authorization_information:type_name -> standards.v23.CMAUI
	6,  // 35: standards.v23.IN1.insured_name:type_name -> standards.v23.XPN
	7,  // 36: standards.v23.IN1.insured_address:type_name -> standards.v23.XAD
	15, // 37: standards.v23.IN1.verification_by:type_name -> standards.v23.XCN
	11, // 38: standards.v23.IN1.policy_deductible:type_name -> standards.v23.CP
	11, // 39: standards.v23.IN1.policy_limit_amount:type_name -> standards.v23.CP
	11, // 40: standards.v23.IN1.room_rate_semi_private:type_name -> standards.v23.CP
	11, // 41: standards.v23.IN1.room_rate_private:type_name -> standards.v23.CP
	10, // 42: standards.v23.IN1.insured_employment_status:type_name -> standards.v23.CE
	7,  // 43: standards.v23.IN1.insured_employer_address:type_name -> standards.v23.XAD
	5,  // 44: standards.v23.IN1.insured_id_number:type_name -> standards.v23.CX
	5,  // 45: standards.v23.IN2.insured_employee_id:type_name -> standards.v23.CX
	15, // 46: standards.v23.IN2.insured_employer_name:type_name -> standards.v23.XCN
	6,  // 47: standards.v23.IN2.medicaid_case_name:type_name -> standards.v23.XPN
	6,  // 48: standards.v23.IN2.champu_sponsor_name:type_name -> standards.v23.XPN
	10, // 49: standards.v23.IN2.champus_dependent_recipient:type_name -> standards.v23.CE
	6,  // 50: standards.v23.IN2.special_coverage_approval_name:type_name -> standards.v23.XPN
	5,  // 51: standards.v23.IN2.payor_id:type_name -> standards.v23.CX
	5,  // 52: standards.v23.IN2.payor_subscriber_id:type_name -> standards.v23.CX
	16, // 53: standards.v23.IN2.room_coverage_type:type_name -> standards.v23.CMPLT
	16, // 54: standards.v23.IN2.policy_type:type_name -> standards.v23.CMPLT
	17, // 55: standards.v23.IN2.daily_deductible:type_name -> standards.v23.CMDDE
	10, // 56: standards.v23.IN2.primary_language:type_name -> standards.v23.CE
	10, // 57: standards.v23.IN2.publicity_indicator:type_name -> standards.v23.CE
	6,  // 58: standards.v23.IN2.mother_maiden_name:type_name -> standards.v23.XPN
	10, // 59: standards.v23.IN2.nationality:type_name -> standards.v23.CE
	12, // 60: standards.v23.IN2.job_code:type_name -> standards.v23.JCC
	6,  // 61: standards.v23.IN2.employer_contact_name:type_name -> standards.v23.XPN
	8,  // 62: standards.v23.IN2.employer_contact_phone_number:type_name -> standards.v23.XTN
	6,  // 63: standards.v23.IN2.insured_contact_name:type_name -> standards.v23.XPN
	8,  // 64: standards.v23.IN2.insured_contact_phone_numbet:type_name -> standards.v23.XTN
	8,  // 65: standards.v23.IN2.insurance_company_contact_phone_number:type_name -> standards.v23.XTN
	5,  // 66: standards.v23.IN2.patient_member_number:type_name -> standards.v23.CX
	8,  // 67: standards.v23.IN2.insured_home_phone_number:type_name -> standards.v23.XTN
	8,  // 68: standards.v23.IN2.insured_home_work_number:type_name -> standards.v23.XTN
	10, // 69: standards.v23.IN2.military_handicapped_program:type_name -> standards.v23.CE
	9,  // 70: standards.v23.IN2.insured_organization_name:type_name -> standards.v23.XON
	9,  // 71: standards.v23.IN2.insured_employer_organization_name:type_name -> standards.v23.XON
	10, // 72: standards.v23.IN2.hcfa_patient_relationship_to_insured:type_name -> standards.v23.CE
	5,  // 73: standards.v23.IN3.certification_number:type_name -> standards.v23.CX
	15, // 74: standards.v23.IN3.certified_by:type_name -> standards.v23.XCN
	18, // 75: standards.v23.IN3.penalty:type_name -> standards.v23.CMVAL
	15, // 76: standards.v23.IN3.operator:type_name -> standards.v23.XCN
	18, // 77: standards.v23.IN3.days:type_name -> standards.v23.CMVAL
	10, // 78: standards.v23.IN3.non_concur_code_description:type_name -> standards.v23.CE
	15, // 79: standards.v23.IN3.physician_reviewer:type_name -> standards.v23.XCN
	8,  // 80: standards.v23.IN3.certification_contact_phone_number:type_name -> standards.v23.XTN
	10, // 81: standards.v23.IN3.appeal_reason:type_name -> standards.v23.CE
	10, // 82: standards.v23.IN3.certification_agency:type_name -> standards.v23.CE
	8,  // 83: standards.v23.IN3.certification_agency_phone_number:type_name -> standards.v23.XTN
	19, // 84: standards.v23.IN3.pre_cert_requirement_window:type_name -> standards.v23.CMPCR
	15, // 85: standards.v23.IN3.second_opinion_physician:type_name -> standards.v23.XCN
	10, // 86: standards.v23.DG1.code:type_name -> standards.v23.CE
	10, // 87: standards.v23.DG1.major_diagnostic_category:type_name -> standards.v23.CE
	10, // 88: standards.v23.DG1.diagnostic_related_group:type_name -> standards.v23.CE
	10, // 89: standards.v23.DG1.outlier_type:type_name -> standards.v23.CE
	11, // 90: standards.v23.DG1.outlier_cost:type_name -> standards.v23.CP
	15, // 91: standards.v23.DG1.diagnosing_clinician:type_name -> standards.v23.XCN
	92, // [92:92] is the sub-list for method output_type
	92, // [92:92] is the sub-list for method input_type
	92, // [92:92] is the sub-list for extension type_name
	92, // [92:92] is the sub-list for extension extendee
	0,  // [0:92] is the sub-list for field type_name
}

func init() { file_standards_v23_financial_proto_init() }
func file_standards_v23_financial_proto_init() {
	if File_standards_v23_financial_proto != nil {
		return
	}
	file_standards_v23_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_v23_financial_proto_rawDesc), len(file_standards_v23_financial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_v23_financial_proto_goTypes,
		DependencyIndexes: file_standards_v23_financial_proto_depIdxs,
		MessageInfos:      file_standards_v23_financial_proto_msgTypes,
	}.Build()
	File_standards_v23_financial_proto = out.File
	file_standards_v23_financial_proto_goTypes = nil
	file_standards_v23_financial_proto_depIdxs = nil
}
