// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: standards/v23/groups.proto

package v23

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatientGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PID           *PID                   `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	PD1           *PD1                   `protobuf:"bytes,2,opt,name=PD1,proto3" json:"PD1,omitempty"`
	Visit         *PatientVisitGroup     `protobuf:"bytes,3,opt,name=visit,proto3" json:"visit,omitempty"`
	Insurance     []*InsuranceGroup      `protobuf:"bytes,4,rep,name=insurance,proto3" json:"insurance,omitempty"`
	GT1           *GT1                   `protobuf:"bytes,5,opt,name=GT1,proto3" json:"GT1,omitempty"`
	AL1           []*AL1                 `protobuf:"bytes,6,rep,name=AL1,proto3" json:"AL1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientGroup) Reset() {
	*x = PatientGroup{}
	mi := &file_standards_v23_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientGroup) ProtoMessage() {}

func (x *PatientGroup) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientGroup.ProtoReflect.Descriptor instead.
func (*PatientGroup) Descriptor() ([]byte, []int) {
	return file_standards_v23_groups_proto_rawDescGZIP(), []int{0}
}

func (x *PatientGroup) GetPID() *PID {
	if x != nil {
		return x.PID
	}
	return nil
}

func (x *PatientGroup) GetPD1() *PD1 {
	if x != nil {
		return x.PD1
	}
	return nil
}

func (x *PatientGroup) GetVisit() *PatientVisitGroup {
	if x != nil {
		return x.Visit
	}
	return nil
}

func (x *PatientGroup) GetInsurance() []*InsuranceGroup {
	if x != nil {
		return x.Insurance
	}
	return nil
}

func (x *PatientGroup) GetGT1() *GT1 {
	if x != nil {
		return x.GT1
	}
	return nil
}

func (x *PatientGroup) GetAL1() []*AL1 {
	if x != nil {
		return x.AL1
	}
	return nil
}

type PatientVisitGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PV1           *PV1                   `protobuf:"bytes,1,opt,name=PV1,proto3" json:"PV1,omitempty"`
	PV2           *PV2                   `protobuf:"bytes,2,opt,name=PV2,proto3" json:"PV2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientVisitGroup) Reset() {
	*x = PatientVisitGroup{}
	mi := &file_standards_v23_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientVisitGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientVisitGroup) ProtoMessage() {}

func (x *PatientVisitGroup) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientVisitGroup.ProtoReflect.Descriptor instead.
func (*PatientVisitGroup) Descriptor() ([]byte, []int) {
	return file_standards_v23_groups_proto_rawDescGZIP(), []int{1}
}

func (x *PatientVisitGroup) GetPV1() *PV1 {
	if x != nil {
		return x.PV1
	}
	return nil
}

func (x *PatientVisitGroup) GetPV2() *PV2 {
	if x != nil {
		return x.PV2
	}
	return nil
}

type InsuranceGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IN1           *IN1                   `protobuf:"bytes,1,opt,name=IN1,proto3" json:"IN1,omitempty"`
	IN2           *IN2                   `protobuf:"bytes,2,opt,name=IN2,proto3" json:"IN2,omitempty"`
	IN3           *IN3                   `protobuf:"bytes,3,opt,name=IN3,proto3" json:"IN3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsuranceGroup) Reset() {
	*x = InsuranceGroup{}
	mi := &file_standards_v23_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsuranceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsuranceGroup) ProtoMessage() {}

func (x *InsuranceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsuranceGroup.ProtoReflect.Descriptor instead.
func (*InsuranceGroup) Descriptor() ([]byte, []int) {
	return file_standards_v23_groups_proto_rawDescGZIP(), []int{2}
}

func (x *InsuranceGroup) GetIN1() *IN1 {
	if x != nil {
		return x.IN1
	}
	return nil
}

func (x *InsuranceGroup) GetIN2() *IN2 {
	if x != nil {
		return x.IN2
	}
	return nil
}

func (x *InsuranceGroup) GetIN3() *IN3 {
	if x != nil {
		return x.IN3
	}
	return nil
}

type OrderGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ORC           *ORC                   `protobuf:"bytes,1,opt,name=ORC,proto3" json:"ORC,omitempty" hl7:"ORC,required"` // @gotags: hl7:"ORC,required"
	Details       *OrderDetailGroup      `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGroup) Reset() {
	*x = OrderGroup{}
	mi := &file_standards_v23_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGroup) ProtoMessage() {}

func (x *OrderGroup) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGroup.ProtoReflect.Descriptor instead.
func (*OrderGroup) Descriptor() ([]byte, []int) {
	return file_standards_v23_groups_proto_rawDescGZIP(), []int{3}
}

func (x *OrderGroup) GetORC() *ORC {
	if x != nil {
		return x.ORC
	}
	return nil
}

func (x *OrderGroup) GetDetails() *OrderDetailGroup {
	if x != nil {
		return x.Details
	}
	return nil
}

type OrderDetailGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: hl7:"OBR,required"
	OBR *OBR `protobuf:"bytes,1,opt,name=OBR,proto3" json:"OBR,omitempty" hl7:"OBR,required"`
	// @gotags: hl7:"NTE"
	NTE []*NTE `protobuf:"bytes,2,rep,name=NTE,proto3" json:"NTE,omitempty" hl7:"NTE"`
	// @gotags: hl7:"DG1"
	DG1 []*DG1 `protobuf:"bytes,3,rep,name=DG1,proto3" json:"DG1,omitempty" hl7:"DG1"`
	// @gotags: hl7:"group"
	ObservationGroup []*ObservationGroup `protobuf:"bytes,4,rep,name=observation_group,json=observationGroup,proto3" json:"observation_group,omitempty" hl7:"group"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderDetailGroup) Reset() {
	*x = OrderDetailGroup{}
	mi := &file_standards_v23_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailGroup) ProtoMessage() {}

func (x *OrderDetailGroup) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailGroup.ProtoReflect.Descriptor instead.
func (*OrderDetailGroup) Descriptor() ([]byte, []int) {
	return file_standards_v23_groups_proto_rawDescGZIP(), []int{4}
}

func (x *OrderDetailGroup) GetOBR() *OBR {
	if x != nil {
		return x.OBR
	}
	return nil
}

func (x *OrderDetailGroup) GetNTE() []*NTE {
	if x != nil {
		return x.NTE
	}
	return nil
}

func (x *OrderDetailGroup) GetDG1() []*DG1 {
	if x != nil {
		return x.DG1
	}
	return nil
}

func (x *OrderDetailGroup) GetObservationGroup() []*ObservationGroup {
	if x != nil {
		return x.ObservationGroup
	}
	return nil
}

type ObservationGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: hl7:"OBX,required"
	OBX *OBX `protobuf:"bytes,1,opt,name=OBX,proto3" json:"OBX,omitempty" hl7:"OBX,required"`
	// @gotags: hl7:"NTE"
	NTE           []*NTE `protobuf:"bytes,2,rep,name=NTE,proto3" json:"NTE,omitempty" hl7:"NTE"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservationGroup) Reset() {
	*x = ObservationGroup{}
	mi := &file_standards_v23_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationGroup) ProtoMessage() {}

func (x *ObservationGroup) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationGroup.ProtoReflect.Descriptor instead.
func (*ObservationGroup) Descriptor() ([]byte, []int) {
	return file_standards_v23_groups_proto_rawDescGZIP(), []int{5}
}

func (x *ObservationGroup) GetOBX() *OBX {
	if x != nil {
		return x.OBX
	}
	return nil
}

func (x *ObservationGroup) GetNTE() []*NTE {
	if x != nil {
		return x.NTE
	}
	return nil
}

type ResultGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PID           *PID                   `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty" hl7:"PID,required"` // @gotags: hl7:"PID,required"
	PD1           *PD1                   `protobuf:"bytes,2,opt,name=PD1,proto3" json:"PD1,omitempty"`
	NTE           []*NTE                 `protobuf:"bytes,3,rep,name=NTE,proto3" json:"NTE,omitempty"`
	Visit         *PatientVisitGroup     `protobuf:"bytes,4,opt,name=visit,proto3" json:"visit,omitempty"`
	Order         []*ObsOrderGroup       `protobuf:"bytes,5,rep,name=order,proto3" json:"order,omitempty" hl7:"group"` // @gotags: hl7:"group"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultGroup) Reset() {
	*x = ResultGroup{}
	mi := &file_standards_v23_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultGroup) ProtoMessage() {}

func (x *ResultGroup) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultGroup.ProtoReflect.Descriptor instead.
func (*ResultGroup) Descriptor() ([]byte, []int) {
	return file_standards_v23_groups_proto_rawDescGZIP(), []int{6}
}

func (x *ResultGroup) GetPID() *PID {
	if x != nil {
		return x.PID
	}
	return nil
}

func (x *ResultGroup) GetPD1() *PD1 {
	if x != nil {
		return x.PD1
	}
	return nil
}

func (x *ResultGroup) GetNTE() []*NTE {
	if x != nil {
		return x.NTE
	}
	return nil
}

func (x *ResultGroup) GetVisit() *PatientVisitGroup {
	if x != nil {
		return x.Visit
	}
	return nil
}

func (x *ResultGroup) GetOrder() []*ObsOrderGroup {
	if x != nil {
		return x.Order
	}
	return nil
}

type ObsPatientGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PID           *PID                   `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty" hl7:"PID,required"` // @gotags: hl7:"PID,required"
	PD1           *PD1                   `protobuf:"bytes,2,opt,name=PD1,proto3" json:"PD1,omitempty"`
	NTE           []*NTE                 `protobuf:"bytes,3,rep,name=NTE,proto3" json:"NTE,omitempty"`
	Visit         *PatientVisitGroup     `protobuf:"bytes,4,opt,name=visit,proto3" json:"visit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObsPatientGroup) Reset() {
	*x = ObsPatientGroup{}
	mi := &file_standards_v23_groups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObsPatientGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObsPatientGroup) ProtoMessage() {}

func (x *ObsPatientGroup) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_groups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObsPatientGroup.ProtoReflect.Descriptor instead.
func (*ObsPatientGroup) Descriptor() ([]byte, []int) {
	return file_standards_v23_groups_proto_rawDescGZIP(), []int{7}
}

func (x *ObsPatientGroup) GetPID() *PID {
	if x != nil {
		return x.PID
	}
	return nil
}

func (x *ObsPatientGroup) GetPD1() *PD1 {
	if x != nil {
		return x.PD1
	}
	return nil
}

func (x *ObsPatientGroup) GetNTE() []*NTE {
	if x != nil {
		return x.NTE
	}
	return nil
}

func (x *ObsPatientGroup) GetVisit() *PatientVisitGroup {
	if x != nil {
		return x.Visit
	}
	return nil
}

type ObsOrderGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: hl7:"ORC,required"
	ORC *ORC `protobuf:"bytes,1,opt,name=ORC,proto3" json:"ORC,omitempty" hl7:"ORC,required"`
	// @gotags: hl7:"OBR,required"
	OBR *OBR   `protobuf:"bytes,2,opt,name=OBR,proto3" json:"OBR,omitempty" hl7:"OBR,required"`
	NTE []*NTE `protobuf:"bytes,3,rep,name=NTE,proto3" json:"NTE,omitempty"`
	// @gotags: hl7:"group"
	Observation   []*ObservationGroup `protobuf:"bytes,4,rep,name=observation,proto3" json:"observation,omitempty" hl7:"group"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObsOrderGroup) Reset() {
	*x = ObsOrderGroup{}
	mi := &file_standards_v23_groups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObsOrderGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObsOrderGroup) ProtoMessage() {}

func (x *ObsOrderGroup) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_groups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObsOrderGroup.ProtoReflect.Descriptor instead.
func (*ObsOrderGroup) Descriptor() ([]byte, []int) {
	return file_standards_v23_groups_proto_rawDescGZIP(), []int{8}
}

func (x *ObsOrderGroup) GetORC() *ORC {
	if x != nil {
		return x.ORC
	}
	return nil
}

func (x *ObsOrderGroup) GetOBR() *OBR {
	if x != nil {
		return x.OBR
	}
	return nil
}

func (x *ObsOrderGroup) GetNTE() []*NTE {
	if x != nil {
		return x.NTE
	}
	return nil
}

func (x *ObsOrderGroup) GetObservation() []*ObservationGroup {
	if x != nil {
		return x.Observation
	}
	return nil
}

var File_standards_v23_groups_proto protoreflect.FileDescriptor

const file_standards_v23_groups_proto_rawDesc = "" +
	"\n" +
	"\x1astandards/v23/groups.proto\x12\rstandards.v23\x1a\x1bstandards/v23/control.proto\x1a\"standards/v23/administration.proto\x1a\x1dstandards/v23/financial.proto\x1a\x19standards/v23/order.proto\x1a\x1fstandards/v23/observation.proto\"\x9b\x02\n" +
	"\fPatientGroup\x12$\n" +
	"\x03PID\x18\x01 \x01(\v2\x12.standards.v23.PIDR\x03PID\x12$\n" +
	"\x03PD1\x18\x02 \x01(\v2\x12.standards.v23.PD1R\x03PD1\x126\n" +
	"\x05visit\x18\x03 \x01(\v2 .standards.v23.PatientVisitGroupR\x05visit\x12;\n" +
	"\tinsurance\x18\x04 \x03(\v2\x1d.standards.v23.InsuranceGroupR\tinsurance\x12$\n" +
	"\x03GT1\x18\x05 \x01(\v2\x12.standards.v23.GT1R\x03GT1\x12$\n" +
	"\x03AL1\x18\x06 \x03(\v2\x12.standards.v23.AL1R\x03AL1\"_\n" +
	"\x11PatientVisitGroup\x12$\n" +
	"\x03PV1\x18\x01 \x01(\v2\x12.standards.v23.PV1R\x03PV1\x12$\n" +
	"\x03PV2\x18\x02 \x01(\v2\x12.standards.v23.PV2R\x03PV2\"\x82\x01\n" +
	"\x0eInsuranceGroup\x12$\n" +
	"\x03IN1\x18\x01 \x01(\v2\x12.standards.v23.IN1R\x03IN1\x12$\n" +
	"\x03IN2\x18\x02 \x01(\v2\x12.standards.v23.IN2R\x03IN2\x12$\n" +
	"\x03IN3\x18\x03 \x01(\v2\x12.standards.v23.IN3R\x03IN3\"m\n" +
	"\n" +
	"OrderGroup\x12$\n" +
	"\x03ORC\x18\x01 \x01(\v2\x12.standards.v23.ORCR\x03ORC\x129\n" +
	"\adetails\x18\x02 \x01(\v2\x1f.standards.v23.OrderDetailGroupR\adetails\"\xd2\x01\n" +
	"\x10OrderDetailGroup\x12$\n" +
	"\x03OBR\x18\x01 \x01(\v2\x12.standards.v23.OBRR\x03OBR\x12$\n" +
	"\x03NTE\x18\x02 \x03(\v2\x12.standards.v23.NTER\x03NTE\x12$\n" +
	"\x03DG1\x18\x03 \x03(\v2\x12.standards.v23.DG1R\x03DG1\x12L\n" +
	"\x11observation_group\x18\x04 \x03(\v2\x1f.standards.v23.ObservationGroupR\x10observationGroup\"^\n" +
	"\x10ObservationGroup\x12$\n" +
	"\x03OBX\x18\x01 \x01(\v2\x12.standards.v23.OBXR\x03OBX\x12$\n" +
	"\x03NTE\x18\x02 \x03(\v2\x12.standards.v23.NTER\x03NTE\"\xeb\x01\n" +
	"\vResultGroup\x12$\n" +
	"\x03PID\x18\x01 \x01(\v2\x12.standards.v23.PIDR\x03PID\x12$\n" +
	"\x03PD1\x18\x02 \x01(\v2\x12.standards.v23.PD1R\x03PD1\x12$\n" +
	"\x03NTE\x18\x03 \x03(\v2\x12.standards.v23.NTER\x03NTE\x126\n" +
	"\x05visit\x18\x04 \x01(\v2 .standards.v23.PatientVisitGroupR\x05visit\x122\n" +
	"\x05order\x18\x05 \x03(\v2\x1c.standards.v23.ObsOrderGroupR\x05order\"\xbb\x01\n" +
	"\x0fObsPatientGroup\x12$\n" +
	"\x03PID\x18\x01 \x01(\v2\x12.standards.v23.PIDR\x03PID\x12$\n" +
	"\x03PD1\x18\x02 \x01(\v2\x12.standards.v23.PD1R\x03PD1\x12$\n" +
	"\x03NTE\x18\x03 \x03(\v2\x12.standards.v23.NTER\x03NTE\x126\n" +
	"\x05visit\x18\x04 \x01(\v2 .standards.v23.PatientVisitGroupR\x05visit\"\xc4\x01\n" +
	"\rObsOrderGroup\x12$\n" +
	"\x03ORC\x18\x01 \x01(\v2\x12.standards.v23.ORCR\x03ORC\x12$\n" +
	"\x03OBR\x18\x02 \x01(\v2\x12.standards.v23.OBRR\x03OBR\x12$\n" +
	"\x03NTE\x18\x03 \x03(\v2\x12.standards.v23.NTER\x03NTE\x12A\n" +
	"\vobservation\x18\x04 \x03(\v2\x1f.standards.v23.ObservationGroupR\vobservationB1Z/github.com/s-hammon/hl7/proto/standards/v23;v23b\x06proto3"

var (
	file_standards_v23_groups_proto_rawDescOnce sync.Once
	file_standards_v23_groups_proto_rawDescData []byte
)

func file_standards_v23_groups_proto_rawDescGZIP() []byte {
	file_standards_v23_groups_proto_rawDescOnce.Do(func() {
		file_standards_v23_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_v23_groups_proto_rawDesc), len(file_standards_v23_groups_proto_rawDesc)))
	})
	return file_standards_v23_groups_proto_rawDescData
}

var file_standards_v23_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_standards_v23_groups_proto_goTypes = []any{
	(*PatientGroup)(nil),      // 0: standards.v23.PatientGroup
	(*PatientVisitGroup)(nil), // 1: standards.v23.PatientVisitGroup
	(*InsuranceGroup)(nil),    // 2: standards.v23.InsuranceGroup
	(*OrderGroup)(nil),        // 3: standards.v23.OrderGroup
	(*OrderDetailGroup)(nil),  // 4: standards.v23.OrderDetailGroup
	(*ObservationGroup)(nil),  // 5: standards.v23.ObservationGroup
	(*ResultGroup)(nil),       // 6: standards.v23.ResultGroup
	(*ObsPatientGroup)(nil),   // 7: standards.v23.ObsPatientGroup
	(*ObsOrderGroup)(nil),     // 8: standards.v23.ObsOrderGroup
	(*PID)(nil),               // 9: standards.v23.PID
	(*PD1)(nil),               // 10: standards.v23.PD1
	(*GT1)(nil),               // 11: standards.v23.GT1
	(*AL1)(nil),               // 12: standards.v23.AL1
	(*PV1)(nil),               // 13: standards.v23.PV1
	(*PV2)(nil),               // 14: standards.v23.PV2
	(*IN1)(nil),               // 15: standards.v23.IN1
	(*IN2)(nil),               // 16: standards.v23.IN2
	(*IN3)(nil),               // 17: standards.v23.IN3
	(*ORC)(nil),               // 18: standards.v23.ORC
	(*OBR)(nil),               // 19: standards.v23.OBR
	(*NTE)(nil),               // 20: standards.v23.NTE
	(*DG1)(nil),               // 21: standards.v23.DG1
	(*OBX)(nil),               // 22: standards.v23.OBX
}
var file_standards_v23_groups_proto_depIdxs = []int32{
	9,  // 0: standards.v23.PatientGroup.PID:type_name -> standards.v23.PID
	10, // 1: standards.v23.PatientGroup.PD1:type_name -> standards.v23.PD1
	1,  // 2: standards.v23.PatientGroup.visit:type_name -> standards.v23.PatientVisitGroup
	2,  // 3: standards.v23.PatientGroup.insurance:type_name -> standards.v23.InsuranceGroup
	11, // 4: standards.v23.PatientGroup.GT1:type_name -> standards.v23.GT1
	12, // 5: standards.v23.PatientGroup.AL1:type_name -> standards.v23.AL1
	13, // 6: standards.v23.PatientVisitGroup.PV1:type_name -> standards.v23.PV1
	14, // 7: standards.v23.PatientVisitGroup.PV2:type_name -> standards.v23.PV2
	15, // 8: standards.v23.InsuranceGroup.IN1:type_name -> standards.v23.IN1
	16, // 9: standards.v23.InsuranceGroup.IN2:type_name -> standards.v23.IN2
	17, // 10: standards.v23.InsuranceGroup.IN3:type_name -> standards.v23.IN3
	18, // 11: standards.v23.OrderGroup.ORC:type_name -> standards.v23.ORC
	4,  // 12: standards.v23.OrderGroup.details:type_name -> standards.v23.OrderDetailGroup
	19, // 13: standards.v23.OrderDetailGroup.OBR:type_name -> standards.v23.OBR
	20, // 14: standards.v23.OrderDetailGroup.NTE:type_name -> standards.v23.NTE
	21, // 15: standards.v23.OrderDetailGroup.DG1:type_name -> standards.v23.DG1
	5,  // 16: standards.v23.OrderDetailGroup.observation_group:type_name -> standards.v23.ObservationGroup
	22, // 17: standards.v23.ObservationGroup.OBX:type_name -> standards.v23.OBX
	20, // 18: standards.v23.ObservationGroup.NTE:type_name -> standards.v23.NTE
	9,  // 19: standards.v23.ResultGroup.PID:type_name -> standards.v23.PID
	10, // 20: standards.v23.ResultGroup.PD1:type_name -> standards.v23.PD1
	20, // 21: standards.v23.ResultGroup.NTE:type_name -> standards.v23.NTE
	1,  // 22: standards.v23.ResultGroup.visit:type_name -> standards.v23.PatientVisitGroup
	8,  // 23: standards.v23.ResultGroup.order:type_name -> standards.v23.ObsOrderGroup
	9,  // 24: standards.v23.ObsPatientGroup.PID:type_name -> standards.v23.PID
	10, // 25: standards.v23.ObsPatientGroup.PD1:type_name -> standards.v23.PD1
	20, // 26: standards.v23.ObsPatientGroup.NTE:type_name -> standards.v23.NTE
	1,  // 27: standards.v23.ObsPatientGroup.visit:type_name -> standards.v23.PatientVisitGroup
	18, // 28: standards.v23.ObsOrderGroup.ORC:type_name -> standards.v23.ORC
	19, // 29: standards.v23.ObsOrderGroup.OBR:type_name -> standards.v23.OBR
	20, // 30: standards.v23.ObsOrderGroup.NTE:type_name -> standards.v23.NTE
	5,  // 31: standards.v23.ObsOrderGroup.observation:type_name -> standards.v23.ObservationGroup
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_standards_v23_groups_proto_init() }
func file_standards_v23_groups_proto_init() {
	if File_standards_v23_groups_proto != nil {
		return
	}
	file_standards_v23_control_proto_init()
	file_standards_v23_administration_proto_init()
	file_standards_v23_financial_proto_init()
	file_standards_v23_order_proto_init()
	file_standards_v23_observation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_v23_groups_proto_rawDesc), len(file_standards_v23_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_v23_groups_proto_goTypes,
		DependencyIndexes: file_standards_v23_groups_proto_depIdxs,
		MessageInfos:      file_standards_v23_groups_proto_msgTypes,
	}.Build()
	File_standards_v23_groups_proto = out.File
	file_standards_v23_groups_proto_goTypes = nil
	file_standards_v23_groups_proto_depIdxs = nil
}
