// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: standards/v23/messages.proto

package v23

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ORM_O01 struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MSH          *MSH                   `protobuf:"bytes,1,opt,name=MSH,proto3" json:"MSH,omitempty"`
	NTE          *NTE                   `protobuf:"bytes,2,opt,name=NTE,proto3" json:"NTE,omitempty"`
	PatientGroup *PatientGroup          `protobuf:"bytes,3,opt,name=patient_group,json=patientGroup,proto3" json:"patient_group,omitempty"`
	// @gotags: hl7:"group"
	OrderGroups   []*OrderGroup `protobuf:"bytes,4,rep,name=order_groups,json=orderGroups,proto3" json:"order_groups,omitempty" hl7:"group"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ORM_O01) Reset() {
	*x = ORM_O01{}
	mi := &file_standards_v23_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ORM_O01) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ORM_O01) ProtoMessage() {}

func (x *ORM_O01) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ORM_O01.ProtoReflect.Descriptor instead.
func (*ORM_O01) Descriptor() ([]byte, []int) {
	return file_standards_v23_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ORM_O01) GetMSH() *MSH {
	if x != nil {
		return x.MSH
	}
	return nil
}

func (x *ORM_O01) GetNTE() *NTE {
	if x != nil {
		return x.NTE
	}
	return nil
}

func (x *ORM_O01) GetPatientGroup() *PatientGroup {
	if x != nil {
		return x.PatientGroup
	}
	return nil
}

func (x *ORM_O01) GetOrderGroups() []*OrderGroup {
	if x != nil {
		return x.OrderGroups
	}
	return nil
}

type ORU_R01 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MSH   *MSH                   `protobuf:"bytes,1,opt,name=MSH,proto3" json:"MSH,omitempty"`
	// @gotags: hl7:"group"
	Results       []*ResultGroup `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" hl7:"group"`
	DSC           *DSC           `protobuf:"bytes,3,opt,name=DSC,proto3" json:"DSC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ORU_R01) Reset() {
	*x = ORU_R01{}
	mi := &file_standards_v23_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ORU_R01) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ORU_R01) ProtoMessage() {}

func (x *ORU_R01) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ORU_R01.ProtoReflect.Descriptor instead.
func (*ORU_R01) Descriptor() ([]byte, []int) {
	return file_standards_v23_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ORU_R01) GetMSH() *MSH {
	if x != nil {
		return x.MSH
	}
	return nil
}

func (x *ORU_R01) GetResults() []*ResultGroup {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ORU_R01) GetDSC() *DSC {
	if x != nil {
		return x.DSC
	}
	return nil
}

var File_standards_v23_messages_proto protoreflect.FileDescriptor

const file_standards_v23_messages_proto_rawDesc = "" +
	"\n" +
	"\x1cstandards/v23/messages.proto\x12\rstandards.v23\x1a\x1bstandards/v23/control.proto\x1a\x1astandards/v23/groups.proto\"\xd5\x01\n" +
	"\aORM_O01\x12$\n" +
	"\x03MSH\x18\x01 \x01(\v2\x12.standards.v23.MSHR\x03MSH\x12$\n" +
	"\x03NTE\x18\x02 \x01(\v2\x12.standards.v23.NTER\x03NTE\x12@\n" +
	"\rpatient_group\x18\x03 \x01(\v2\x1b.standards.v23.PatientGroupR\fpatientGroup\x12<\n" +
	"\forder_groups\x18\x04 \x03(\v2\x19.standards.v23.OrderGroupR\vorderGroups\"\x8b\x01\n" +
	"\aORU_R01\x12$\n" +
	"\x03MSH\x18\x01 \x01(\v2\x12.standards.v23.MSHR\x03MSH\x124\n" +
	"\aresults\x18\x02 \x03(\v2\x1a.standards.v23.ResultGroupR\aresults\x12$\n" +
	"\x03DSC\x18\x03 \x01(\v2\x12.standards.v23.DSCR\x03DSCB1Z/github.com/s-hammon/hl7/proto/standards/v23;v23b\x06proto3"

var (
	file_standards_v23_messages_proto_rawDescOnce sync.Once
	file_standards_v23_messages_proto_rawDescData []byte
)

func file_standards_v23_messages_proto_rawDescGZIP() []byte {
	file_standards_v23_messages_proto_rawDescOnce.Do(func() {
		file_standards_v23_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_v23_messages_proto_rawDesc), len(file_standards_v23_messages_proto_rawDesc)))
	})
	return file_standards_v23_messages_proto_rawDescData
}

var file_standards_v23_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_v23_messages_proto_goTypes = []any{
	(*ORM_O01)(nil),      // 0: standards.v23.ORM_O01
	(*ORU_R01)(nil),      // 1: standards.v23.ORU_R01
	(*MSH)(nil),          // 2: standards.v23.MSH
	(*NTE)(nil),          // 3: standards.v23.NTE
	(*PatientGroup)(nil), // 4: standards.v23.PatientGroup
	(*OrderGroup)(nil),   // 5: standards.v23.OrderGroup
	(*ResultGroup)(nil),  // 6: standards.v23.ResultGroup
	(*DSC)(nil),          // 7: standards.v23.DSC
}
var file_standards_v23_messages_proto_depIdxs = []int32{
	2, // 0: standards.v23.ORM_O01.MSH:type_name -> standards.v23.MSH
	3, // 1: standards.v23.ORM_O01.NTE:type_name -> standards.v23.NTE
	4, // 2: standards.v23.ORM_O01.patient_group:type_name -> standards.v23.PatientGroup
	5, // 3: standards.v23.ORM_O01.order_groups:type_name -> standards.v23.OrderGroup
	2, // 4: standards.v23.ORU_R01.MSH:type_name -> standards.v23.MSH
	6, // 5: standards.v23.ORU_R01.results:type_name -> standards.v23.ResultGroup
	7, // 6: standards.v23.ORU_R01.DSC:type_name -> standards.v23.DSC
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_standards_v23_messages_proto_init() }
func file_standards_v23_messages_proto_init() {
	if File_standards_v23_messages_proto != nil {
		return
	}
	file_standards_v23_control_proto_init()
	file_standards_v23_groups_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_v23_messages_proto_rawDesc), len(file_standards_v23_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_v23_messages_proto_goTypes,
		DependencyIndexes: file_standards_v23_messages_proto_depIdxs,
		MessageInfos:      file_standards_v23_messages_proto_msgTypes,
	}.Build()
	File_standards_v23_messages_proto = out.File
	file_standards_v23_messages_proto_goTypes = nil
	file_standards_v23_messages_proto_depIdxs = nil
}
