// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: standards/v23/observation.proto

package v23

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OBX struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	SetId                        string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	ValueType                    string                 `protobuf:"bytes,2,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	ObservationIdentifier        *CE                    `protobuf:"bytes,3,opt,name=observation_identifier,json=observationIdentifier,proto3" json:"observation_identifier,omitempty"`
	ObservationSubId             string                 `protobuf:"bytes,4,opt,name=observation_sub_id,json=observationSubId,proto3" json:"observation_sub_id,omitempty"`
	ObservationValue             string                 `protobuf:"bytes,5,opt,name=observation_value,json=observationValue,proto3" json:"observation_value,omitempty"`
	Units                        *CE                    `protobuf:"bytes,6,opt,name=units,proto3" json:"units,omitempty"`
	ReferencesRange              string                 `protobuf:"bytes,7,opt,name=references_range,json=referencesRange,proto3" json:"references_range,omitempty"`
	AbnormalFlags                string                 `protobuf:"bytes,8,opt,name=abnormal_flags,json=abnormalFlags,proto3" json:"abnormal_flags,omitempty"`
	Probability                  string                 `protobuf:"bytes,9,opt,name=probability,proto3" json:"probability,omitempty"`
	AbnormalTestNature           string                 `protobuf:"bytes,10,opt,name=abnormal_test_nature,json=abnormalTestNature,proto3" json:"abnormal_test_nature,omitempty"`
	ResultStatus                 string                 `protobuf:"bytes,11,opt,name=result_status,json=resultStatus,proto3" json:"result_status,omitempty"`
	LastDateObservedNormalValues string                 `protobuf:"bytes,12,opt,name=last_date_observed_normal_values,json=lastDateObservedNormalValues,proto3" json:"last_date_observed_normal_values,omitempty"`
	UserDefinedAccessChecks      string                 `protobuf:"bytes,13,opt,name=user_defined_access_checks,json=userDefinedAccessChecks,proto3" json:"user_defined_access_checks,omitempty"`
	ObservationDateTime          string                 `protobuf:"bytes,14,opt,name=observation_date_time,json=observationDateTime,proto3" json:"observation_date_time,omitempty"`
	ProducerId                   *CE                    `protobuf:"bytes,15,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	ResponsibleObserver          *XCN                   `protobuf:"bytes,16,opt,name=responsible_observer,json=responsibleObserver,proto3" json:"responsible_observer,omitempty"`
	ObservationMethod            *CE                    `protobuf:"bytes,17,opt,name=observation_method,json=observationMethod,proto3" json:"observation_method,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *OBX) Reset() {
	*x = OBX{}
	mi := &file_standards_v23_observation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OBX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OBX) ProtoMessage() {}

func (x *OBX) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_observation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OBX.ProtoReflect.Descriptor instead.
func (*OBX) Descriptor() ([]byte, []int) {
	return file_standards_v23_observation_proto_rawDescGZIP(), []int{0}
}

func (x *OBX) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *OBX) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *OBX) GetObservationIdentifier() *CE {
	if x != nil {
		return x.ObservationIdentifier
	}
	return nil
}

func (x *OBX) GetObservationSubId() string {
	if x != nil {
		return x.ObservationSubId
	}
	return ""
}

func (x *OBX) GetObservationValue() string {
	if x != nil {
		return x.ObservationValue
	}
	return ""
}

func (x *OBX) GetUnits() *CE {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *OBX) GetReferencesRange() string {
	if x != nil {
		return x.ReferencesRange
	}
	return ""
}

func (x *OBX) GetAbnormalFlags() string {
	if x != nil {
		return x.AbnormalFlags
	}
	return ""
}

func (x *OBX) GetProbability() string {
	if x != nil {
		return x.Probability
	}
	return ""
}

func (x *OBX) GetAbnormalTestNature() string {
	if x != nil {
		return x.AbnormalTestNature
	}
	return ""
}

func (x *OBX) GetResultStatus() string {
	if x != nil {
		return x.ResultStatus
	}
	return ""
}

func (x *OBX) GetLastDateObservedNormalValues() string {
	if x != nil {
		return x.LastDateObservedNormalValues
	}
	return ""
}

func (x *OBX) GetUserDefinedAccessChecks() string {
	if x != nil {
		return x.UserDefinedAccessChecks
	}
	return ""
}

func (x *OBX) GetObservationDateTime() string {
	if x != nil {
		return x.ObservationDateTime
	}
	return ""
}

func (x *OBX) GetProducerId() *CE {
	if x != nil {
		return x.ProducerId
	}
	return nil
}

func (x *OBX) GetResponsibleObserver() *XCN {
	if x != nil {
		return x.ResponsibleObserver
	}
	return nil
}

func (x *OBX) GetObservationMethod() *CE {
	if x != nil {
		return x.ObservationMethod
	}
	return nil
}

var File_standards_v23_observation_proto protoreflect.FileDescriptor

const file_standards_v23_observation_proto_rawDesc = "" +
	"\n" +
	"\x1fstandards/v23/observation.proto\x12\rstandards.v23\x1a\x19standards/v23/types.proto\"\xca\x06\n" +
	"\x03OBX\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12\x1d\n" +
	"\n" +
	"value_type\x18\x02 \x01(\tR\tvalueType\x12H\n" +
	"\x16observation_identifier\x18\x03 \x01(\v2\x11.standards.v23.CER\x15observationIdentifier\x12,\n" +
	"\x12observation_sub_id\x18\x04 \x01(\tR\x10observationSubId\x12+\n" +
	"\x11observation_value\x18\x05 \x01(\tR\x10observationValue\x12'\n" +
	"\x05units\x18\x06 \x01(\v2\x11.standards.v23.CER\x05units\x12)\n" +
	"\x10references_range\x18\a \x01(\tR\x0freferencesRange\x12%\n" +
	"\x0eabnormal_flags\x18\b \x01(\tR\rabnormalFlags\x12 \n" +
	"\vprobability\x18\t \x01(\tR\vprobability\x120\n" +
	"\x14abnormal_test_nature\x18\n" +
	" \x01(\tR\x12abnormalTestNature\x12#\n" +
	"\rresult_status\x18\v \x01(\tR\fresultStatus\x12F\n" +
	" last_date_observed_normal_values\x18\f \x01(\tR\x1clastDateObservedNormalValues\x12;\n" +
	"\x1auser_defined_access_checks\x18\r \x01(\tR\x17userDefinedAccessChecks\x122\n" +
	"\x15observation_date_time\x18\x0e \x01(\tR\x13observationDateTime\x122\n" +
	"\vproducer_id\x18\x0f \x01(\v2\x11.standards.v23.CER\n" +
	"producerId\x12E\n" +
	"\x14responsible_observer\x18\x10 \x01(\v2\x12.standards.v23.XCNR\x13responsibleObserver\x12@\n" +
	"\x12observation_method\x18\x11 \x01(\v2\x11.standards.v23.CER\x11observationMethodB1Z/github.com/s-hammon/hl7/proto/standards/v23;v23b\x06proto3"

var (
	file_standards_v23_observation_proto_rawDescOnce sync.Once
	file_standards_v23_observation_proto_rawDescData []byte
)

func file_standards_v23_observation_proto_rawDescGZIP() []byte {
	file_standards_v23_observation_proto_rawDescOnce.Do(func() {
		file_standards_v23_observation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_v23_observation_proto_rawDesc), len(file_standards_v23_observation_proto_rawDesc)))
	})
	return file_standards_v23_observation_proto_rawDescData
}

var file_standards_v23_observation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_standards_v23_observation_proto_goTypes = []any{
	(*OBX)(nil), // 0: standards.v23.OBX
	(*CE)(nil),  // 1: standards.v23.CE
	(*XCN)(nil), // 2: standards.v23.XCN
}
var file_standards_v23_observation_proto_depIdxs = []int32{
	1, // 0: standards.v23.OBX.observation_identifier:type_name -> standards.v23.CE
	1, // 1: standards.v23.OBX.units:type_name -> standards.v23.CE
	1, // 2: standards.v23.OBX.producer_id:type_name -> standards.v23.CE
	2, // 3: standards.v23.OBX.responsible_observer:type_name -> standards.v23.XCN
	1, // 4: standards.v23.OBX.observation_method:type_name -> standards.v23.CE
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_standards_v23_observation_proto_init() }
func file_standards_v23_observation_proto_init() {
	if File_standards_v23_observation_proto != nil {
		return
	}
	file_standards_v23_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_v23_observation_proto_rawDesc), len(file_standards_v23_observation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_v23_observation_proto_goTypes,
		DependencyIndexes: file_standards_v23_observation_proto_depIdxs,
		MessageInfos:      file_standards_v23_observation_proto_msgTypes,
	}.Build()
	File_standards_v23_observation_proto = out.File
	file_standards_v23_observation_proto_goTypes = nil
	file_standards_v23_observation_proto_depIdxs = nil
}
