// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: standards/v23/order.proto

package v23

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ORC struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	OrderControl           string                 `protobuf:"bytes,1,opt,name=order_control,json=orderControl,proto3" json:"order_control,omitempty"`
	PlacerOrderNumber      string                 `protobuf:"bytes,2,opt,name=placer_order_number,json=placerOrderNumber,proto3" json:"placer_order_number,omitempty"`
	FillerOrderNumber      string                 `protobuf:"bytes,3,opt,name=filler_order_number,json=fillerOrderNumber,proto3" json:"filler_order_number,omitempty"`
	PlacerGroupNumber      string                 `protobuf:"bytes,4,opt,name=placer_group_number,json=placerGroupNumber,proto3" json:"placer_group_number,omitempty"`
	OrderStatus            string                 `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	ResponseFlag           string                 `protobuf:"bytes,6,opt,name=response_flag,json=responseFlag,proto3" json:"response_flag,omitempty"`
	QuantityTiming         *TQ                    `protobuf:"bytes,7,opt,name=quantity_timing,json=quantityTiming,proto3" json:"quantity_timing,omitempty"`
	Parent                 *CMPOR                 `protobuf:"bytes,8,opt,name=parent,proto3" json:"parent,omitempty"`
	TransactionDateTime    string                 `protobuf:"bytes,9,opt,name=transaction_date_time,json=transactionDateTime,proto3" json:"transaction_date_time,omitempty"`
	EnteredBy              *XCN                   `protobuf:"bytes,10,opt,name=entered_by,json=enteredBy,proto3" json:"entered_by,omitempty"`
	VerifiedBy             *XCN                   `protobuf:"bytes,11,opt,name=verified_by,json=verifiedBy,proto3" json:"verified_by,omitempty"`
	OrderingProvider       *XCN                   `protobuf:"bytes,12,opt,name=ordering_provider,json=orderingProvider,proto3" json:"ordering_provider,omitempty"`
	EntryLocation          *PL                    `protobuf:"bytes,13,opt,name=entry_location,json=entryLocation,proto3" json:"entry_location,omitempty"`
	CallbackPhoneNumber    *XTN                   `protobuf:"bytes,14,opt,name=callback_phone_number,json=callbackPhoneNumber,proto3" json:"callback_phone_number,omitempty"`
	EffectiveDateTime      string                 `protobuf:"bytes,15,opt,name=effective_date_time,json=effectiveDateTime,proto3" json:"effective_date_time,omitempty"`
	OrderControlCodeReason *CE                    `protobuf:"bytes,16,opt,name=order_control_code_reason,json=orderControlCodeReason,proto3" json:"order_control_code_reason,omitempty"`
	EnteringOrganization   *CE                    `protobuf:"bytes,17,opt,name=entering_organization,json=enteringOrganization,proto3" json:"entering_organization,omitempty"`
	EnteringDevice         *CE                    `protobuf:"bytes,18,opt,name=entering_device,json=enteringDevice,proto3" json:"entering_device,omitempty"`
	ActionBy               *XCN                   `protobuf:"bytes,19,opt,name=action_by,json=actionBy,proto3" json:"action_by,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ORC) Reset() {
	*x = ORC{}
	mi := &file_standards_v23_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ORC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ORC) ProtoMessage() {}

func (x *ORC) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ORC.ProtoReflect.Descriptor instead.
func (*ORC) Descriptor() ([]byte, []int) {
	return file_standards_v23_order_proto_rawDescGZIP(), []int{0}
}

func (x *ORC) GetOrderControl() string {
	if x != nil {
		return x.OrderControl
	}
	return ""
}

func (x *ORC) GetPlacerOrderNumber() string {
	if x != nil {
		return x.PlacerOrderNumber
	}
	return ""
}

func (x *ORC) GetFillerOrderNumber() string {
	if x != nil {
		return x.FillerOrderNumber
	}
	return ""
}

func (x *ORC) GetPlacerGroupNumber() string {
	if x != nil {
		return x.PlacerGroupNumber
	}
	return ""
}

func (x *ORC) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ORC) GetResponseFlag() string {
	if x != nil {
		return x.ResponseFlag
	}
	return ""
}

func (x *ORC) GetQuantityTiming() *TQ {
	if x != nil {
		return x.QuantityTiming
	}
	return nil
}

func (x *ORC) GetParent() *CMPOR {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *ORC) GetTransactionDateTime() string {
	if x != nil {
		return x.TransactionDateTime
	}
	return ""
}

func (x *ORC) GetEnteredBy() *XCN {
	if x != nil {
		return x.EnteredBy
	}
	return nil
}

func (x *ORC) GetVerifiedBy() *XCN {
	if x != nil {
		return x.VerifiedBy
	}
	return nil
}

func (x *ORC) GetOrderingProvider() *XCN {
	if x != nil {
		return x.OrderingProvider
	}
	return nil
}

func (x *ORC) GetEntryLocation() *PL {
	if x != nil {
		return x.EntryLocation
	}
	return nil
}

func (x *ORC) GetCallbackPhoneNumber() *XTN {
	if x != nil {
		return x.CallbackPhoneNumber
	}
	return nil
}

func (x *ORC) GetEffectiveDateTime() string {
	if x != nil {
		return x.EffectiveDateTime
	}
	return ""
}

func (x *ORC) GetOrderControlCodeReason() *CE {
	if x != nil {
		return x.OrderControlCodeReason
	}
	return nil
}

func (x *ORC) GetEnteringOrganization() *CE {
	if x != nil {
		return x.EnteringOrganization
	}
	return nil
}

func (x *ORC) GetEnteringDevice() *CE {
	if x != nil {
		return x.EnteringDevice
	}
	return nil
}

func (x *ORC) GetActionBy() *XCN {
	if x != nil {
		return x.ActionBy
	}
	return nil
}

type OBR struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	SetId                              string                 `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	PlacerOrderNumber                  string                 `protobuf:"bytes,2,opt,name=placer_order_number,json=placerOrderNumber,proto3" json:"placer_order_number,omitempty"`
	FillerOrderNumber                  string                 `protobuf:"bytes,3,opt,name=filler_order_number,json=fillerOrderNumber,proto3" json:"filler_order_number,omitempty"`
	UniversalServiceId                 *CE                    `protobuf:"bytes,4,opt,name=universal_service_id,json=universalServiceId,proto3" json:"universal_service_id,omitempty"`
	Priority                           string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	RequestedDateTime                  string                 `protobuf:"bytes,6,opt,name=requested_date_time,json=requestedDateTime,proto3" json:"requested_date_time,omitempty"`
	ObservationDateTime                string                 `protobuf:"bytes,7,opt,name=observation_date_time,json=observationDateTime,proto3" json:"observation_date_time,omitempty"`
	ObservationEndDateTime             string                 `protobuf:"bytes,8,opt,name=observation_end_date_time,json=observationEndDateTime,proto3" json:"observation_end_date_time,omitempty"`
	CollectionVolume                   *CQ                    `protobuf:"bytes,9,opt,name=collection_volume,json=collectionVolume,proto3" json:"collection_volume,omitempty"`
	CollectorIdentifier                *XCN                   `protobuf:"bytes,10,opt,name=collector_identifier,json=collectorIdentifier,proto3" json:"collector_identifier,omitempty"`
	SpecimenActionCode                 string                 `protobuf:"bytes,11,opt,name=specimen_action_code,json=specimenActionCode,proto3" json:"specimen_action_code,omitempty"`
	DangerCode                         *CE                    `protobuf:"bytes,12,opt,name=danger_code,json=dangerCode,proto3" json:"danger_code,omitempty"`
	RelevantClinicalInfo               string                 `protobuf:"bytes,13,opt,name=relevant_clinical_info,json=relevantClinicalInfo,proto3" json:"relevant_clinical_info,omitempty"`
	SpecimenReceivedDateTime           string                 `protobuf:"bytes,14,opt,name=specimen_received_date_time,json=specimenReceivedDateTime,proto3" json:"specimen_received_date_time,omitempty"`
	SpecimenSource                     *CMSPE                 `protobuf:"bytes,15,opt,name=specimen_source,json=specimenSource,proto3" json:"specimen_source,omitempty"`
	OrderingProvider                   *XCN                   `protobuf:"bytes,16,opt,name=ordering_provider,json=orderingProvider,proto3" json:"ordering_provider,omitempty"`
	OrderCallbackPhoneNumber           *XTN                   `protobuf:"bytes,17,opt,name=order_callback_phone_number,json=orderCallbackPhoneNumber,proto3" json:"order_callback_phone_number,omitempty"`
	PlacerField_1                      string                 `protobuf:"bytes,18,opt,name=placer_field_1,json=placerField1,proto3" json:"placer_field_1,omitempty"`
	PlacerField_2                      string                 `protobuf:"bytes,19,opt,name=placer_field_2,json=placerField2,proto3" json:"placer_field_2,omitempty"`
	FillerField_1                      string                 `protobuf:"bytes,20,opt,name=filler_field_1,json=fillerField1,proto3" json:"filler_field_1,omitempty"`
	FillerField_2                      string                 `protobuf:"bytes,21,opt,name=filler_field_2,json=fillerField2,proto3" json:"filler_field_2,omitempty"`
	StatusChangeDatTime                string                 `protobuf:"bytes,22,opt,name=status_change_dat_time,json=statusChangeDatTime,proto3" json:"status_change_dat_time,omitempty"`
	ChargeToPractice                   *CMCHP                 `protobuf:"bytes,23,opt,name=charge_to_practice,json=chargeToPractice,proto3" json:"charge_to_practice,omitempty"`
	DiagnosticServiceSectionId         string                 `protobuf:"bytes,24,opt,name=diagnostic_service_section_id,json=diagnosticServiceSectionId,proto3" json:"diagnostic_service_section_id,omitempty"`
	ResultStatus                       string                 `protobuf:"bytes,25,opt,name=result_status,json=resultStatus,proto3" json:"result_status,omitempty"`
	ParentResult                       *CMPRE                 `protobuf:"bytes,26,opt,name=parent_result,json=parentResult,proto3" json:"parent_result,omitempty"`
	QuantityTiming                     string                 `protobuf:"bytes,27,opt,name=quantity_timing,json=quantityTiming,proto3" json:"quantity_timing,omitempty"`
	ResultCopiesTo                     *XCN                   `protobuf:"bytes,28,opt,name=result_copies_to,json=resultCopiesTo,proto3" json:"result_copies_to,omitempty"`
	Parent                             *CMPOR                 `protobuf:"bytes,29,opt,name=parent,proto3" json:"parent,omitempty"`
	TransportationMode                 string                 `protobuf:"bytes,30,opt,name=transportation_mode,json=transportationMode,proto3" json:"transportation_mode,omitempty"`
	ReasonForStudy                     *CE                    `protobuf:"bytes,31,opt,name=reason_for_study,json=reasonForStudy,proto3" json:"reason_for_study,omitempty"`
	PrincipalResultInterpreter         *CMOBS                 `protobuf:"bytes,32,opt,name=principal_result_interpreter,json=principalResultInterpreter,proto3" json:"principal_result_interpreter,omitempty"`
	AssistantResultInterpreter         *CMOBS                 `protobuf:"bytes,33,opt,name=assistant_result_interpreter,json=assistantResultInterpreter,proto3" json:"assistant_result_interpreter,omitempty"`
	Technician                         *CMOBS                 `protobuf:"bytes,34,opt,name=technician,proto3" json:"technician,omitempty"`
	Transcriptionist                   *CMOBS                 `protobuf:"bytes,35,opt,name=transcriptionist,proto3" json:"transcriptionist,omitempty"`
	ScheduledDateTime                  string                 `protobuf:"bytes,36,opt,name=scheduled_date_time,json=scheduledDateTime,proto3" json:"scheduled_date_time,omitempty"`
	SampleContainersCount              string                 `protobuf:"bytes,37,opt,name=sample_containers_count,json=sampleContainersCount,proto3" json:"sample_containers_count,omitempty"`
	SampleTransportLogistics           *CE                    `protobuf:"bytes,38,opt,name=sample_transport_logistics,json=sampleTransportLogistics,proto3" json:"sample_transport_logistics,omitempty"`
	CollectorComment                   *CE                    `protobuf:"bytes,39,opt,name=collector_comment,json=collectorComment,proto3" json:"collector_comment,omitempty"`
	TransportArrangementResponsibility *CE                    `protobuf:"bytes,40,opt,name=transport_arrangement_responsibility,json=transportArrangementResponsibility,proto3" json:"transport_arrangement_responsibility,omitempty"`
	TransportArranged                  string                 `protobuf:"bytes,41,opt,name=transport_arranged,json=transportArranged,proto3" json:"transport_arranged,omitempty"`
	EscortRequired                     string                 `protobuf:"bytes,42,opt,name=escort_required,json=escortRequired,proto3" json:"escort_required,omitempty"`
	PlannedPatientTransportComment     *CE                    `protobuf:"bytes,43,opt,name=planned_patient_transport_comment,json=plannedPatientTransportComment,proto3" json:"planned_patient_transport_comment,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *OBR) Reset() {
	*x = OBR{}
	mi := &file_standards_v23_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OBR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OBR) ProtoMessage() {}

func (x *OBR) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OBR.ProtoReflect.Descriptor instead.
func (*OBR) Descriptor() ([]byte, []int) {
	return file_standards_v23_order_proto_rawDescGZIP(), []int{1}
}

func (x *OBR) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *OBR) GetPlacerOrderNumber() string {
	if x != nil {
		return x.PlacerOrderNumber
	}
	return ""
}

func (x *OBR) GetFillerOrderNumber() string {
	if x != nil {
		return x.FillerOrderNumber
	}
	return ""
}

func (x *OBR) GetUniversalServiceId() *CE {
	if x != nil {
		return x.UniversalServiceId
	}
	return nil
}

func (x *OBR) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *OBR) GetRequestedDateTime() string {
	if x != nil {
		return x.RequestedDateTime
	}
	return ""
}

func (x *OBR) GetObservationDateTime() string {
	if x != nil {
		return x.ObservationDateTime
	}
	return ""
}

func (x *OBR) GetObservationEndDateTime() string {
	if x != nil {
		return x.ObservationEndDateTime
	}
	return ""
}

func (x *OBR) GetCollectionVolume() *CQ {
	if x != nil {
		return x.CollectionVolume
	}
	return nil
}

func (x *OBR) GetCollectorIdentifier() *XCN {
	if x != nil {
		return x.CollectorIdentifier
	}
	return nil
}

func (x *OBR) GetSpecimenActionCode() string {
	if x != nil {
		return x.SpecimenActionCode
	}
	return ""
}

func (x *OBR) GetDangerCode() *CE {
	if x != nil {
		return x.DangerCode
	}
	return nil
}

func (x *OBR) GetRelevantClinicalInfo() string {
	if x != nil {
		return x.RelevantClinicalInfo
	}
	return ""
}

func (x *OBR) GetSpecimenReceivedDateTime() string {
	if x != nil {
		return x.SpecimenReceivedDateTime
	}
	return ""
}

func (x *OBR) GetSpecimenSource() *CMSPE {
	if x != nil {
		return x.SpecimenSource
	}
	return nil
}

func (x *OBR) GetOrderingProvider() *XCN {
	if x != nil {
		return x.OrderingProvider
	}
	return nil
}

func (x *OBR) GetOrderCallbackPhoneNumber() *XTN {
	if x != nil {
		return x.OrderCallbackPhoneNumber
	}
	return nil
}

func (x *OBR) GetPlacerField_1() string {
	if x != nil {
		return x.PlacerField_1
	}
	return ""
}

func (x *OBR) GetPlacerField_2() string {
	if x != nil {
		return x.PlacerField_2
	}
	return ""
}

func (x *OBR) GetFillerField_1() string {
	if x != nil {
		return x.FillerField_1
	}
	return ""
}

func (x *OBR) GetFillerField_2() string {
	if x != nil {
		return x.FillerField_2
	}
	return ""
}

func (x *OBR) GetStatusChangeDatTime() string {
	if x != nil {
		return x.StatusChangeDatTime
	}
	return ""
}

func (x *OBR) GetChargeToPractice() *CMCHP {
	if x != nil {
		return x.ChargeToPractice
	}
	return nil
}

func (x *OBR) GetDiagnosticServiceSectionId() string {
	if x != nil {
		return x.DiagnosticServiceSectionId
	}
	return ""
}

func (x *OBR) GetResultStatus() string {
	if x != nil {
		return x.ResultStatus
	}
	return ""
}

func (x *OBR) GetParentResult() *CMPRE {
	if x != nil {
		return x.ParentResult
	}
	return nil
}

func (x *OBR) GetQuantityTiming() string {
	if x != nil {
		return x.QuantityTiming
	}
	return ""
}

func (x *OBR) GetResultCopiesTo() *XCN {
	if x != nil {
		return x.ResultCopiesTo
	}
	return nil
}

func (x *OBR) GetParent() *CMPOR {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *OBR) GetTransportationMode() string {
	if x != nil {
		return x.TransportationMode
	}
	return ""
}

func (x *OBR) GetReasonForStudy() *CE {
	if x != nil {
		return x.ReasonForStudy
	}
	return nil
}

func (x *OBR) GetPrincipalResultInterpreter() *CMOBS {
	if x != nil {
		return x.PrincipalResultInterpreter
	}
	return nil
}

func (x *OBR) GetAssistantResultInterpreter() *CMOBS {
	if x != nil {
		return x.AssistantResultInterpreter
	}
	return nil
}

func (x *OBR) GetTechnician() *CMOBS {
	if x != nil {
		return x.Technician
	}
	return nil
}

func (x *OBR) GetTranscriptionist() *CMOBS {
	if x != nil {
		return x.Transcriptionist
	}
	return nil
}

func (x *OBR) GetScheduledDateTime() string {
	if x != nil {
		return x.ScheduledDateTime
	}
	return ""
}

func (x *OBR) GetSampleContainersCount() string {
	if x != nil {
		return x.SampleContainersCount
	}
	return ""
}

func (x *OBR) GetSampleTransportLogistics() *CE {
	if x != nil {
		return x.SampleTransportLogistics
	}
	return nil
}

func (x *OBR) GetCollectorComment() *CE {
	if x != nil {
		return x.CollectorComment
	}
	return nil
}

func (x *OBR) GetTransportArrangementResponsibility() *CE {
	if x != nil {
		return x.TransportArrangementResponsibility
	}
	return nil
}

func (x *OBR) GetTransportArranged() string {
	if x != nil {
		return x.TransportArranged
	}
	return ""
}

func (x *OBR) GetEscortRequired() string {
	if x != nil {
		return x.EscortRequired
	}
	return ""
}

func (x *OBR) GetPlannedPatientTransportComment() *CE {
	if x != nil {
		return x.PlannedPatientTransportComment
	}
	return nil
}

var File_standards_v23_order_proto protoreflect.FileDescriptor

const file_standards_v23_order_proto_rawDesc = "" +
	"\n" +
	"\x19standards/v23/order.proto\x12\rstandards.v23\x1a\x19standards/v23/types.proto\"\xfe\a\n" +
	"\x03ORC\x12#\n" +
	"\rorder_control\x18\x01 \x01(\tR\forderControl\x12.\n" +
	"\x13placer_order_number\x18\x02 \x01(\tR\x11placerOrderNumber\x12.\n" +
	"\x13filler_order_number\x18\x03 \x01(\tR\x11fillerOrderNumber\x12.\n" +
	"\x13placer_group_number\x18\x04 \x01(\tR\x11placerGroupNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x12#\n" +
	"\rresponse_flag\x18\x06 \x01(\tR\fresponseFlag\x12:\n" +
	"\x0fquantity_timing\x18\a \x01(\v2\x11.standards.v23.TQR\x0equantityTiming\x12,\n" +
	"\x06parent\x18\b \x01(\v2\x14.standards.v23.CMPORR\x06parent\x122\n" +
	"\x15transaction_date_time\x18\t \x01(\tR\x13transactionDateTime\x121\n" +
	"\n" +
	"entered_by\x18\n" +
	" \x01(\v2\x12.standards.v23.XCNR\tenteredBy\x123\n" +
	"\vverified_by\x18\v \x01(\v2\x12.standards.v23.XCNR\n" +
	"verifiedBy\x12?\n" +
	"\x11ordering_provider\x18\f \x01(\v2\x12.standards.v23.XCNR\x10orderingProvider\x128\n" +
	"\x0eentry_location\x18\r \x01(\v2\x11.standards.v23.PLR\rentryLocation\x12F\n" +
	"\x15callback_phone_number\x18\x0e \x01(\v2\x12.standards.v23.XTNR\x13callbackPhoneNumber\x12.\n" +
	"\x13effective_date_time\x18\x0f \x01(\tR\x11effectiveDateTime\x12L\n" +
	"\x19order_control_code_reason\x18\x10 \x01(\v2\x11.standards.v23.CER\x16orderControlCodeReason\x12F\n" +
	"\x15entering_organization\x18\x11 \x01(\v2\x11.standards.v23.CER\x14enteringOrganization\x12:\n" +
	"\x0fentering_device\x18\x12 \x01(\v2\x11.standards.v23.CER\x0eenteringDevice\x12/\n" +
	"\taction_by\x18\x13 \x01(\v2\x12.standards.v23.XCNR\bactionBy\"\xa4\x13\n" +
	"\x03OBR\x12\x15\n" +
	"\x06set_id\x18\x01 \x01(\tR\x05setId\x12.\n" +
	"\x13placer_order_number\x18\x02 \x01(\tR\x11placerOrderNumber\x12.\n" +
	"\x13filler_order_number\x18\x03 \x01(\tR\x11fillerOrderNumber\x12C\n" +
	"\x14universal_service_id\x18\x04 \x01(\v2\x11.standards.v23.CER\x12universalServiceId\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12.\n" +
	"\x13requested_date_time\x18\x06 \x01(\tR\x11requestedDateTime\x122\n" +
	"\x15observation_date_time\x18\a \x01(\tR\x13observationDateTime\x129\n" +
	"\x19observation_end_date_time\x18\b \x01(\tR\x16observationEndDateTime\x12>\n" +
	"\x11collection_volume\x18\t \x01(\v2\x11.standards.v23.CQR\x10collectionVolume\x12E\n" +
	"\x14collector_identifier\x18\n" +
	" \x01(\v2\x12.standards.v23.XCNR\x13collectorIdentifier\x120\n" +
	"\x14specimen_action_code\x18\v \x01(\tR\x12specimenActionCode\x122\n" +
	"\vdanger_code\x18\f \x01(\v2\x11.standards.v23.CER\n" +
	"dangerCode\x124\n" +
	"\x16relevant_clinical_info\x18\r \x01(\tR\x14relevantClinicalInfo\x12=\n" +
	"\x1bspecimen_received_date_time\x18\x0e \x01(\tR\x18specimenReceivedDateTime\x12=\n" +
	"\x0fspecimen_source\x18\x0f \x01(\v2\x14.standards.v23.CMSPER\x0especimenSource\x12?\n" +
	"\x11ordering_provider\x18\x10 \x01(\v2\x12.standards.v23.XCNR\x10orderingProvider\x12Q\n" +
	"\x1border_callback_phone_number\x18\x11 \x01(\v2\x12.standards.v23.XTNR\x18orderCallbackPhoneNumber\x12$\n" +
	"\x0eplacer_field_1\x18\x12 \x01(\tR\fplacerField1\x12$\n" +
	"\x0eplacer_field_2\x18\x13 \x01(\tR\fplacerField2\x12$\n" +
	"\x0efiller_field_1\x18\x14 \x01(\tR\ffillerField1\x12$\n" +
	"\x0efiller_field_2\x18\x15 \x01(\tR\ffillerField2\x123\n" +
	"\x16status_change_dat_time\x18\x16 \x01(\tR\x13statusChangeDatTime\x12B\n" +
	"\x12charge_to_practice\x18\x17 \x01(\v2\x14.standards.v23.CMCHPR\x10chargeToPractice\x12A\n" +
	"\x1ddiagnostic_service_section_id\x18\x18 \x01(\tR\x1adiagnosticServiceSectionId\x12#\n" +
	"\rresult_status\x18\x19 \x01(\tR\fresultStatus\x129\n" +
	"\rparent_result\x18\x1a \x01(\v2\x14.standards.v23.CMPRER\fparentResult\x12'\n" +
	"\x0fquantity_timing\x18\x1b \x01(\tR\x0equantityTiming\x12<\n" +
	"\x10result_copies_to\x18\x1c \x01(\v2\x12.standards.v23.XCNR\x0eresultCopiesTo\x12,\n" +
	"\x06parent\x18\x1d \x01(\v2\x14.standards.v23.CMPORR\x06parent\x12/\n" +
	"\x13transportation_mode\x18\x1e \x01(\tR\x12transportationMode\x12;\n" +
	"\x10reason_for_study\x18\x1f \x01(\v2\x11.standards.v23.CER\x0ereasonForStudy\x12V\n" +
	"\x1cprincipal_result_interpreter\x18  \x01(\v2\x14.standards.v23.CMOBSR\x1aprincipalResultInterpreter\x12V\n" +
	"\x1cassistant_result_interpreter\x18! \x01(\v2\x14.standards.v23.CMOBSR\x1aassistantResultInterpreter\x124\n" +
	"\n" +
	"technician\x18\" \x01(\v2\x14.standards.v23.CMOBSR\n" +
	"technician\x12@\n" +
	"\x10transcriptionist\x18# \x01(\v2\x14.standards.v23.CMOBSR\x10transcriptionist\x12.\n" +
	"\x13scheduled_date_time\x18$ \x01(\tR\x11scheduledDateTime\x126\n" +
	"\x17sample_containers_count\x18% \x01(\tR\x15sampleContainersCount\x12O\n" +
	"\x1asample_transport_logistics\x18& \x01(\v2\x11.standards.v23.CER\x18sampleTransportLogistics\x12>\n" +
	"\x11collector_comment\x18' \x01(\v2\x11.standards.v23.CER\x10collectorComment\x12c\n" +
	"$transport_arrangement_responsibility\x18( \x01(\v2\x11.standards.v23.CER\"transportArrangementResponsibility\x12-\n" +
	"\x12transport_arranged\x18) \x01(\tR\x11transportArranged\x12'\n" +
	"\x0fescort_required\x18* \x01(\tR\x0eescortRequired\x12\\\n" +
	"!planned_patient_transport_comment\x18+ \x01(\v2\x11.standards.v23.CER\x1eplannedPatientTransportCommentB1Z/github.com/s-hammon/hl7/proto/standards/v23;v23b\x06proto3"

var (
	file_standards_v23_order_proto_rawDescOnce sync.Once
	file_standards_v23_order_proto_rawDescData []byte
)

func file_standards_v23_order_proto_rawDescGZIP() []byte {
	file_standards_v23_order_proto_rawDescOnce.Do(func() {
		file_standards_v23_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_v23_order_proto_rawDesc), len(file_standards_v23_order_proto_rawDesc)))
	})
	return file_standards_v23_order_proto_rawDescData
}

var file_standards_v23_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_standards_v23_order_proto_goTypes = []any{
	(*ORC)(nil),   // 0: standards.v23.ORC
	(*OBR)(nil),   // 1: standards.v23.OBR
	(*TQ)(nil),    // 2: standards.v23.TQ
	(*CMPOR)(nil), // 3: standards.v23.CMPOR
	(*XCN)(nil),   // 4: standards.v23.XCN
	(*PL)(nil),    // 5: standards.v23.PL
	(*XTN)(nil),   // 6: standards.v23.XTN
	(*CE)(nil),    // 7: standards.v23.CE
	(*CQ)(nil),    // 8: standards.v23.CQ
	(*CMSPE)(nil), // 9: standards.v23.CMSPE
	(*CMCHP)(nil), // 10: standards.v23.CMCHP
	(*CMPRE)(nil), // 11: standards.v23.CMPRE
	(*CMOBS)(nil), // 12: standards.v23.CMOBS
}
var file_standards_v23_order_proto_depIdxs = []int32{
	2,  // 0: standards.v23.ORC.quantity_timing:type_name -> standards.v23.TQ
	3,  // 1: standards.v23.ORC.parent:type_name -> standards.v23.CMPOR
	4,  // 2: standards.v23.ORC.entered_by:type_name -> standards.v23.XCN
	4,  // 3: standards.v23.ORC.verified_by:type_name -> standards.v23.XCN
	4,  // 4: standards.v23.ORC.ordering_provider:type_name -> standards.v23.XCN
	5,  // 5: standards.v23.ORC.entry_location:type_name -> standards.v23.PL
	6,  // 6: standards.v23.ORC.callback_phone_number:type_name -> standards.v23.XTN
	7,  // 7: standards.v23.ORC.order_control_code_reason:type_name -> standards.v23.CE
	7,  // 8: standards.v23.ORC.entering_organization:type_name -> standards.v23.CE
	7,  // 9: standards.v23.ORC.entering_device:type_name -> standards.v23.CE
	4,  // 10: standards.v23.ORC.action_by:type_name -> standards.v23.XCN
	7,  // 11: standards.v23.OBR.universal_service_id:type_name -> standards.v23.CE
	8,  // 12: standards.v23.OBR.collection_volume:type_name -> standards.v23.CQ
	4,  // 13: standards.v23.OBR.collector_identifier:type_name -> standards.v23.XCN
	7,  // 14: standards.v23.OBR.danger_code:type_name -> standards.v23.CE
	9,  // 15: standards.v23.OBR.specimen_source:type_name -> standards.v23.CMSPE
	4,  // 16: standards.v23.OBR.ordering_provider:type_name -> standards.v23.XCN
	6,  // 17: standards.v23.OBR.order_callback_phone_number:type_name -> standards.v23.XTN
	10, // 18: standards.v23.OBR.charge_to_practice:type_name -> standards.v23.CMCHP
	11, // 19: standards.v23.OBR.parent_result:type_name -> standards.v23.CMPRE
	4,  // 20: standards.v23.OBR.result_copies_to:type_name -> standards.v23.XCN
	3,  // 21: standards.v23.OBR.parent:type_name -> standards.v23.CMPOR
	7,  // 22: standards.v23.OBR.reason_for_study:type_name -> standards.v23.CE
	12, // 23: standards.v23.OBR.principal_result_interpreter:type_name -> standards.v23.CMOBS
	12, // 24: standards.v23.OBR.assistant_result_interpreter:type_name -> standards.v23.CMOBS
	12, // 25: standards.v23.OBR.technician:type_name -> standards.v23.CMOBS
	12, // 26: standards.v23.OBR.transcriptionist:type_name -> standards.v23.CMOBS
	7,  // 27: standards.v23.OBR.sample_transport_logistics:type_name -> standards.v23.CE
	7,  // 28: standards.v23.OBR.collector_comment:type_name -> standards.v23.CE
	7,  // 29: standards.v23.OBR.transport_arrangement_responsibility:type_name -> standards.v23.CE
	7,  // 30: standards.v23.OBR.planned_patient_transport_comment:type_name -> standards.v23.CE
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_standards_v23_order_proto_init() }
func file_standards_v23_order_proto_init() {
	if File_standards_v23_order_proto != nil {
		return
	}
	file_standards_v23_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_v23_order_proto_rawDesc), len(file_standards_v23_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_v23_order_proto_goTypes,
		DependencyIndexes: file_standards_v23_order_proto_depIdxs,
		MessageInfos:      file_standards_v23_order_proto_msgTypes,
	}.Build()
	File_standards_v23_order_proto = out.File
	file_standards_v23_order_proto_goTypes = nil
	file_standards_v23_order_proto_depIdxs = nil
}
