// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: standards/v23/types.proto

package v23

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMMSG struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TriggerEvent  string                 `protobuf:"bytes,2,opt,name=trigger_event,json=triggerEvent,proto3" json:"trigger_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMMSG) Reset() {
	*x = CMMSG{}
	mi := &file_standards_v23_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMMSG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMMSG) ProtoMessage() {}

func (x *CMMSG) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMMSG.ProtoReflect.Descriptor instead.
func (*CMMSG) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{0}
}

func (x *CMMSG) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CMMSG) GetTriggerEvent() string {
	if x != nil {
		return x.TriggerEvent
	}
	return ""
}

type XCN struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IdNumber             string                 `protobuf:"bytes,1,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	FamilyName           string                 `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName            string                 `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	MiddleName           string                 `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Suffix               string                 `protobuf:"bytes,5,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Prefix               string                 `protobuf:"bytes,6,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Degree               string                 `protobuf:"bytes,7,opt,name=degree,proto3" json:"degree,omitempty"`
	SourceTable          string                 `protobuf:"bytes,8,opt,name=source_table,json=sourceTable,proto3" json:"source_table,omitempty"`
	AssigningAuthority   string                 `protobuf:"bytes,9,opt,name=assigning_authority,json=assigningAuthority,proto3" json:"assigning_authority,omitempty"`
	NameTypeCode         string                 `protobuf:"bytes,10,opt,name=name_type_code,json=nameTypeCode,proto3" json:"name_type_code,omitempty"`
	IdentifierCheckDigit string                 `protobuf:"bytes,11,opt,name=identifier_check_digit,json=identifierCheckDigit,proto3" json:"identifier_check_digit,omitempty"`
	CheckDigitSchemeCode string                 `protobuf:"bytes,12,opt,name=check_digit_scheme_code,json=checkDigitSchemeCode,proto3" json:"check_digit_scheme_code,omitempty"`
	IdentifierTypeCode   string                 `protobuf:"bytes,13,opt,name=identifier_type_code,json=identifierTypeCode,proto3" json:"identifier_type_code,omitempty"`
	AssigningFacility    string                 `protobuf:"bytes,14,opt,name=assigning_facility,json=assigningFacility,proto3" json:"assigning_facility,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *XCN) Reset() {
	*x = XCN{}
	mi := &file_standards_v23_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XCN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XCN) ProtoMessage() {}

func (x *XCN) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XCN.ProtoReflect.Descriptor instead.
func (*XCN) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{1}
}

func (x *XCN) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *XCN) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *XCN) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *XCN) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *XCN) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *XCN) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *XCN) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *XCN) GetSourceTable() string {
	if x != nil {
		return x.SourceTable
	}
	return ""
}

func (x *XCN) GetAssigningAuthority() string {
	if x != nil {
		return x.AssigningAuthority
	}
	return ""
}

func (x *XCN) GetNameTypeCode() string {
	if x != nil {
		return x.NameTypeCode
	}
	return ""
}

func (x *XCN) GetIdentifierCheckDigit() string {
	if x != nil {
		return x.IdentifierCheckDigit
	}
	return ""
}

func (x *XCN) GetCheckDigitSchemeCode() string {
	if x != nil {
		return x.CheckDigitSchemeCode
	}
	return ""
}

func (x *XCN) GetIdentifierTypeCode() string {
	if x != nil {
		return x.IdentifierTypeCode
	}
	return ""
}

func (x *XCN) GetAssigningFacility() string {
	if x != nil {
		return x.AssigningFacility
	}
	return ""
}

type CX struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CheckId                  string                 `protobuf:"bytes,2,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	CheckDigitIdentifierCode string                 `protobuf:"bytes,3,opt,name=check_digit_identifier_code,json=checkDigitIdentifierCode,proto3" json:"check_digit_identifier_code,omitempty"`
	AssigningAuthority       string                 `protobuf:"bytes,4,opt,name=assigning_authority,json=assigningAuthority,proto3" json:"assigning_authority,omitempty"`
	IdentifierTypeCode       string                 `protobuf:"bytes,5,opt,name=identifier_type_code,json=identifierTypeCode,proto3" json:"identifier_type_code,omitempty"`
	AssigningingFacility     string                 `protobuf:"bytes,6,opt,name=assigninging_facility,json=assigningingFacility,proto3" json:"assigninging_facility,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CX) Reset() {
	*x = CX{}
	mi := &file_standards_v23_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CX) ProtoMessage() {}

func (x *CX) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CX.ProtoReflect.Descriptor instead.
func (*CX) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{2}
}

func (x *CX) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CX) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *CX) GetCheckDigitIdentifierCode() string {
	if x != nil {
		return x.CheckDigitIdentifierCode
	}
	return ""
}

func (x *CX) GetAssigningAuthority() string {
	if x != nil {
		return x.AssigningAuthority
	}
	return ""
}

func (x *CX) GetIdentifierTypeCode() string {
	if x != nil {
		return x.IdentifierTypeCode
	}
	return ""
}

func (x *CX) GetAssigningingFacility() string {
	if x != nil {
		return x.AssigningingFacility
	}
	return ""
}

type XPN struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FamilyName             string                 `protobuf:"bytes,1,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName              string                 `protobuf:"bytes,2,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	MiddleName             string                 `protobuf:"bytes,3,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Suffix                 string                 `protobuf:"bytes,4,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Prefix                 string                 `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Degree                 string                 `protobuf:"bytes,6,opt,name=degree,proto3" json:"degree,omitempty"`
	NameTypeCode           string                 `protobuf:"bytes,7,opt,name=name_type_code,json=nameTypeCode,proto3" json:"name_type_code,omitempty"`
	NameRepresentationCode string                 `protobuf:"bytes,8,opt,name=name_representation_code,json=nameRepresentationCode,proto3" json:"name_representation_code,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *XPN) Reset() {
	*x = XPN{}
	mi := &file_standards_v23_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XPN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XPN) ProtoMessage() {}

func (x *XPN) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XPN.ProtoReflect.Descriptor instead.
func (*XPN) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{3}
}

func (x *XPN) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *XPN) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *XPN) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *XPN) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *XPN) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *XPN) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *XPN) GetNameTypeCode() string {
	if x != nil {
		return x.NameTypeCode
	}
	return ""
}

func (x *XPN) GetNameRepresentationCode() string {
	if x != nil {
		return x.NameRepresentationCode
	}
	return ""
}

type XAD struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	StreetAddress              string                 `protobuf:"bytes,1,opt,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"`
	OtherDesignation           string                 `protobuf:"bytes,2,opt,name=other_designation,json=otherDesignation,proto3" json:"other_designation,omitempty"`
	City                       string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                      string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Zip                        string                 `protobuf:"bytes,5,opt,name=zip,proto3" json:"zip,omitempty"`
	Country                    string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	AddressType                string                 `protobuf:"bytes,7,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	OtherGeographicDesignation string                 `protobuf:"bytes,8,opt,name=other_geographic_designation,json=otherGeographicDesignation,proto3" json:"other_geographic_designation,omitempty"`
	CountyCode                 string                 `protobuf:"bytes,9,opt,name=county_code,json=countyCode,proto3" json:"county_code,omitempty"`
	CensusTract                string                 `protobuf:"bytes,10,opt,name=census_tract,json=censusTract,proto3" json:"census_tract,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *XAD) Reset() {
	*x = XAD{}
	mi := &file_standards_v23_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XAD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAD) ProtoMessage() {}

func (x *XAD) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAD.ProtoReflect.Descriptor instead.
func (*XAD) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{4}
}

func (x *XAD) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *XAD) GetOtherDesignation() string {
	if x != nil {
		return x.OtherDesignation
	}
	return ""
}

func (x *XAD) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *XAD) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *XAD) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *XAD) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *XAD) GetAddressType() string {
	if x != nil {
		return x.AddressType
	}
	return ""
}

func (x *XAD) GetOtherGeographicDesignation() string {
	if x != nil {
		return x.OtherGeographicDesignation
	}
	return ""
}

func (x *XAD) GetCountyCode() string {
	if x != nil {
		return x.CountyCode
	}
	return ""
}

func (x *XAD) GetCensusTract() string {
	if x != nil {
		return x.CensusTract
	}
	return ""
}

type XTN struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Number                   string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	TelecommunicationUseCode string                 `protobuf:"bytes,2,opt,name=telecommunication_use_code,json=telecommunicationUseCode,proto3" json:"telecommunication_use_code,omitempty"`
	EquipmentType            string                 `protobuf:"bytes,3,opt,name=equipment_type,json=equipmentType,proto3" json:"equipment_type,omitempty"`
	EmailAddress             string                 `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	CountryCode              string                 `protobuf:"bytes,5,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	AreaCode                 string                 `protobuf:"bytes,6,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
	PhoneNumber              string                 `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Extension                string                 `protobuf:"bytes,8,opt,name=extension,proto3" json:"extension,omitempty"`
	AnyText                  string                 `protobuf:"bytes,9,opt,name=any_text,json=anyText,proto3" json:"any_text,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *XTN) Reset() {
	*x = XTN{}
	mi := &file_standards_v23_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XTN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XTN) ProtoMessage() {}

func (x *XTN) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XTN.ProtoReflect.Descriptor instead.
func (*XTN) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{5}
}

func (x *XTN) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *XTN) GetTelecommunicationUseCode() string {
	if x != nil {
		return x.TelecommunicationUseCode
	}
	return ""
}

func (x *XTN) GetEquipmentType() string {
	if x != nil {
		return x.EquipmentType
	}
	return ""
}

func (x *XTN) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *XTN) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *XTN) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *XTN) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *XTN) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *XTN) GetAnyText() string {
	if x != nil {
		return x.AnyText
	}
	return ""
}

type CE struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Identifier            string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Text                  string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	CodingSystem          string                 `protobuf:"bytes,3,opt,name=coding_system,json=codingSystem,proto3" json:"coding_system,omitempty"`
	AlternateIdentifier   string                 `protobuf:"bytes,4,opt,name=alternate_identifier,json=alternateIdentifier,proto3" json:"alternate_identifier,omitempty"`
	AlternateText         string                 `protobuf:"bytes,5,opt,name=alternate_text,json=alternateText,proto3" json:"alternate_text,omitempty"`
	AlternateCodingSystem string                 `protobuf:"bytes,6,opt,name=alternate_coding_system,json=alternateCodingSystem,proto3" json:"alternate_coding_system,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CE) Reset() {
	*x = CE{}
	mi := &file_standards_v23_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CE) ProtoMessage() {}

func (x *CE) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CE.ProtoReflect.Descriptor instead.
func (*CE) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{6}
}

func (x *CE) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *CE) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CE) GetCodingSystem() string {
	if x != nil {
		return x.CodingSystem
	}
	return ""
}

func (x *CE) GetAlternateIdentifier() string {
	if x != nil {
		return x.AlternateIdentifier
	}
	return ""
}

func (x *CE) GetAlternateText() string {
	if x != nil {
		return x.AlternateText
	}
	return ""
}

func (x *CE) GetAlternateCodingSystem() string {
	if x != nil {
		return x.AlternateCodingSystem
	}
	return ""
}

type DLN struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LicenseNumber  string                 `protobuf:"bytes,1,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	IssuingState   string                 `protobuf:"bytes,2,opt,name=issuing_state,json=issuingState,proto3" json:"issuing_state,omitempty"`
	ExpirationDate string                 `protobuf:"bytes,3,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DLN) Reset() {
	*x = DLN{}
	mi := &file_standards_v23_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLN) ProtoMessage() {}

func (x *DLN) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLN.ProtoReflect.Descriptor instead.
func (*DLN) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{7}
}

func (x *DLN) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *DLN) GetIssuingState() string {
	if x != nil {
		return x.IssuingState
	}
	return ""
}

func (x *DLN) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

type PL struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PointOfCare         string                 `protobuf:"bytes,1,opt,name=point_of_care,json=pointOfCare,proto3" json:"point_of_care,omitempty"`
	Room                string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Bed                 string                 `protobuf:"bytes,3,opt,name=bed,proto3" json:"bed,omitempty"`
	Facility            string                 `protobuf:"bytes,4,opt,name=facility,proto3" json:"facility,omitempty"`
	LocationStatus      string                 `protobuf:"bytes,5,opt,name=location_status,json=locationStatus,proto3" json:"location_status,omitempty"`
	PersonLocationType  string                 `protobuf:"bytes,6,opt,name=person_location_type,json=personLocationType,proto3" json:"person_location_type,omitempty"`
	Building            string                 `protobuf:"bytes,7,opt,name=building,proto3" json:"building,omitempty"`
	Floor               string                 `protobuf:"bytes,8,opt,name=floor,proto3" json:"floor,omitempty"`
	LocationDescription string                 `protobuf:"bytes,9,opt,name=location_description,json=locationDescription,proto3" json:"location_description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PL) Reset() {
	*x = PL{}
	mi := &file_standards_v23_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PL) ProtoMessage() {}

func (x *PL) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PL.ProtoReflect.Descriptor instead.
func (*PL) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{8}
}

func (x *PL) GetPointOfCare() string {
	if x != nil {
		return x.PointOfCare
	}
	return ""
}

func (x *PL) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *PL) GetBed() string {
	if x != nil {
		return x.Bed
	}
	return ""
}

func (x *PL) GetFacility() string {
	if x != nil {
		return x.Facility
	}
	return ""
}

func (x *PL) GetLocationStatus() string {
	if x != nil {
		return x.LocationStatus
	}
	return ""
}

func (x *PL) GetPersonLocationType() string {
	if x != nil {
		return x.PersonLocationType
	}
	return ""
}

func (x *PL) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *PL) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *PL) GetLocationDescription() string {
	if x != nil {
		return x.LocationDescription
	}
	return ""
}

type FC struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FinancialClass string                 `protobuf:"bytes,1,opt,name=financial_class,json=financialClass,proto3" json:"financial_class,omitempty"`
	EffectiveDate  string                 `protobuf:"bytes,2,opt,name=effective_date,json=effectiveDate,proto3" json:"effective_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FC) Reset() {
	*x = FC{}
	mi := &file_standards_v23_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FC) ProtoMessage() {}

func (x *FC) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FC.ProtoReflect.Descriptor instead.
func (*FC) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{9}
}

func (x *FC) GetFinancialClass() string {
	if x != nil {
		return x.FinancialClass
	}
	return ""
}

func (x *FC) GetEffectiveDate() string {
	if x != nil {
		return x.EffectiveDate
	}
	return ""
}

type CMDSL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	EffectiveDate string                 `protobuf:"bytes,2,opt,name=effective_date,json=effectiveDate,proto3" json:"effective_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMDSL) Reset() {
	*x = CMDSL{}
	mi := &file_standards_v23_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMDSL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMDSL) ProtoMessage() {}

func (x *CMDSL) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMDSL.ProtoReflect.Descriptor instead.
func (*CMDSL) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{10}
}

func (x *CMDSL) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CMDSL) GetEffectiveDate() string {
	if x != nil {
		return x.EffectiveDate
	}
	return ""
}

type XON struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OrganizationName     string                 `protobuf:"bytes,1,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	TypeCode             string                 `protobuf:"bytes,2,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`
	IdNumber             string                 `protobuf:"bytes,3,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	CheckDigit           string                 `protobuf:"bytes,4,opt,name=check_digit,json=checkDigit,proto3" json:"check_digit,omitempty"`
	CheckDigitSchemeCode string                 `protobuf:"bytes,5,opt,name=check_digit_scheme_code,json=checkDigitSchemeCode,proto3" json:"check_digit_scheme_code,omitempty"`
	AssigningAuthority   string                 `protobuf:"bytes,6,opt,name=assigning_authority,json=assigningAuthority,proto3" json:"assigning_authority,omitempty"`
	IdentifierTypeCode   string                 `protobuf:"bytes,7,opt,name=identifier_type_code,json=identifierTypeCode,proto3" json:"identifier_type_code,omitempty"`
	AssigningFacility    string                 `protobuf:"bytes,8,opt,name=assigning_facility,json=assigningFacility,proto3" json:"assigning_facility,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *XON) Reset() {
	*x = XON{}
	mi := &file_standards_v23_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XON) ProtoMessage() {}

func (x *XON) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XON.ProtoReflect.Descriptor instead.
func (*XON) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{11}
}

func (x *XON) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *XON) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *XON) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *XON) GetCheckDigit() string {
	if x != nil {
		return x.CheckDigit
	}
	return ""
}

func (x *XON) GetCheckDigitSchemeCode() string {
	if x != nil {
		return x.CheckDigitSchemeCode
	}
	return ""
}

func (x *XON) GetAssigningAuthority() string {
	if x != nil {
		return x.AssigningAuthority
	}
	return ""
}

func (x *XON) GetIdentifierTypeCode() string {
	if x != nil {
		return x.IdentifierTypeCode
	}
	return ""
}

func (x *XON) GetAssigningFacility() string {
	if x != nil {
		return x.AssigningFacility
	}
	return ""
}

type CP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	PriceType     string                 `protobuf:"bytes,2,opt,name=price_type,json=priceType,proto3" json:"price_type,omitempty"`
	FromValue     string                 `protobuf:"bytes,3,opt,name=from_value,json=fromValue,proto3" json:"from_value,omitempty"`
	ToValue       string                 `protobuf:"bytes,4,opt,name=to_value,json=toValue,proto3" json:"to_value,omitempty"`
	RangeUnits    *CE                    `protobuf:"bytes,5,opt,name=range_units,json=rangeUnits,proto3" json:"range_units,omitempty"`
	RanteType     string                 `protobuf:"bytes,6,opt,name=rante_type,json=ranteType,proto3" json:"rante_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CP) Reset() {
	*x = CP{}
	mi := &file_standards_v23_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CP) ProtoMessage() {}

func (x *CP) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CP.ProtoReflect.Descriptor instead.
func (*CP) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{12}
}

func (x *CP) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CP) GetPriceType() string {
	if x != nil {
		return x.PriceType
	}
	return ""
}

func (x *CP) GetFromValue() string {
	if x != nil {
		return x.FromValue
	}
	return ""
}

func (x *CP) GetToValue() string {
	if x != nil {
		return x.ToValue
	}
	return ""
}

func (x *CP) GetRangeUnits() *CE {
	if x != nil {
		return x.RangeUnits
	}
	return nil
}

func (x *CP) GetRanteType() string {
	if x != nil {
		return x.RanteType
	}
	return ""
}

type JCC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobCode       string                 `protobuf:"bytes,1,opt,name=job_code,json=jobCode,proto3" json:"job_code,omitempty"`
	JobClass      string                 `protobuf:"bytes,2,opt,name=job_class,json=jobClass,proto3" json:"job_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JCC) Reset() {
	*x = JCC{}
	mi := &file_standards_v23_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JCC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JCC) ProtoMessage() {}

func (x *JCC) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JCC.ProtoReflect.Descriptor instead.
func (*JCC) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{13}
}

func (x *JCC) GetJobCode() string {
	if x != nil {
		return x.JobCode
	}
	return ""
}

func (x *JCC) GetJobClass() string {
	if x != nil {
		return x.JobClass
	}
	return ""
}

type CMAUI struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationNumber string                 `protobuf:"bytes,1,opt,name=authorization_number,json=authorizationNumber,proto3" json:"authorization_number,omitempty"`
	Date                string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Source              string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CMAUI) Reset() {
	*x = CMAUI{}
	mi := &file_standards_v23_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMAUI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMAUI) ProtoMessage() {}

func (x *CMAUI) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMAUI.ProtoReflect.Descriptor instead.
func (*CMAUI) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{14}
}

func (x *CMAUI) GetAuthorizationNumber() string {
	if x != nil {
		return x.AuthorizationNumber
	}
	return ""
}

func (x *CMAUI) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CMAUI) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CMPLT struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomType       string                 `protobuf:"bytes,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	AmountType     string                 `protobuf:"bytes,2,opt,name=amount_type,json=amountType,proto3" json:"amount_type,omitempty"`
	CoverageAmount string                 `protobuf:"bytes,3,opt,name=coverage_amount,json=coverageAmount,proto3" json:"coverage_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CMPLT) Reset() {
	*x = CMPLT{}
	mi := &file_standards_v23_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMPLT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMPLT) ProtoMessage() {}

func (x *CMPLT) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMPLT.ProtoReflect.Descriptor instead.
func (*CMPLT) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{15}
}

func (x *CMPLT) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *CMPLT) GetAmountType() string {
	if x != nil {
		return x.AmountType
	}
	return ""
}

func (x *CMPLT) GetCoverageAmount() string {
	if x != nil {
		return x.CoverageAmount
	}
	return ""
}

type CMDDE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelayDays     string                 `protobuf:"bytes,1,opt,name=delay_days,json=delayDays,proto3" json:"delay_days,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	DayCount      string                 `protobuf:"bytes,3,opt,name=day_count,json=dayCount,proto3" json:"day_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMDDE) Reset() {
	*x = CMDDE{}
	mi := &file_standards_v23_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMDDE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMDDE) ProtoMessage() {}

func (x *CMDDE) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMDDE.ProtoReflect.Descriptor instead.
func (*CMDDE) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{16}
}

func (x *CMDDE) GetDelayDays() string {
	if x != nil {
		return x.DelayDays
	}
	return ""
}

func (x *CMDDE) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CMDDE) GetDayCount() string {
	if x != nil {
		return x.DayCount
	}
	return ""
}

type CMVAL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMVAL) Reset() {
	*x = CMVAL{}
	mi := &file_standards_v23_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMVAL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMVAL) ProtoMessage() {}

func (x *CMVAL) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMVAL.ProtoReflect.Descriptor instead.
func (*CMVAL) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{17}
}

func (x *CMVAL) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CMVAL) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type CMPCR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientType   string                 `protobuf:"bytes,1,opt,name=patient_type,json=patientType,proto3" json:"patient_type,omitempty"`
	Required      string                 `protobuf:"bytes,2,opt,name=required,proto3" json:"required,omitempty"`
	Window        string                 `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMPCR) Reset() {
	*x = CMPCR{}
	mi := &file_standards_v23_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMPCR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMPCR) ProtoMessage() {}

func (x *CMPCR) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMPCR.ProtoReflect.Descriptor instead.
func (*CMPCR) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{18}
}

func (x *CMPCR) GetPatientType() string {
	if x != nil {
		return x.PatientType
	}
	return ""
}

func (x *CMPCR) GetRequired() string {
	if x != nil {
		return x.Required
	}
	return ""
}

func (x *CMPCR) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type CQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      string                 `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Units         *CE                    `protobuf:"bytes,2,opt,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CQ) Reset() {
	*x = CQ{}
	mi := &file_standards_v23_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CQ) ProtoMessage() {}

func (x *CQ) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CQ.ProtoReflect.Descriptor instead.
func (*CQ) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{19}
}

func (x *CQ) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *CQ) GetUnits() *CE {
	if x != nil {
		return x.Units
	}
	return nil
}

type TQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      *CQ                    `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	StartDateTime string                 `protobuf:"bytes,4,opt,name=start_date_time,json=startDateTime,proto3" json:"start_date_time,omitempty"`
	EndDateTime   string                 `protobuf:"bytes,5,opt,name=end_date_time,json=endDateTime,proto3" json:"end_date_time,omitempty"`
	Priority      string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Condition     string                 `protobuf:"bytes,7,opt,name=condition,proto3" json:"condition,omitempty"`
	Text          string                 `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	Conjunction   string                 `protobuf:"bytes,9,opt,name=conjunction,proto3" json:"conjunction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TQ) Reset() {
	*x = TQ{}
	mi := &file_standards_v23_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TQ) ProtoMessage() {}

func (x *TQ) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TQ.ProtoReflect.Descriptor instead.
func (*TQ) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{20}
}

func (x *TQ) GetQuantity() *CQ {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *TQ) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *TQ) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *TQ) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *TQ) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

func (x *TQ) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *TQ) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *TQ) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TQ) GetConjunction() string {
	if x != nil {
		return x.Conjunction
	}
	return ""
}

type CMPOR struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlacerOrderNumber string                 `protobuf:"bytes,1,opt,name=placer_order_number,json=placerOrderNumber,proto3" json:"placer_order_number,omitempty"`
	FillerOrderNumber string                 `protobuf:"bytes,2,opt,name=filler_order_number,json=fillerOrderNumber,proto3" json:"filler_order_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CMPOR) Reset() {
	*x = CMPOR{}
	mi := &file_standards_v23_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMPOR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMPOR) ProtoMessage() {}

func (x *CMPOR) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMPOR.ProtoReflect.Descriptor instead.
func (*CMPOR) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{21}
}

func (x *CMPOR) GetPlacerOrderNumber() string {
	if x != nil {
		return x.PlacerOrderNumber
	}
	return ""
}

func (x *CMPOR) GetFillerOrderNumber() string {
	if x != nil {
		return x.FillerOrderNumber
	}
	return ""
}

type CMSPE struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Name                         *CE                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Additives                    string                 `protobuf:"bytes,2,opt,name=additives,proto3" json:"additives,omitempty"`
	FreeText                     string                 `protobuf:"bytes,3,opt,name=free_text,json=freeText,proto3" json:"free_text,omitempty"`
	BodySite                     *CE                    `protobuf:"bytes,4,opt,name=body_site,json=bodySite,proto3" json:"body_site,omitempty"`
	SiteModifier                 *CE                    `protobuf:"bytes,5,opt,name=site_modifier,json=siteModifier,proto3" json:"site_modifier,omitempty"`
	CollectionMethodModifierCode *CE                    `protobuf:"bytes,6,opt,name=collection_method_modifier_code,json=collectionMethodModifierCode,proto3" json:"collection_method_modifier_code,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CMSPE) Reset() {
	*x = CMSPE{}
	mi := &file_standards_v23_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMSPE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMSPE) ProtoMessage() {}

func (x *CMSPE) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMSPE.ProtoReflect.Descriptor instead.
func (*CMSPE) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{22}
}

func (x *CMSPE) GetName() *CE {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CMSPE) GetAdditives() string {
	if x != nil {
		return x.Additives
	}
	return ""
}

func (x *CMSPE) GetFreeText() string {
	if x != nil {
		return x.FreeText
	}
	return ""
}

func (x *CMSPE) GetBodySite() *CE {
	if x != nil {
		return x.BodySite
	}
	return nil
}

func (x *CMSPE) GetSiteModifier() *CE {
	if x != nil {
		return x.SiteModifier
	}
	return nil
}

func (x *CMSPE) GetCollectionMethodModifierCode() *CE {
	if x != nil {
		return x.CollectionMethodModifierCode
	}
	return nil
}

type MO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      string                 `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Denomination  string                 `protobuf:"bytes,2,opt,name=denomination,proto3" json:"denomination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MO) Reset() {
	*x = MO{}
	mi := &file_standards_v23_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MO) ProtoMessage() {}

func (x *MO) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MO.ProtoReflect.Descriptor instead.
func (*MO) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{23}
}

func (x *MO) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *MO) GetDenomination() string {
	if x != nil {
		return x.Denomination
	}
	return ""
}

type CMCHP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DollarAmount  *MO                    `protobuf:"bytes,1,opt,name=dollar_amount,json=dollarAmount,proto3" json:"dollar_amount,omitempty"`
	ChargeCode    *CE                    `protobuf:"bytes,2,opt,name=charge_code,json=chargeCode,proto3" json:"charge_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMCHP) Reset() {
	*x = CMCHP{}
	mi := &file_standards_v23_types_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMCHP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMCHP) ProtoMessage() {}

func (x *CMCHP) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMCHP.ProtoReflect.Descriptor instead.
func (*CMCHP) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{24}
}

func (x *CMCHP) GetDollarAmount() *MO {
	if x != nil {
		return x.DollarAmount
	}
	return nil
}

func (x *CMCHP) GetChargeCode() *CE {
	if x != nil {
		return x.ChargeCode
	}
	return nil
}

type CMPRE struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ObservationIdentifier *CE                    `protobuf:"bytes,1,opt,name=observation_identifier,json=observationIdentifier,proto3" json:"observation_identifier,omitempty"`
	SubId                 string                 `protobuf:"bytes,2,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	ObservationResult     string                 `protobuf:"bytes,3,opt,name=observation_result,json=observationResult,proto3" json:"observation_result,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CMPRE) Reset() {
	*x = CMPRE{}
	mi := &file_standards_v23_types_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMPRE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMPRE) ProtoMessage() {}

func (x *CMPRE) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMPRE.ProtoReflect.Descriptor instead.
func (*CMPRE) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{25}
}

func (x *CMPRE) GetObservationIdentifier() *CE {
	if x != nil {
		return x.ObservationIdentifier
	}
	return nil
}

func (x *CMPRE) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *CMPRE) GetObservationResult() string {
	if x != nil {
		return x.ObservationResult
	}
	return ""
}

type HD struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId     string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	UniversalId     string                 `protobuf:"bytes,2,opt,name=universal_id,json=universalId,proto3" json:"universal_id,omitempty"`
	UniversalIdType string                 `protobuf:"bytes,3,opt,name=universal_id_type,json=universalIdType,proto3" json:"universal_id_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HD) Reset() {
	*x = HD{}
	mi := &file_standards_v23_types_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HD) ProtoMessage() {}

func (x *HD) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HD.ProtoReflect.Descriptor instead.
func (*HD) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{26}
}

func (x *HD) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *HD) GetUniversalId() string {
	if x != nil {
		return x.UniversalId
	}
	return ""
}

func (x *HD) GetUniversalIdType() string {
	if x != nil {
		return x.UniversalIdType
	}
	return ""
}

type CN struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdNumber           string                 `protobuf:"bytes,1,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	FamilyName         string                 `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName          string                 `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	MiddleName         string                 `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Suffix             string                 `protobuf:"bytes,5,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Prefix             string                 `protobuf:"bytes,6,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Degree             string                 `protobuf:"bytes,7,opt,name=degree,proto3" json:"degree,omitempty"`
	SourceTable        string                 `protobuf:"bytes,8,opt,name=source_table,json=sourceTable,proto3" json:"source_table,omitempty"`
	AssigningAuthority *HD                    `protobuf:"bytes,9,opt,name=assigning_authority,json=assigningAuthority,proto3" json:"assigning_authority,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CN) Reset() {
	*x = CN{}
	mi := &file_standards_v23_types_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CN) ProtoMessage() {}

func (x *CN) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CN.ProtoReflect.Descriptor instead.
func (*CN) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{27}
}

func (x *CN) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *CN) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *CN) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *CN) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *CN) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *CN) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *CN) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *CN) GetSourceTable() string {
	if x != nil {
		return x.SourceTable
	}
	return ""
}

func (x *CN) GetAssigningAuthority() *HD {
	if x != nil {
		return x.AssigningAuthority
	}
	return nil
}

type CMOBS struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                *CN                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartDateTime       string                 `protobuf:"bytes,2,opt,name=start_date_time,json=startDateTime,proto3" json:"start_date_time,omitempty"`
	EndDateTime         string                 `protobuf:"bytes,3,opt,name=end_date_time,json=endDateTime,proto3" json:"end_date_time,omitempty"`
	PointOfCare         string                 `protobuf:"bytes,4,opt,name=point_of_care,json=pointOfCare,proto3" json:"point_of_care,omitempty"`
	Room                string                 `protobuf:"bytes,5,opt,name=room,proto3" json:"room,omitempty"`
	Bed                 string                 `protobuf:"bytes,6,opt,name=bed,proto3" json:"bed,omitempty"`
	Facility            *HD                    `protobuf:"bytes,7,opt,name=facility,proto3" json:"facility,omitempty"`
	LocationStatus      string                 `protobuf:"bytes,8,opt,name=location_status,json=locationStatus,proto3" json:"location_status,omitempty"`
	PatientLocationType string                 `protobuf:"bytes,9,opt,name=patient_location_type,json=patientLocationType,proto3" json:"patient_location_type,omitempty"`
	Building            string                 `protobuf:"bytes,10,opt,name=building,proto3" json:"building,omitempty"`
	Floor               string                 `protobuf:"bytes,11,opt,name=floor,proto3" json:"floor,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CMOBS) Reset() {
	*x = CMOBS{}
	mi := &file_standards_v23_types_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMOBS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMOBS) ProtoMessage() {}

func (x *CMOBS) ProtoReflect() protoreflect.Message {
	mi := &file_standards_v23_types_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMOBS.ProtoReflect.Descriptor instead.
func (*CMOBS) Descriptor() ([]byte, []int) {
	return file_standards_v23_types_proto_rawDescGZIP(), []int{28}
}

func (x *CMOBS) GetName() *CN {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CMOBS) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *CMOBS) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

func (x *CMOBS) GetPointOfCare() string {
	if x != nil {
		return x.PointOfCare
	}
	return ""
}

func (x *CMOBS) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *CMOBS) GetBed() string {
	if x != nil {
		return x.Bed
	}
	return ""
}

func (x *CMOBS) GetFacility() *HD {
	if x != nil {
		return x.Facility
	}
	return nil
}

func (x *CMOBS) GetLocationStatus() string {
	if x != nil {
		return x.LocationStatus
	}
	return ""
}

func (x *CMOBS) GetPatientLocationType() string {
	if x != nil {
		return x.PatientLocationType
	}
	return ""
}

func (x *CMOBS) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *CMOBS) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

var File_standards_v23_types_proto protoreflect.FileDescriptor

const file_standards_v23_types_proto_rawDesc = "" +
	"\n" +
	"\x19standards/v23/types.proto\x12\rstandards.v23\"@\n" +
	"\x05CMMSG\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rtrigger_event\x18\x02 \x01(\tR\ftriggerEvent\"\x93\x04\n" +
	"\x03XCN\x12\x1b\n" +
	"\tid_number\x18\x01 \x01(\tR\bidNumber\x12\x1f\n" +
	"\vfamily_name\x18\x02 \x01(\tR\n" +
	"familyName\x12\x1d\n" +
	"\n" +
	"given_name\x18\x03 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vmiddle_name\x18\x04 \x01(\tR\n" +
	"middleName\x12\x16\n" +
	"\x06suffix\x18\x05 \x01(\tR\x06suffix\x12\x16\n" +
	"\x06prefix\x18\x06 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06degree\x18\a \x01(\tR\x06degree\x12!\n" +
	"\fsource_table\x18\b \x01(\tR\vsourceTable\x12/\n" +
	"\x13assigning_authority\x18\t \x01(\tR\x12assigningAuthority\x12$\n" +
	"\x0ename_type_code\x18\n" +
	" \x01(\tR\fnameTypeCode\x124\n" +
	"\x16identifier_check_digit\x18\v \x01(\tR\x14identifierCheckDigit\x125\n" +
	"\x17check_digit_scheme_code\x18\f \x01(\tR\x14checkDigitSchemeCode\x120\n" +
	"\x14identifier_type_code\x18\r \x01(\tR\x12identifierTypeCode\x12-\n" +
	"\x12assigning_facility\x18\x0e \x01(\tR\x11assigningFacility\"\x86\x02\n" +
	"\x02CX\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bcheck_id\x18\x02 \x01(\tR\acheckId\x12=\n" +
	"\x1bcheck_digit_identifier_code\x18\x03 \x01(\tR\x18checkDigitIdentifierCode\x12/\n" +
	"\x13assigning_authority\x18\x04 \x01(\tR\x12assigningAuthority\x120\n" +
	"\x14identifier_type_code\x18\x05 \x01(\tR\x12identifierTypeCode\x123\n" +
	"\x15assigninging_facility\x18\x06 \x01(\tR\x14assigningingFacility\"\x8e\x02\n" +
	"\x03XPN\x12\x1f\n" +
	"\vfamily_name\x18\x01 \x01(\tR\n" +
	"familyName\x12\x1d\n" +
	"\n" +
	"given_name\x18\x02 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vmiddle_name\x18\x03 \x01(\tR\n" +
	"middleName\x12\x16\n" +
	"\x06suffix\x18\x04 \x01(\tR\x06suffix\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06degree\x18\x06 \x01(\tR\x06degree\x12$\n" +
	"\x0ename_type_code\x18\a \x01(\tR\fnameTypeCode\x128\n" +
	"\x18name_representation_code\x18\b \x01(\tR\x16nameRepresentationCode\"\xd8\x02\n" +
	"\x03XAD\x12%\n" +
	"\x0estreet_address\x18\x01 \x01(\tR\rstreetAddress\x12+\n" +
	"\x11other_designation\x18\x02 \x01(\tR\x10otherDesignation\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x05 \x01(\tR\x03zip\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12!\n" +
	"\faddress_type\x18\a \x01(\tR\vaddressType\x12@\n" +
	"\x1cother_geographic_designation\x18\b \x01(\tR\x1aotherGeographicDesignation\x12\x1f\n" +
	"\vcounty_code\x18\t \x01(\tR\n" +
	"countyCode\x12!\n" +
	"\fcensus_tract\x18\n" +
	" \x01(\tR\vcensusTract\"\xc3\x02\n" +
	"\x03XTN\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12<\n" +
	"\x1atelecommunication_use_code\x18\x02 \x01(\tR\x18telecommunicationUseCode\x12%\n" +
	"\x0eequipment_type\x18\x03 \x01(\tR\requipmentType\x12#\n" +
	"\remail_address\x18\x04 \x01(\tR\femailAddress\x12!\n" +
	"\fcountry_code\x18\x05 \x01(\tR\vcountryCode\x12\x1b\n" +
	"\tarea_code\x18\x06 \x01(\tR\bareaCode\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x1c\n" +
	"\textension\x18\b \x01(\tR\textension\x12\x19\n" +
	"\bany_text\x18\t \x01(\tR\aanyText\"\xef\x01\n" +
	"\x02CE\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\rcoding_system\x18\x03 \x01(\tR\fcodingSystem\x121\n" +
	"\x14alternate_identifier\x18\x04 \x01(\tR\x13alternateIdentifier\x12%\n" +
	"\x0ealternate_text\x18\x05 \x01(\tR\ralternateText\x126\n" +
	"\x17alternate_coding_system\x18\x06 \x01(\tR\x15alternateCodingSystem\"z\n" +
	"\x03DLN\x12%\n" +
	"\x0elicense_number\x18\x01 \x01(\tR\rlicenseNumber\x12#\n" +
	"\rissuing_state\x18\x02 \x01(\tR\fissuingState\x12'\n" +
	"\x0fexpiration_date\x18\x03 \x01(\tR\x0eexpirationDate\"\xaa\x02\n" +
	"\x02PL\x12\"\n" +
	"\rpoint_of_care\x18\x01 \x01(\tR\vpointOfCare\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x10\n" +
	"\x03bed\x18\x03 \x01(\tR\x03bed\x12\x1a\n" +
	"\bfacility\x18\x04 \x01(\tR\bfacility\x12'\n" +
	"\x0flocation_status\x18\x05 \x01(\tR\x0elocationStatus\x120\n" +
	"\x14person_location_type\x18\x06 \x01(\tR\x12personLocationType\x12\x1a\n" +
	"\bbuilding\x18\a \x01(\tR\bbuilding\x12\x14\n" +
	"\x05floor\x18\b \x01(\tR\x05floor\x121\n" +
	"\x14location_description\x18\t \x01(\tR\x13locationDescription\"T\n" +
	"\x02FC\x12'\n" +
	"\x0ffinancial_class\x18\x01 \x01(\tR\x0efinancialClass\x12%\n" +
	"\x0eeffective_date\x18\x02 \x01(\tR\reffectiveDate\"J\n" +
	"\x05CMDSL\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12%\n" +
	"\x0eeffective_date\x18\x02 \x01(\tR\reffectiveDate\"\xd6\x02\n" +
	"\x03XON\x12+\n" +
	"\x11organization_name\x18\x01 \x01(\tR\x10organizationName\x12\x1b\n" +
	"\ttype_code\x18\x02 \x01(\tR\btypeCode\x12\x1b\n" +
	"\tid_number\x18\x03 \x01(\tR\bidNumber\x12\x1f\n" +
	"\vcheck_digit\x18\x04 \x01(\tR\n" +
	"checkDigit\x125\n" +
	"\x17check_digit_scheme_code\x18\x05 \x01(\tR\x14checkDigitSchemeCode\x12/\n" +
	"\x13assigning_authority\x18\x06 \x01(\tR\x12assigningAuthority\x120\n" +
	"\x14identifier_type_code\x18\a \x01(\tR\x12identifierTypeCode\x12-\n" +
	"\x12assigning_facility\x18\b \x01(\tR\x11assigningFacility\"\xc6\x01\n" +
	"\x02CP\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x1d\n" +
	"\n" +
	"price_type\x18\x02 \x01(\tR\tpriceType\x12\x1d\n" +
	"\n" +
	"from_value\x18\x03 \x01(\tR\tfromValue\x12\x19\n" +
	"\bto_value\x18\x04 \x01(\tR\atoValue\x122\n" +
	"\vrange_units\x18\x05 \x01(\v2\x11.standards.v23.CER\n" +
	"rangeUnits\x12\x1d\n" +
	"\n" +
	"rante_type\x18\x06 \x01(\tR\tranteType\"=\n" +
	"\x03JCC\x12\x19\n" +
	"\bjob_code\x18\x01 \x01(\tR\ajobCode\x12\x1b\n" +
	"\tjob_class\x18\x02 \x01(\tR\bjobClass\"f\n" +
	"\x05CMAUI\x121\n" +
	"\x14authorization_number\x18\x01 \x01(\tR\x13authorizationNumber\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"n\n" +
	"\x05CMPLT\x12\x1b\n" +
	"\troom_type\x18\x01 \x01(\tR\broomType\x12\x1f\n" +
	"\vamount_type\x18\x02 \x01(\tR\n" +
	"amountType\x12'\n" +
	"\x0fcoverage_amount\x18\x03 \x01(\tR\x0ecoverageAmount\"[\n" +
	"\x05CMDDE\x12\x1d\n" +
	"\n" +
	"delay_days\x18\x01 \x01(\tR\tdelayDays\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1b\n" +
	"\tday_count\x18\x03 \x01(\tR\bdayCount\"3\n" +
	"\x05CMVAL\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"^\n" +
	"\x05CMPCR\x12!\n" +
	"\fpatient_type\x18\x01 \x01(\tR\vpatientType\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\tR\brequired\x12\x16\n" +
	"\x06window\x18\x03 \x01(\tR\x06window\"I\n" +
	"\x02CQ\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\tR\bquantity\x12'\n" +
	"\x05units\x18\x02 \x01(\v2\x11.standards.v23.CER\x05units\"\xa7\x02\n" +
	"\x02TQ\x12-\n" +
	"\bquantity\x18\x01 \x01(\v2\x11.standards.v23.CQR\bquantity\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12&\n" +
	"\x0fstart_date_time\x18\x04 \x01(\tR\rstartDateTime\x12\"\n" +
	"\rend_date_time\x18\x05 \x01(\tR\vendDateTime\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12\x1c\n" +
	"\tcondition\x18\a \x01(\tR\tcondition\x12\x12\n" +
	"\x04text\x18\b \x01(\tR\x04text\x12 \n" +
	"\vconjunction\x18\t \x01(\tR\vconjunction\"g\n" +
	"\x05CMPOR\x12.\n" +
	"\x13placer_order_number\x18\x01 \x01(\tR\x11placerOrderNumber\x12.\n" +
	"\x13filler_order_number\x18\x02 \x01(\tR\x11fillerOrderNumber\"\xab\x02\n" +
	"\x05CMSPE\x12%\n" +
	"\x04name\x18\x01 \x01(\v2\x11.standards.v23.CER\x04name\x12\x1c\n" +
	"\tadditives\x18\x02 \x01(\tR\tadditives\x12\x1b\n" +
	"\tfree_text\x18\x03 \x01(\tR\bfreeText\x12.\n" +
	"\tbody_site\x18\x04 \x01(\v2\x11.standards.v23.CER\bbodySite\x126\n" +
	"\rsite_modifier\x18\x05 \x01(\v2\x11.standards.v23.CER\fsiteModifier\x12X\n" +
	"\x1fcollection_method_modifier_code\x18\x06 \x01(\v2\x11.standards.v23.CER\x1ccollectionMethodModifierCode\"D\n" +
	"\x02MO\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\tR\bquantity\x12\"\n" +
	"\fdenomination\x18\x02 \x01(\tR\fdenomination\"s\n" +
	"\x05CMCHP\x126\n" +
	"\rdollar_amount\x18\x01 \x01(\v2\x11.standards.v23.MOR\fdollarAmount\x122\n" +
	"\vcharge_code\x18\x02 \x01(\v2\x11.standards.v23.CER\n" +
	"chargeCode\"\x97\x01\n" +
	"\x05CMPRE\x12H\n" +
	"\x16observation_identifier\x18\x01 \x01(\v2\x11.standards.v23.CER\x15observationIdentifier\x12\x15\n" +
	"\x06sub_id\x18\x02 \x01(\tR\x05subId\x12-\n" +
	"\x12observation_result\x18\x03 \x01(\tR\x11observationResult\"v\n" +
	"\x02HD\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12!\n" +
	"\funiversal_id\x18\x02 \x01(\tR\vuniversalId\x12*\n" +
	"\x11universal_id_type\x18\x03 \x01(\tR\x0funiversalIdType\"\xb1\x02\n" +
	"\x02CN\x12\x1b\n" +
	"\tid_number\x18\x01 \x01(\tR\bidNumber\x12\x1f\n" +
	"\vfamily_name\x18\x02 \x01(\tR\n" +
	"familyName\x12\x1d\n" +
	"\n" +
	"given_name\x18\x03 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vmiddle_name\x18\x04 \x01(\tR\n" +
	"middleName\x12\x16\n" +
	"\x06suffix\x18\x05 \x01(\tR\x06suffix\x12\x16\n" +
	"\x06prefix\x18\x06 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06degree\x18\a \x01(\tR\x06degree\x12!\n" +
	"\fsource_table\x18\b \x01(\tR\vsourceTable\x12B\n" +
	"\x13assigning_authority\x18\t \x01(\v2\x11.standards.v23.HDR\x12assigningAuthority\"\x82\x03\n" +
	"\x05CMOBS\x12%\n" +
	"\x04name\x18\x01 \x01(\v2\x11.standards.v23.CNR\x04name\x12&\n" +
	"\x0fstart_date_time\x18\x02 \x01(\tR\rstartDateTime\x12\"\n" +
	"\rend_date_time\x18\x03 \x01(\tR\vendDateTime\x12\"\n" +
	"\rpoint_of_care\x18\x04 \x01(\tR\vpointOfCare\x12\x12\n" +
	"\x04room\x18\x05 \x01(\tR\x04room\x12\x10\n" +
	"\x03bed\x18\x06 \x01(\tR\x03bed\x12-\n" +
	"\bfacility\x18\a \x01(\v2\x11.standards.v23.HDR\bfacility\x12'\n" +
	"\x0flocation_status\x18\b \x01(\tR\x0elocationStatus\x122\n" +
	"\x15patient_location_type\x18\t \x01(\tR\x13patientLocationType\x12\x1a\n" +
	"\bbuilding\x18\n" +
	" \x01(\tR\bbuilding\x12\x14\n" +
	"\x05floor\x18\v \x01(\tR\x05floorB1Z/github.com/s-hammon/hl7/proto/standards/v23;v23b\x06proto3"

var (
	file_standards_v23_types_proto_rawDescOnce sync.Once
	file_standards_v23_types_proto_rawDescData []byte
)

func file_standards_v23_types_proto_rawDescGZIP() []byte {
	file_standards_v23_types_proto_rawDescOnce.Do(func() {
		file_standards_v23_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standards_v23_types_proto_rawDesc), len(file_standards_v23_types_proto_rawDesc)))
	})
	return file_standards_v23_types_proto_rawDescData
}

var file_standards_v23_types_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_standards_v23_types_proto_goTypes = []any{
	(*CMMSG)(nil), // 0: standards.v23.CMMSG
	(*XCN)(nil),   // 1: standards.v23.XCN
	(*CX)(nil),    // 2: standards.v23.CX
	(*XPN)(nil),   // 3: standards.v23.XPN
	(*XAD)(nil),   // 4: standards.v23.XAD
	(*XTN)(nil),   // 5: standards.v23.XTN
	(*CE)(nil),    // 6: standards.v23.CE
	(*DLN)(nil),   // 7: standards.v23.DLN
	(*PL)(nil),    // 8: standards.v23.PL
	(*FC)(nil),    // 9: standards.v23.FC
	(*CMDSL)(nil), // 10: standards.v23.CMDSL
	(*XON)(nil),   // 11: standards.v23.XON
	(*CP)(nil),    // 12: standards.v23.CP
	(*JCC)(nil),   // 13: standards.v23.JCC
	(*CMAUI)(nil), // 14: standards.v23.CMAUI
	(*CMPLT)(nil), // 15: standards.v23.CMPLT
	(*CMDDE)(nil), // 16: standards.v23.CMDDE
	(*CMVAL)(nil), // 17: standards.v23.CMVAL
	(*CMPCR)(nil), // 18: standards.v23.CMPCR
	(*CQ)(nil),    // 19: standards.v23.CQ
	(*TQ)(nil),    // 20: standards.v23.TQ
	(*CMPOR)(nil), // 21: standards.v23.CMPOR
	(*CMSPE)(nil), // 22: standards.v23.CMSPE
	(*MO)(nil),    // 23: standards.v23.MO
	(*CMCHP)(nil), // 24: standards.v23.CMCHP
	(*CMPRE)(nil), // 25: standards.v23.CMPRE
	(*HD)(nil),    // 26: standards.v23.HD
	(*CN)(nil),    // 27: standards.v23.CN
	(*CMOBS)(nil), // 28: standards.v23.CMOBS
}
var file_standards_v23_types_proto_depIdxs = []int32{
	6,  // 0: standards.v23.CP.range_units:type_name -> standards.v23.CE
	6,  // 1: standards.v23.CQ.units:type_name -> standards.v23.CE
	19, // 2: standards.v23.TQ.quantity:type_name -> standards.v23.CQ
	6,  // 3: standards.v23.CMSPE.name:type_name -> standards.v23.CE
	6,  // 4: standards.v23.CMSPE.body_site:type_name -> standards.v23.CE
	6,  // 5: standards.v23.CMSPE.site_modifier:type_name -> standards.v23.CE
	6,  // 6: standards.v23.CMSPE.collection_method_modifier_code:type_name -> standards.v23.CE
	23, // 7: standards.v23.CMCHP.dollar_amount:type_name -> standards.v23.MO
	6,  // 8: standards.v23.CMCHP.charge_code:type_name -> standards.v23.CE
	6,  // 9: standards.v23.CMPRE.observation_identifier:type_name -> standards.v23.CE
	26, // 10: standards.v23.CN.assigning_authority:type_name -> standards.v23.HD
	27, // 11: standards.v23.CMOBS.name:type_name -> standards.v23.CN
	26, // 12: standards.v23.CMOBS.facility:type_name -> standards.v23.HD
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_standards_v23_types_proto_init() }
func file_standards_v23_types_proto_init() {
	if File_standards_v23_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standards_v23_types_proto_rawDesc), len(file_standards_v23_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_standards_v23_types_proto_goTypes,
		DependencyIndexes: file_standards_v23_types_proto_depIdxs,
		MessageInfos:      file_standards_v23_types_proto_msgTypes,
	}.Build()
	File_standards_v23_types_proto = out.File
	file_standards_v23_types_proto_goTypes = nil
	file_standards_v23_types_proto_depIdxs = nil
}
